from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .admin_api import (
    AdminAccountDetailView,
    AdminAccountListView,
    AdminAccountRoleView,
    AdminAccountSessionsView,
    AdminAuditView,
    AdminComponentListView,
    AdminOverviewView,
    AdminSiteDetailView,
    AdminSiteListView,
    AdminSystemView,
)
from .views import (
    ReportSharedComponentView,
    ShareComponentView,
    SharedComponentDetailView,
    SharedComponentListView,
    SharedComponentViewCountView,
    UseSharedComponentView,
    SharedComponentVisibilityView,
    WithdrawSharedComponentView,
    AdminComponentModerateView,
    AdminComponentReportResolveView,
    AdminComponentReportsView,
    AdminReportResolveView,
    AdminReportsView,
    AdminSettingsView,
    AdminStatsView,
    AdminSiteModerateView,
    AdminSitePinView,
    AdminUserSuspendView,
    AdminUsersView,
    CloneSiteView,
    PublicConfigView,
    PublicFormSubmissionView,
    ExploreView,
    FavoriteToggleView,
    FavoritesView,
    GoogleLoginView,
    GlobalSearchView,
    LocalAiProxyView,
    LocalAiStatusView,
    LoginView,
    DomainAllowedView,
    GuestAdoptView,
    GuestSessionView,
    GuestUpgradeView,
    MeView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    ProfileView,
    SavedThemesView,
    PublicProfileView,
    PublicReviewView,
    PublicSiteView,
    RegisterView,
    ReportSiteView,
    SiteViewCountView,
    SiteViewSet,
    UploadedImageViewSet,
)

router = DefaultRouter()
router.register(r'sites', SiteViewSet, basename='site')
router.register(r'images', UploadedImageViewSet, basename='image')

urlpatterns = [
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/google/', GoogleLoginView.as_view(), name='google-login'),
    path('auth/password/reset/', PasswordResetRequestView.as_view(), name='password-reset'),
    path('auth/password/reset/confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('auth/guest/', GuestSessionView.as_view(), name='guest-session'),
    path('auth/adopt/', GuestAdoptView.as_view(), name='guest-adopt'),
    path('auth/upgrade/', GuestUpgradeView.as_view(), name='guest-upgrade'),
    path('auth/me/', MeView.as_view(), name='me'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/themes/', SavedThemesView.as_view(), name='saved-themes'),
    path('explore/', ExploreView.as_view(), name='explore'),
    path('search/', GlobalSearchView.as_view(), name='global-search'),
    path('favorites/', FavoritesView.as_view(), name='favorites'),
    # BEFORE the router so these aren't shadowed by the owner-scoped SiteViewSet.
    path('sites/<int:site_id>/favorite/', FavoriteToggleView.as_view(), name='site-favorite'),
    path('sites/<int:site_id>/report/', ReportSiteView.as_view(), name='site-report'),
    path('sites/clone/<slug:slug>/', CloneSiteView.as_view(), name='site-clone'),
    path('public/profiles/<int:user_id>/', PublicProfileView.as_view(), name='public-profile'),
    path('public/config/', PublicConfigView.as_view(), name='public-config'),
    # Asked by the TLS layer before issuing a certificate for a custom domain.
    path('public/domain-allowed/', DomainAllowedView.as_view(), name='domain-allowed'),
    path('admin/settings/', AdminSettingsView.as_view(), name='admin-settings'),
    path('admin/stats/', AdminStatsView.as_view(), name='admin-stats'),
    path('admin/users/', AdminUsersView.as_view(), name='admin-users'),
    path('admin/users/<int:user_id>/suspend/', AdminUserSuspendView.as_view(), name='admin-user-suspend'),
    path('admin/sites/<int:site_id>/moderate/', AdminSiteModerateView.as_view(), name='admin-site-moderate'),
    path('admin/sites/<int:site_id>/pin/', AdminSitePinView.as_view(), name='admin-site-pin'),
    path('admin/reports/', AdminReportsView.as_view(), name='admin-reports'),
    path('admin/reports/<int:report_id>/resolve/', AdminReportResolveView.as_view(), name='admin-report-resolve'),
    path('public/sites/<slug:slug>/', PublicSiteView.as_view(), name='public-site'),
    path('public/sites/<slug:slug>/view/', SiteViewCountView.as_view(), name='public-site-view'),
    path('public/sites/<slug:slug>/submit/', PublicFormSubmissionView.as_view(), name='public-site-submit'),
    path('public/reviews/<uuid:token>/', PublicReviewView.as_view(), name='public-review'),
    path('ai/local/status/', LocalAiStatusView.as_view(), name='local-ai-status'),
    path('ai/local/proxy/', LocalAiProxyView.as_view(), name='local-ai-proxy'),
    # Community components
    path('public/components/', SharedComponentListView.as_view(), name='shared-components'),
    path('public/components/<int:component_id>/', SharedComponentDetailView.as_view(), name='shared-component'),
    path('public/components/<int:component_id>/view/', SharedComponentViewCountView.as_view(), name='shared-component-view'),
    path('public/components/<int:component_id>/use/', UseSharedComponentView.as_view(), name='shared-component-use'),
    path('public/components/<int:component_id>/report/', ReportSharedComponentView.as_view(), name='shared-component-report'),
    path('components/', ShareComponentView.as_view(), name='share-component'),
    path('components/<int:component_id>/withdraw/', WithdrawSharedComponentView.as_view(), name='shared-component-withdraw'),
    path('components/<int:component_id>/visibility/', SharedComponentVisibilityView.as_view(), name='shared-component-visibility'),
    path('admin/component-reports/', AdminComponentReportsView.as_view(), name='admin-component-reports'),
    path('admin/component-reports/<int:report_id>/resolve/', AdminComponentReportResolveView.as_view(), name='admin-component-report-resolve'),
    path('admin/components/<int:component_id>/moderate/', AdminComponentModerateView.as_view(), name='admin-component-moderate'),
    # Admin console (admin_api.py)
    path('admin/overview/', AdminOverviewView.as_view(), name='admin-overview'),
    path('admin/accounts/', AdminAccountListView.as_view(), name='admin-accounts'),
    path('admin/accounts/<int:user_id>/', AdminAccountDetailView.as_view(), name='admin-account'),
    path('admin/accounts/<int:user_id>/role/', AdminAccountRoleView.as_view(), name='admin-account-role'),
    path('admin/accounts/<int:user_id>/sessions/', AdminAccountSessionsView.as_view(), name='admin-account-sessions'),
    path('admin/sites/', AdminSiteListView.as_view(), name='admin-sites'),
    path('admin/sites/<int:site_id>/', AdminSiteDetailView.as_view(), name='admin-site'),
    path('admin/components/', AdminComponentListView.as_view(), name='admin-components'),
    path('admin/audit/', AdminAuditView.as_view(), name='admin-audit'),
    path('admin/system/', AdminSystemView.as_view(), name='admin-system'),
    path('', include(router.urls)),
]
