// Boxes and fields: cards, alerts, containers, accordions, inputs and selects.
import { FONT, copy, photo, variant } from './kit.js'

const CARD = `${FONT}width:100%;max-width:360px;border-radius:18px;background:#ffffff;border:1px solid #e2e8f0;overflow:hidden;color:#0f172a;`
const small = (text, extra = '') => `<span style="font-size:13.5px;color:#64748b;${extra}">${text}</span>`
const cardButton = (label, style = 'background:#0f172a;color:#ffffff;') => `<a href="#" style="display:inline-block;padding:10px 18px;border-radius:10px;text-decoration:none;font-weight:700;font-size:14.5px;${style}">${label}</a>`
const chip = (text, style = 'background:#f1f5f9;color:#334155;') => `<span style="display:inline-block;padding:4px 10px;border-radius:999px;font-size:12.5px;font-weight:700;${style}">${text}</span>`

export const CARDS = [
  variant('blog-post', copy('Blog post', 'Blog yazısı'), (T) => `<article style="${CARD}">${photo('card-blog', 720, 420)}<div style="padding:20px;">${chip(T('Guide', 'Rehber'), 'background:#eef2ff;color:#4338ca;')}<h3 style="margin:12px 0 8px;font-size:19px;line-height:1.3;">${T('How to photograph your products with a phone', 'Ürünlerinizi telefonla nasıl fotoğraflarsınız')}</h3>${small(T('12 May · 6 min read', '12 Mayıs · 6 dk okuma'))}</div></article>`),
  variant('event', copy('Event', 'Etkinlik'), (T) => `<article style="${CARD}display:flex;gap:16px;align-items:center;padding:18px;"><div style="flex-shrink:0;display:grid;place-items:center;width:64px;height:68px;border-radius:14px;background:#4f46e5;color:#ffffff;text-align:center;line-height:1.05;"><b style="font-size:24px;">14</b><span style="font-size:12px;font-weight:800;text-transform:uppercase;">${T('Jun', 'Haz')}</span></div><div><h3 style="margin:0 0 4px;font-size:17px;">${T('Summer wine tasting', 'Yaz şarap tadımı')}</h3>${small(T('The cellar · 19:00', 'Mahzen · 19.00'))}</div></article>`),
  variant('service-price', copy('Service with price', 'Fiyatlı hizmet'), (T) => `<article style="${CARD}padding:24px;"><span aria-hidden="true" style="display:inline-grid;place-items:center;width:46px;height:46px;border-radius:14px;background:#fef3c7;color:#b45309;font-size:22px;margin-bottom:14px;">✂</span><h3 style="margin:0 0 6px;font-size:19px;">${T('Cut and style', 'Kesim ve şekillendirme')}</h3><p style="margin:0 0 16px;color:#64748b;line-height:1.6;font-size:15px;">${T('Consultation, wash, cut and finish.', 'Ön görüşme, yıkama, kesim ve şekillendirme.')}</p><div style="display:flex;justify-content:space-between;align-items:center;"><b style="font-size:22px;">€45</b>${cardButton(T('Book', 'Randevu al'))}</div></article>`),
  variant('review', copy('Review', 'Değerlendirme'), (T) => `<article style="${CARD}padding:22px;"><div aria-label="5/5" style="color:#f59e0b;letter-spacing:2px;margin-bottom:10px;">★★★★★</div><p style="margin:0 0 16px;line-height:1.65;">“${T('Beautiful quality and it arrived the next day. Already ordered a second one.', 'Kalitesi çok güzel ve ertesi gün geldi. Şimdiden ikincisini sipariş ettim.')}”</p><div style="display:flex;align-items:center;gap:10px;"><span aria-hidden="true" style="display:grid;place-items:center;width:38px;height:38px;border-radius:50%;background:#0d9488;color:#ffffff;font-weight:800;">L</span><span><b style="display:block;font-size:14.5px;">Leyla</b>${small(T('Verified buyer', 'Doğrulanmış alıcı'))}</span></div></article>`),
  variant('stat-trend', copy('Stat with trend', 'Eğilimli istatistik'), (T) => `<article style="${CARD}padding:22px;">${small(T('Monthly visitors', 'Aylık ziyaretçi'), 'font-weight:600;')}<div style="display:flex;align-items:baseline;gap:10px;margin:6px 0 10px;"><b style="font-size:36px;letter-spacing:-0.02em;">24,180</b><span style="padding:3px 8px;border-radius:999px;background:#dcfce7;color:#15803d;font-size:13px;font-weight:700;">▲ 12%</span></div><svg aria-hidden="true" viewBox="0 0 200 40" style="display:block;width:100%;height:40px;"><polyline points="0,32 25,28 50,30 75,20 100,24 125,14 150,16 175,8 200,6" fill="none" stroke="#16a34a" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg></article>`),
  variant('contact-person', copy('Contact person', 'İletişim kişisi'), (T) => `<article style="${CARD}padding:22px;text-align:center;"><span aria-hidden="true" style="display:inline-grid;place-items:center;width:72px;height:72px;border-radius:50%;background:linear-gradient(135deg,#6366f1,#a855f7);color:#ffffff;font-weight:800;font-size:28px;margin-bottom:12px;">D</span><h3 style="margin:0 0 2px;font-size:18px;">Deniz Arslan</h3><p style="margin:0 0 14px;color:#6366f1;font-weight:700;font-size:14px;">${T('Sales lead', 'Satış sorumlusu')}</p><p style="margin:0;line-height:1.8;font-size:14.5px;color:#334155;">✉ deniz@example.com<br />☎ +90 212 555 01 01</p></article>`),
  variant('download-file', copy('File download', 'Dosya indirme'), (T) => `<article style="${CARD}display:flex;align-items:center;gap:14px;padding:16px;"><span aria-hidden="true" style="flex-shrink:0;display:grid;place-items:center;width:48px;height:56px;border-radius:10px;background:#fee2e2;color:#b91c1c;font-weight:900;font-size:12px;">PDF</span><div style="flex:1;min-width:0;"><b style="display:block;font-size:15px;">${T('Price list 2026', 'Fiyat listesi 2026')}</b>${small('2.4 MB')}</div>${cardButton('↓', 'background:#f1f5f9;color:#0f172a;padding:10px 14px;')}</article>`),
  variant('recipe', copy('Recipe', 'Tarif'), (T) => `<article style="${CARD}">${photo('card-recipe', 720, 460)}<div style="padding:18px 20px;"><h3 style="margin:0 0 10px;font-size:19px;">${T('Lemon and herb chicken', 'Limonlu ve otlu tavuk')}</h3><div style="display:flex;gap:16px;font-size:14px;color:#475569;"><span>◷ 40 ${T('min', 'dk')}</span><span>◉ ${T('Easy', 'Kolay')}</span><span>♨ 4 ${T('servings', 'porsiyon')}</span></div></div></article>`),
  variant('job', copy('Job opening', 'İş ilanı'), (T) => `<article style="${CARD}padding:22px;"><h3 style="margin:0 0 6px;font-size:19px;">${T('Product designer', 'Ürün tasarımcısı')}</h3><p style="margin:0 0 14px;color:#64748b;font-size:14.5px;">${T('Istanbul or remote', 'İstanbul ya da uzaktan')}</p><div style="display:flex;flex-wrap:wrap;gap:6px;margin-bottom:18px;">${chip(T('Full-time', 'Tam zamanlı'))}${chip(T('Design', 'Tasarım'))}${chip(T('Senior', 'Kıdemli'))}</div>${cardButton(T('Apply', 'Başvurun'), 'background:#4f46e5;color:#ffffff;')}</article>`),
  variant('course', copy('Course', 'Kurs'), (T) => `<article style="${CARD}">${photo('card-course', 720, 400)}<div style="padding:18px 20px;">${small(T('12 lessons · 4 hours', '12 ders · 4 saat'), 'font-weight:600;')}<h3 style="margin:6px 0 14px;font-size:19px;line-height:1.3;">${T('Watercolour for beginners', 'Yeni başlayanlar için suluboya')}</h3><div style="display:flex;justify-content:space-between;align-items:center;"><b style="font-size:20px;color:#7c3aed;">€49</b>${cardButton(T('Enrol', 'Kaydolun'), 'background:#7c3aed;color:#ffffff;')}</div></div></article>`),
  variant('property', copy('Property listing', 'Emlak ilanı'), (T) => `<article style="${CARD}"><div style="position:relative;">${photo('card-house', 720, 460)}<span style="position:absolute;top:12px;left:12px;padding:5px 10px;border-radius:8px;background:#ffffff;color:#0f172a;font-weight:800;font-size:13px;">${T('For sale', 'Satılık')}</span></div><div style="padding:18px 20px;"><b style="display:block;font-size:22px;margin-bottom:4px;">€385,000</b><p style="margin:0 0 12px;color:#64748b;font-size:14.5px;">${T('Garden Street 8, Old Town', 'Bahçe Sokak 8, Eski Şehir')}</p><div style="display:flex;gap:16px;font-size:14px;color:#334155;"><span>3 ${T('beds', 'oda')}</span><span>2 ${T('baths', 'banyo')}</span><span>140 m²</span></div></div></article>`),
  variant('room', copy('Hotel room', 'Otel odası'), (T) => `<article style="${CARD}">${photo('card-room', 720, 440)}<div style="padding:18px 20px;display:flex;justify-content:space-between;align-items:end;gap:12px;"><div><h3 style="margin:0 0 4px;font-size:18px;">${T('Sea view double', 'Deniz manzaralı çift kişilik')}</h3>${small(T('Breakfast included', 'Kahvaltı dahil'))}</div><div style="text-align:right;"><b style="font-size:20px;">€140</b><br />${small(T('/ night', '/ gece'))}</div></div></article>`),
  variant('feature-dark', copy('Dark feature', 'Koyu özellik'), (T) => `<article style="${FONT}width:100%;max-width:340px;padding:26px;border-radius:20px;background:radial-gradient(120% 90% at 0% 0%,#312e81,#0b1120 70%);color:#e2e8f0;"><span aria-hidden="true" style="display:inline-grid;place-items:center;width:46px;height:46px;border-radius:14px;background:rgba(129,140,248,0.2);color:#a5b4fc;font-size:22px;margin-bottom:16px;">⚡</span><h3 style="margin:0 0 8px;font-size:19px;color:#ffffff;">${T('Instant publishing', 'Anında yayın')}</h3><p style="margin:0;line-height:1.6;color:#94a3b8;">${T('Changes go live the moment you press save.', 'Değişiklikler kaydet’e bastığınız anda yayında.')}</p></article>`),
  variant('coloured-quote', copy('Coloured quote', 'Renkli alıntı'), (T) => `<article style="${FONT}width:100%;max-width:340px;padding:26px;border-radius:20px;background:#fde68a;color:#422006;"><p style="margin:0 0 18px;font-size:20px;font-weight:700;line-height:1.4;">“${T('The kindest team we have ever worked with.', 'Birlikte çalıştığımız en nazik ekip.')}”</p><span style="font-size:14px;font-weight:700;">— ${T('Olive Tree Yoga', 'Zeytin Ağacı Yoga')}</span></article>`),
  variant('membership', copy('Membership tier', 'Üyelik paketi'), (T) => `<article style="${CARD}padding:24px;border:2px solid #0d9488;"><span style="display:inline-block;padding:4px 10px;border-radius:999px;background:#ccfbf1;color:#115e59;font-size:12.5px;font-weight:800;margin-bottom:12px;">${T('Most chosen', 'En çok tercih edilen')}</span><h3 style="margin:0 0 4px;font-size:20px;">${T('Monthly pass', 'Aylık üyelik')}</h3><div style="margin:0 0 14px;"><b style="font-size:34px;">€69</b>${small(T('/month', '/ay'))}</div><p style="margin:0 0 16px;color:#475569;line-height:1.7;font-size:14.5px;">✓ ${T('Unlimited classes', 'Sınırsız ders')}<br />✓ ${T('Sauna access', 'Sauna kullanımı')}<br />✓ ${T('Bring a friend once', 'Bir kez arkadaş getirme')}</p>${cardButton(T('Join', 'Katılın'), 'background:#0d9488;color:#ffffff;display:block;text-align:center;')}</article>`),
  variant('episode', copy('Podcast episode', 'Podcast bölümü'), (T) => `<article style="${CARD}display:flex;gap:14px;align-items:center;padding:14px;"><span aria-hidden="true" style="flex-shrink:0;width:72px;height:72px;border-radius:14px;background:linear-gradient(135deg,#f97316,#db2777);"></span><div style="flex:1;min-width:0;">${small(`${T('Episode', 'Bölüm')} 42 · 48 ${T('min', 'dk')}`)}<b style="display:block;margin:2px 0 0;font-size:15.5px;line-height:1.35;">${T('Opening a second location', 'İkinci şubeyi açmak')}</b></div><a href="#" aria-label="${T('Play', 'Oynat')}" style="flex-shrink:0;display:grid;place-items:center;width:42px;height:42px;border-radius:50%;background:#0f172a;color:#ffffff;text-decoration:none;">▶</a></article>`),
  variant('location', copy('Location', 'Konum'), (T) => `<article style="${CARD}"><div aria-hidden="true" style="position:relative;height:130px;background:#e8f1ec;background-image:linear-gradient(#d4e4da 2px,transparent 2px),linear-gradient(90deg,#d4e4da 2px,transparent 2px);background-size:40px 40px;"><span style="position:absolute;left:50%;top:50%;width:20px;height:20px;border-radius:50% 50% 50% 0;transform:translate(-50%,-70%) rotate(-45deg);background:#dc2626;border:3px solid #ffffff;"></span></div><div style="padding:18px 20px;"><h3 style="margin:0 0 4px;font-size:17px;">${T('Kadıköy shop', 'Kadıköy mağazası')}</h3>${small(T('Moda Street 21 · Open until 20:00', 'Moda Caddesi 21 · 20.00’ye kadar açık'))}</div></article>`),
  variant('coupon', copy('Coupon', 'Kupon'), (T) => `<article style="${FONT}width:100%;max-width:360px;display:flex;border-radius:16px;overflow:hidden;background:#fff7ed;border:2px dashed #fb923c;color:#7c2d12;"><div style="display:grid;place-items:center;padding:18px;background:#fb923c;color:#ffffff;"><b style="font-size:26px;">−15%</b></div><div style="padding:16px 18px;"><b style="display:block;margin-bottom:4px;">${T('Welcome gift', 'Hoş geldin hediyesi')}</b><span style="font-size:14px;">${T('Use code', 'Kodu kullanın:')} <code style="font-weight:800;letter-spacing:0.08em;">HELLO15</code></span></div></article>`),
  variant('track', copy('Music track', 'Müzik parçası'), (T) => `<article style="${FONT}width:100%;max-width:360px;padding:16px;border-radius:18px;background:#111827;color:#f9fafb;"><div style="display:flex;gap:14px;align-items:center;margin-bottom:14px;"><span aria-hidden="true" style="flex-shrink:0;width:56px;height:56px;border-radius:12px;background:linear-gradient(135deg,#22d3ee,#6366f1);"></span><div><b style="display:block;">${T('Harbour Lights', 'Liman Işıkları')}</b><span style="font-size:13.5px;color:#9ca3af;">The Quiet Hours</span></div></div><div style="display:flex;align-items:center;gap:10px;"><span aria-hidden="true">▶</span><div style="flex:1;height:5px;border-radius:99px;background:#374151;"><div style="width:42%;height:100%;border-radius:99px;background:#22d3ee;"></div></div><span style="font-size:12.5px;color:#9ca3af;">1:32</span></div></article>`),
  variant('countdown', copy('Countdown card', 'Geri sayım kartı'), (T) => `<article style="${CARD}padding:20px;text-align:center;"><p style="margin:0 0 12px;font-weight:700;">${T('Sale ends in', 'İndirimin bitmesine')}</p><div style="display:flex;justify-content:center;gap:8px;">${[['02', T('days', 'gün')], ['14', T('hrs', 'sa')], ['36', T('min', 'dk')]].map(([n, l]) => `<div style="min-width:64px;padding:10px 6px;border-radius:12px;background:#f1f5f9;"><b style="display:block;font-size:24px;">${n}</b><span style="font-size:12px;color:#64748b;">${l}</span></div>`).join('')}</div></article>`),
]

export const ALERTS = [
  variant('error', copy('Error', 'Hata'), (T) => `<div role="alert" style="${FONT}display:flex;gap:12px;align-items:flex-start;padding:14px 16px;border-radius:12px;background:#fef2f2;border:1px solid #fecaca;color:#991b1b;"><span aria-hidden="true" style="flex-shrink:0;display:grid;place-items:center;width:22px;height:22px;border-radius:50%;background:#dc2626;color:#ffffff;font-size:13px;font-weight:900;">!</span><span style="font-size:14.5px;line-height:1.5;"><b>${T('Payment failed.', 'Ödeme başarısız.')}</b> ${T('Please check your card details and try again.', 'Lütfen kart bilgilerinizi kontrol edip yeniden deneyin.')}</span></div>`),
  variant('neutral', copy('Neutral', 'Nötr'), (T) => `<div style="${FONT}padding:14px 16px;border-radius:12px;background:#f8fafc;border:1px solid #e2e8f0;color:#334155;font-size:14.5px;line-height:1.5;">${T('Prices shown include VAT and free delivery.', 'Gösterilen fiyatlara KDV ve ücretsiz teslimat dahildir.')}</div>`),
  variant('with-action', copy('With action', 'Eylem düğmeli'), (T) => `<div style="${FONT}display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:12px;padding:14px 16px;border-radius:12px;background:#eef2ff;color:#312e81;"><span style="font-size:14.5px;">${T('Your trial ends in 3 days.', 'Deneme süreniz 3 gün içinde bitiyor.')}</span><a href="#" style="padding:8px 14px;border-radius:9px;background:#4f46e5;color:#ffffff;text-decoration:none;font-weight:700;font-size:14px;">${T('Upgrade', 'Yükseltin')}</a></div>`),
  variant('dismissible', copy('Dismissible', 'Kapatılabilir'), (T) => `<div style="${FONT}display:flex;gap:12px;align-items:flex-start;padding:14px 16px;border-radius:12px;background:#ecfeff;border:1px solid #a5f3fc;color:#155e75;"><span style="flex:1;font-size:14.5px;line-height:1.5;">${T('We have updated our opening hours for the holidays.', 'Tatil dönemi için çalışma saatlerimizi güncelledik.')}</span><a href="#" aria-label="${T('Close', 'Kapat')}" style="color:#155e75;text-decoration:none;font-weight:800;">✕</a></div>`),
  variant('left-accent', copy('Left accent', 'Sol vurgulu'), (T) => `<div style="${FONT}padding:14px 18px;border-left:5px solid #f59e0b;border-radius:4px 12px 12px 4px;background:#fffbeb;color:#78350f;"><b style="display:block;margin-bottom:4px;">${T('Heads up', 'Dikkat')}</b><span style="font-size:14.5px;line-height:1.5;">${T('Some items in your cart are almost sold out.', 'Sepetinizdeki bazı ürünler tükenmek üzere.')}</span></div>`),
  variant('toast-dark', copy('Dark toast', 'Koyu bildirim'), (T) => `<div role="status" style="${FONT}display:flex;align-items:center;gap:12px;padding:12px 14px 12px 16px;border-radius:14px;background:#111827;color:#f9fafb;box-shadow:0 16px 40px rgba(0,0,0,0.3);max-width:420px;"><span aria-hidden="true" style="color:#4ade80;font-weight:900;">✓</span><span style="flex:1;font-size:14.5px;">${T('Message sent', 'Mesaj gönderildi')}</span><a href="#" style="color:#93c5fd;font-weight:700;font-size:14px;text-decoration:none;">${T('Undo', 'Geri al')}</a></div>`),
  variant('update', copy('Update available', 'Güncelleme var'), (T) => `<div style="${FONT}display:flex;gap:12px;align-items:center;padding:14px 16px;border-radius:14px;background:linear-gradient(90deg,#f5f3ff,#fdf2f8);border:1px solid #e9d5ff;color:#4c1d95;"><span aria-hidden="true" style="font-size:20px;">✦</span><span style="flex:1;font-size:14.5px;line-height:1.5;"><b>${T('New:', 'Yeni:')}</b> ${T('dark mode is here. Try it from the settings.', 'koyu mod geldi. Ayarlardan deneyin.')}</span></div>`),
  variant('success-solid', copy('Solid success', 'Dolgun başarı'), (T) => `<div role="status" style="${FONT}display:flex;gap:10px;align-items:center;padding:14px 16px;border-radius:12px;background:#16a34a;color:#ffffff;font-size:14.5px;font-weight:600;"><span aria-hidden="true" style="font-weight:900;">✓</span>${T('Your booking is confirmed for Friday at 19:30.', 'Rezervasyonunuz cuma saat 19.30 için onaylandı.')}</div>`),
  variant('maintenance', copy('Maintenance', 'Bakım'), (T) => `<div style="${FONT}display:flex;gap:12px;align-items:flex-start;padding:14px 16px;border-radius:12px;background:#f1f5f9;border:1px dashed #94a3b8;color:#334155;"><span aria-hidden="true" style="font-size:18px;">⚙</span><span style="font-size:14.5px;line-height:1.5;">${T('Scheduled maintenance on Sunday from 02:00 to 04:00.', 'Pazar günü 02.00–04.00 arasında planlı bakım yapılacak.')}</span></div>`),
  variant('cookie-mini', copy('Cookie notice', 'Çerez bildirimi'), (T) => `<div style="${FONT}display:flex;flex-wrap:wrap;align-items:center;gap:12px;padding:14px 16px;border-radius:14px;background:#ffffff;border:1px solid #e2e8f0;box-shadow:0 10px 30px rgba(15,23,42,0.1);color:#334155;max-width:520px;"><span style="flex:1 1 240px;font-size:14px;line-height:1.5;">🍪 ${T('We use cookies to improve your visit.', 'Ziyaretinizi iyileştirmek için çerez kullanıyoruz.')}</span><a href="#" style="padding:8px 14px;border-radius:9px;background:#0f172a;color:#ffffff;text-decoration:none;font-weight:700;font-size:14px;">${T('OK', 'Tamam')}</a></div>`),
]

const zone = (style, title, text) => `<div style="${FONT}min-height:100%;padding:26px;${style}"><b style="display:block;margin-bottom:6px;font-size:17px;">${title}</b><span style="font-size:14.5px;line-height:1.6;opacity:0.85;">${text}</span></div>`

export const CONTAINERS = [
  variant('soft-gradient', copy('Soft gradient', 'Yumuşak degrade'), (T) => zone('border-radius:20px;background:linear-gradient(135deg,#eef2ff,#fdf2f8);color:#312e81;', T('Soft gradient panel', 'Yumuşak degrade panel'), T('Place text, images or buttons inside.', 'İçine yazı, görsel ya da düğme yerleştirin.'))),
  variant('dark-panel', copy('Dark panel', 'Koyu panel'), (T) => zone('border-radius:18px;background:#0f172a;color:#e2e8f0;', T('Dark panel', 'Koyu panel'), T('Good for highlighting one message.', 'Tek bir mesajı öne çıkarmak için ideal.'))),
  variant('accent-border', copy('Accent border', 'Vurgulu çerçeve'), (T) => zone('border-radius:16px;border:2px solid #4f46e5;background:#ffffff;color:#1e1b4b;', T('Highlighted box', 'Vurgulu kutu'), T('Draws the eye without shouting.', 'Bağırmadan göz alır.'))),
  variant('dot-grid', copy('Dot grid', 'Noktalı ızgara'), (T) => zone('border-radius:16px;border:1px solid #e2e8f0;background-color:#ffffff;background-image:radial-gradient(#cbd5e1 1.2px,transparent 1.2px);background-size:18px 18px;color:#0f172a;', T('Dot grid canvas', 'Noktalı ızgara zemin'), T('A light texture behind your content.', 'İçeriğinizin arkasında hafif bir doku.'))),
  variant('paper', copy('Paper', 'Kâğıt'), (T) => zone('border-radius:6px;background:#fffdf7;box-shadow:0 1px 2px rgba(0,0,0,0.06),0 12px 28px rgba(120,90,40,0.12);color:#44403c;font-family:Georgia,serif;', T('A note on paper', 'Kâğıt üzerinde bir not'), T('Warm and personal.', 'Sıcak ve kişisel.'))),
  variant('split-tone', copy('Split tone', 'İki tonlu'), (T) => zone('border-radius:18px;background:linear-gradient(90deg,#fef3c7 0 50%,#ffedd5 50% 100%);color:#7c2d12;', T('Two-tone background', 'İki tonlu zemin'), T('Split your content into two halves.', 'İçeriğinizi iki yarıya bölün.'))),
  variant('floating', copy('Floating card', 'Yüzen kart'), (T) => zone('border-radius:22px;background:#ffffff;box-shadow:0 30px 60px rgba(15,23,42,0.14);color:#0f172a;', T('Floating card', 'Yüzen kart'), T('A deep, soft shadow lifts it off the page.', 'Derin ve yumuşak bir gölge onu sayfadan kaldırır.'))),
  variant('accent-dashed', copy('Dashed accent', 'Kesik vurgulu'), (T) => zone('border-radius:16px;border:2px dashed #14b8a6;background:#f0fdfa;color:#115e59;text-align:center;', T('Drop content here', 'İçeriği buraya bırakın'), T('Anything you drop inside stays together.', 'İçine bıraktığınız her şey birlikte kalır.'))),
]

const details = (question, answer, style, summaryStyle, open = false) => `<details${open ? ' open' : ''} style="${style}"><summary style="cursor:pointer;list-style:none;display:flex;justify-content:space-between;gap:12px;font-weight:700;${summaryStyle}">${question}<span aria-hidden="true">+</span></summary><p style="margin:10px 0 0;line-height:1.6;opacity:0.85;">${answer}</p></details>`

const QA = (T) => [
  [T('How long does delivery take?', 'Teslimat ne kadar sürer?'), T('Two working days within the country.', 'Yurt içinde iki iş günü.')],
  [T('Can I return an item?', 'Ürünü iade edebilir miyim?'), T('Yes, free of charge within 30 days.', 'Evet, 30 gün içinde ücretsiz.')],
  [T('Do you ship abroad?', 'Yurt dışına gönderim var mı?'), T('We ship to 30 countries.', '30 ülkeye gönderim yapıyoruz.')],
]

export const ACCORDIONS = [
  variant('plus-lines', copy('Plus and lines', 'Artı ve çizgiler'), (T) => `<div style="${FONT}max-width:680px;border-top:1px solid #e2e8f0;color:#0f172a;">${QA(T).map(([q, ans], i) => details(q, ans, 'padding:16px 2px;border-bottom:1px solid #e2e8f0;', 'font-size:16.5px;', i === 0)).join('')}</div>`),
  variant('numbered', copy('Numbered', 'Numaralı'), (T) => `<div style="${FONT}max-width:680px;display:grid;gap:10px;color:#0f172a;">${QA(T).map(([q, ans], i) => details(`<span><span style="color:#4f46e5;margin-right:10px;">0${i + 1}</span>${q}</span>`, ans, 'padding:14px 18px;border-radius:12px;background:#f8fafc;', '', i === 0)).join('')}</div>`),
  variant('cards', copy('Card stack', 'Kart yığını'), (T) => `<div style="${FONT}max-width:680px;display:grid;gap:12px;color:#0f172a;">${QA(T).map(([q, ans], i) => details(q, ans, 'padding:16px 18px;border-radius:16px;background:#ffffff;box-shadow:0 8px 24px rgba(15,23,42,0.08);', '', i === 0)).join('')}</div>`),
  variant('violet', copy('Soft violet', 'Yumuşak mor'), (T) => `<div style="${FONT}max-width:680px;padding:10px 18px;border-radius:18px;background:#f5f3ff;color:#2e1065;">${QA(T).map(([q, ans], i) => details(q, ans, `padding:14px 0;${i ? 'border-top:1px solid #ddd6fe;' : ''}`, '', i === 0)).join('')}</div>`),
  variant('with-icons', copy('With icons', 'Simgeli'), (T) => `<div style="${FONT}max-width:680px;display:grid;gap:10px;color:#0f172a;">${QA(T).map(([q, ans], i) => details(`<span style="display:flex;align-items:center;gap:12px;"><span aria-hidden="true" style="display:grid;place-items:center;width:30px;height:30px;border-radius:9px;background:#ecfdf5;color:#047857;">${['⛟', '⇄', '✈'][i]}</span>${q}</span>`, ans, 'padding:12px 16px;border-radius:14px;border:1px solid #e2e8f0;', '', i === 0)).join('')}</div>`),
  variant('dark-lines', copy('Dark lines', 'Koyu çizgiler'), (T) => `<div style="${FONT}max-width:680px;padding:8px 22px;border-radius:18px;background:#111827;color:#f3f4f6;">${QA(T).map(([q, ans], i) => details(q, ans, `padding:16px 0;${i ? 'border-top:1px solid #374151;' : ''}`, '', i === 0)).join('')}</div>`),
]

const FIELD = 'display:block;width:100%;padding:12px 14px;font-size:15px;font-family:inherit;box-sizing:border-box;'
const labelText = (text, color = '#1e293b') => `<span style="display:block;margin-bottom:6px;font-size:14px;font-weight:600;color:${color};">${text}</span>`

export const INPUTS = [
  variant('underline', copy('Underlined', 'Alt çizgili'), (T) => `<label style="${FONT}display:block;width:100%;max-width:420px;">${labelText(T('Your name', 'Adınız'))}<input type="text" name="name" placeholder="${T('Jane Doe', 'Ayşe Yılmaz')}" style="${FIELD}padding:10px 2px;border:0;border-bottom:2px solid #cbd5e1;background:transparent;border-radius:0;" /></label>`),
  variant('filled', copy('Filled', 'Dolgulu'), (T) => `<label style="${FONT}display:block;width:100%;max-width:420px;">${labelText(T('Company', 'Şirket'))}<input type="text" name="company" placeholder="${T('Acme Ltd.', 'Örnek Ltd.')}" style="${FIELD}border:0;border-radius:12px;background:#f1f5f9;color:#0f172a;" /></label>`),
  variant('dark', copy('Dark', 'Koyu'), (T) => `<label style="${FONT}display:block;width:100%;max-width:420px;padding:16px;border-radius:14px;background:#0f172a;">${labelText(T('Email', 'E-posta'), '#e2e8f0')}<input type="email" name="email" placeholder="you@example.com" style="${FIELD}border:1px solid #334155;border-radius:10px;background:#1e293b;color:#f8fafc;" /></label>`),
  variant('phone', copy('Phone number', 'Telefon numarası'), (T) => `<label style="${FONT}display:block;width:100%;max-width:420px;">${labelText(T('Phone', 'Telefon'))}<span style="display:flex;border:1px solid #cbd5e1;border-radius:10px;overflow:hidden;"><span style="display:grid;place-items:center;padding:0 12px;background:#f8fafc;color:#475569;font-weight:600;border-right:1px solid #cbd5e1;">+90</span><input type="tel" name="phone" placeholder="5xx xxx xx xx" style="${FIELD}border:0;border-radius:0;" /></span></label>`),
  variant('date', copy('Date', 'Tarih'), (T) => `<label style="${FONT}display:block;width:100%;max-width:280px;">${labelText(T('Arrival date', 'Varış tarihi'))}<input type="date" name="date" style="${FIELD}border:1px solid #cbd5e1;border-radius:10px;color:#0f172a;" /></label>`),
  variant('password', copy('Password', 'Parola'), (T) => `<label style="${FONT}display:block;width:100%;max-width:420px;">${labelText(T('Password', 'Parola'))}<span style="display:flex;align-items:center;border:1px solid #cbd5e1;border-radius:10px;padding-right:12px;"><input type="password" name="password" placeholder="••••••••" style="${FIELD}border:0;background:transparent;" /><span style="font-size:13.5px;font-weight:700;color:#4f46e5;">${T('Show', 'Göster')}</span></span></label>`),
  variant('quantity', copy('Quantity stepper', 'Adet seçici'), (T) => `<label style="${FONT}display:inline-flex;align-items:center;gap:12px;"><span style="font-size:14px;font-weight:600;color:#1e293b;">${T('Quantity', 'Adet')}</span><span style="display:inline-flex;align-items:center;border:1px solid #cbd5e1;border-radius:999px;overflow:hidden;"><span aria-hidden="true" style="padding:8px 14px;font-weight:800;color:#334155;">−</span><input type="number" name="quantity" value="1" min="1" aria-label="${T('Quantity', 'Adet')}" style="width:48px;padding:8px 0;border:0;text-align:center;font-size:15px;font-family:inherit;" /><span aria-hidden="true" style="padding:8px 14px;font-weight:800;color:#334155;">+</span></span></label>`),
  variant('url', copy('Web address', 'Web adresi'), (T) => `<label style="${FONT}display:block;width:100%;max-width:420px;">${labelText(T('Website', 'Web sitesi'))}<span style="display:flex;border:1px solid #cbd5e1;border-radius:10px;overflow:hidden;"><span style="display:grid;place-items:center;padding:0 10px;background:#f8fafc;color:#64748b;font-size:14px;border-right:1px solid #cbd5e1;">https://</span><input type="text" name="website" placeholder="example.com" style="${FIELD}border:0;border-radius:0;" /></span></label>`),
  variant('search-large', copy('Large search', 'Büyük arama'), (T) => `<label style="${FONT}display:flex;align-items:center;gap:10px;width:100%;max-width:560px;padding:6px 6px 6px 18px;border-radius:16px;background:#ffffff;border:1px solid #e2e8f0;box-shadow:0 10px 30px rgba(15,23,42,0.08);"><span aria-hidden="true" style="color:#94a3b8;font-size:18px;">⌕</span><input type="search" name="q" placeholder="${T('Search recipes, ingredients…', 'Tarif, malzeme arayın…')}" aria-label="${T('Search', 'Ara')}" style="flex:1;min-width:0;padding:10px 0;border:0;outline:0;font-size:16px;font-family:inherit;" /><span style="padding:10px 18px;border-radius:12px;background:#0f172a;color:#ffffff;font-weight:700;font-size:14.5px;">${T('Search', 'Ara')}</span></label>`),
  variant('message', copy('Message box', 'Mesaj kutusu'), (T) => `<label style="${FONT}display:block;width:100%;max-width:480px;">${labelText(T('Message', 'Mesaj'))}<textarea name="message" rows="4" placeholder="${T('How can we help?', 'Nasıl yardımcı olabiliriz?')}" style="${FIELD}border:1px solid #cbd5e1;border-radius:12px;background:#f8fafc;resize:vertical;"></textarea><span style="display:block;margin-top:6px;text-align:right;font-size:12.5px;color:#94a3b8;">0 / 500</span></label>`),
]

const SELECT = 'display:block;width:100%;padding:11px 14px;font-size:15px;font-family:inherit;box-sizing:border-box;'

export const SELECTS = [
  variant('pill', copy('Pill', 'Hap'), (T) => `<select name="sort" aria-label="${T('Sort by', 'Sırala')}" style="${FONT}${SELECT}max-width:240px;border:1px solid #cbd5e1;border-radius:999px;background:#ffffff;color:#0f172a;"><option>${T('Most popular', 'En popüler')}</option><option>${T('Newest', 'En yeni')}</option><option>${T('Price: low to high', 'Fiyat: artan')}</option></select>`),
  variant('dark', copy('Dark', 'Koyu'), (T) => `<label style="${FONT}display:block;max-width:320px;padding:14px;border-radius:14px;background:#0f172a;color:#e2e8f0;font-size:14px;font-weight:600;">${T('Room type', 'Oda tipi')}<select name="room" style="${SELECT}margin-top:6px;border:1px solid #334155;border-radius:10px;background:#1e293b;color:#f8fafc;"><option>${T('Single', 'Tek kişilik')}</option><option>${T('Double', 'Çift kişilik')}</option><option>${T('Suite', 'Süit')}</option></select></label>`),
  variant('underline', copy('Underlined', 'Alt çizgili'), (T) => `<label style="${FONT}display:block;max-width:320px;font-size:14px;font-weight:600;color:#1e293b;">${T('Guests', 'Misafir')}<select name="guests" style="${SELECT}margin-top:4px;padding:10px 2px;border:0;border-bottom:2px solid #cbd5e1;border-radius:0;background:transparent;color:#0f172a;"><option>${T('2 adults', '2 yetişkin')}</option><option>${T('2 adults, 1 child', '2 yetişkin, 1 çocuk')}</option><option>${T('Family of 4', '4 kişilik aile')}</option></select></label>`),
  variant('with-icon', copy('With icon', 'Simgeli'), (T) => `<label style="${FONT}display:flex;align-items:center;gap:10px;max-width:320px;padding:4px 4px 4px 14px;border:1px solid #cbd5e1;border-radius:12px;background:#ffffff;"><span aria-hidden="true" style="color:#64748b;">◷</span><select name="time" aria-label="${T('Time', 'Saat')}" style="${SELECT}flex:1;border:0;background:transparent;color:#0f172a;padding:9px 6px;"><option>18:00</option><option>19:30</option><option>21:00</option></select></label>`),
  variant('sort-inline', copy('Sort inline', 'Satır içi sıralama'), (T) => `<label style="${FONT}display:inline-flex;align-items:center;gap:10px;font-size:14.5px;color:#475569;">${T('Sort by', 'Sırala')}<select name="sort" style="padding:8px 12px;border:1px solid #e2e8f0;border-radius:9px;background:#f8fafc;color:#0f172a;font-size:14.5px;font-weight:600;font-family:inherit;"><option>${T('Relevance', 'İlgi')}</option><option>${T('Price', 'Fiyat')}</option><option>${T('Rating', 'Puan')}</option></select></label>`),
  variant('language', copy('Language picker', 'Dil seçici'), (T) => `<label style="${FONT}display:inline-flex;align-items:center;gap:8px;padding:6px 6px 6px 12px;border:1px solid #e2e8f0;border-radius:999px;font-size:14px;color:#334155;"><span aria-hidden="true">🌐</span><select name="language" aria-label="${T('Language', 'Dil')}" style="border:0;background:transparent;color:#0f172a;font-size:14px;font-weight:600;font-family:inherit;padding:4px;"><option>English</option><option>Türkçe</option><option>Deutsch</option><option>Español</option></select></label>`),
]
