// Small interactive pieces: buttons, link buttons, badges and icons.
import { a, copy, glyph, pill, variant } from './kit.js'

export const BUTTONS = [
  variant('brutalist', copy('Brutalist', 'Brütalist'), (T) => a('padding:12px 26px;background:#fde047;color:#111111;border:2px solid #111111;border-radius:0;box-shadow:4px 4px 0 #111111;', T('Get started', 'Hemen başlayın'))),
  variant('arrow-dark-pill', copy('Dark pill with arrow', 'Oklu koyu hap'), (T) => a('padding:12px 16px 12px 24px;background:#0f172a;color:#ffffff;border-radius:999px;', `${T('Next step', 'Sonraki adım')} <span aria-hidden="true" style="display:inline-grid;place-items:center;width:26px;height:26px;border-radius:50%;background:#ffffff;color:#0f172a;">→</span>`)),
  variant('emerald', copy('Emerald', 'Zümrüt'), (T) => a('padding:12px 26px;background:#059669;color:#ffffff;border-radius:10px;', T('Book now', 'Rezervasyon yapın'))),
  variant('coral', copy('Coral', 'Mercan'), (T) => a('padding:12px 26px;background:#e11d48;color:#ffffff;border-radius:12px;', T('Shop the sale', 'İndirimi keşfedin'))),
  variant('amber-outline', copy('Amber outline', 'Kehribar çerçeve'), (T) => a('padding:11px 25px;background:#fffbeb;color:#92400e;border:1.5px solid #f59e0b;border-radius:10px;', T('Learn more', 'Daha fazla bilgi'))),
  variant('violet-soft', copy('Soft violet', 'Yumuşak mor'), (T) => a('padding:12px 24px;background:#ede9fe;color:#5b21b6;border-radius:12px;', T('Try it free', 'Ücretsiz deneyin'))),
  variant('sky-gradient', copy('Sky gradient', 'Gök degrade'), (T) => a('padding:12px 28px;background:linear-gradient(135deg,#38bdf8,#2563eb);color:#ffffff;border-radius:12px;box-shadow:0 10px 24px rgba(37,99,235,0.35);', T('Start now', 'Şimdi başlayın'))),
  variant('gold-luxe', copy('Gold on black', 'Siyah üzerine altın'), (T) => a('padding:13px 30px;background:#1c1917;color:#fcd34d;border:1px solid #a16207;border-radius:2px;letter-spacing:0.14em;text-transform:uppercase;font-size:13.5px;', T('Reserve', 'Rezerve edin'))),
  variant('serif-classic', copy('Classic serif', 'Klasik serif'), (T) => a('padding:12px 28px;background:#ffffff;color:#1f2937;border:1px solid #1f2937;border-radius:0;font-family:Georgia,serif;font-weight:400;font-size:16.5px;', T('Reserve a table', 'Masa ayırtın'))),
  variant('mint-pill', copy('Mint pill', 'Nane hap'), (T) => a('padding:12px 28px;background:#ccfbf1;color:#115e59;border-radius:999px;', T('Join us', 'Bize katılın'))),
  variant('lifted', copy('Lifted white', 'Yüzen beyaz'), (T) => a('padding:13px 28px;background:#ffffff;color:#4338ca;border-radius:14px;box-shadow:0 14px 34px rgba(67,56,202,0.28);', T('See pricing', 'Fiyatları görün'))),
  variant('double-border', copy('Double border', 'Çift çerçeve'), (T) => a('padding:10px 26px;background:transparent;color:#0f172a;border:4px double #0f172a;border-radius:10px;', T('Contact us', 'Bize ulaşın'))),
  variant('wide-caps', copy('Wide capitals', 'Geniş büyük harf'), (T) => a('padding:14px 34px;background:#111827;color:#ffffff;border-radius:0;letter-spacing:0.2em;text-transform:uppercase;font-size:12.5px;', T('Explore', 'Keşfedin'))),
  variant('download', copy('Download', 'İndirme'), (T) => a('padding:12px 24px;background:#1d4ed8;color:#ffffff;border-radius:10px;', `<span aria-hidden="true">↓</span> ${T('Download PDF', 'PDF indirin')}`)),
  variant('chat', copy('Chat', 'Sohbet'), (T) => a('padding:12px 24px;background:#16a34a;color:#ffffff;border-radius:999px;', `<span aria-hidden="true">✆</span> ${T('Message us', 'Bize yazın')}`)),
  variant('call', copy('Call now', 'Hemen arayın'), (T) => a('padding:12px 24px;background:#ffffff;color:#b91c1c;border:2px solid #b91c1c;border-radius:12px;', `<span aria-hidden="true">☎\uFE0E</span> ${T('Call now', 'Hemen arayın')}`)),
  variant('add-to-cart', copy('Add to cart', 'Sepete ekle'), (T) => a('padding:13px 26px;background:#0f172a;color:#ffffff;border-radius:12px;', `<span aria-hidden="true">+</span> ${T('Add to cart', 'Sepete ekleyin')}`)),
  variant('save', copy('Save with heart', 'Kalpli kaydet'), (T) => a('padding:11px 20px;background:#fff1f2;color:#be123c;border:1px solid #fecdd3;border-radius:999px;', `<span aria-hidden="true">♥</span> ${T('Save', 'Kaydedin')}`)),
  variant('compact', copy('Compact', 'Kompakt'), (T) => a('padding:7px 14px;background:#4f46e5;color:#ffffff;border-radius:8px;font-size:13.5px;', T('Apply', 'Uygula'))),
  variant('extra-large', copy('Extra large', 'Çok büyük'), (T) => a('padding:20px 44px;background:#4f46e5;color:#ffffff;border-radius:16px;font-size:20px;box-shadow:0 18px 40px rgba(79,70,229,0.35);', T('Get started free', 'Ücretsiz başlayın'))),
  variant('glass-dark', copy('Dark glass', 'Koyu cam'), (T) => a('padding:12px 26px;background:rgba(15,23,42,0.55);color:#ffffff;border:1px solid rgba(255,255,255,0.25);border-radius:12px;backdrop-filter:blur(10px);', T('Watch the film', 'Filmi izleyin'))),
  variant('retro', copy('Retro', 'Retro'), (T) => a('padding:12px 26px;background:#fb923c;color:#431407;border-radius:10px;box-shadow:0 5px 0 #9a3412;', T('Play now', 'Hemen oynayın'))),
  variant('soft-shadow', copy('Soft shadow', 'Yumuşak gölge'), (T) => a('padding:13px 28px;background:#e8edf3;color:#334155;border-radius:14px;box-shadow:6px 6px 14px #c3cad4,-6px -6px 14px #ffffff;', T('Continue', 'Devam edin'))),
  variant('dashed', copy('Dashed', 'Kesik çizgili'), (T) => a('padding:11px 24px;background:#f8fafc;color:#334155;border:1.5px dashed #94a3b8;border-radius:10px;', `<span aria-hidden="true">+</span> ${T('Add item', 'Öğe ekleyin')}`)),
  variant('split-arrow', copy('Split arrow', 'Bölünmüş ok'), (T) => a('padding:0;background:#2563eb;color:#ffffff;border-radius:10px;overflow:hidden;gap:0;', `<span style="padding:12px 20px;">${T('Learn more', 'Daha fazla bilgi')}</span><span aria-hidden="true" style="align-self:stretch;display:grid;place-items:center;padding:0 16px;background:#1e40af;">→</span>`)),
  variant('ticket', copy('Tickets', 'Bilet'), (T) => a('padding:12px 26px;background:#7c3aed;color:#ffffff;border-radius:10px;', `<span aria-hidden="true">🎟</span> ${T('Get tickets', 'Bilet alın')}`)),
]

export const LINK_BUTTONS = [
  variant('chevron', copy('Chevron link', 'Köşeli ok bağlantısı'), (T) => a('padding:4px 0;color:#2563eb;font-size:15.5px;gap:4px;', `${T('View all', 'Tümünü görün')} <span aria-hidden="true">›</span>`)),
  variant('arrow-circle', copy('Arrow in a circle', 'Daire içinde ok'), (T) => a('padding:4px 0;color:#0f172a;gap:10px;', `${T('Read the story', 'Hikâyeyi okuyun')} <span aria-hidden="true" style="display:inline-grid;place-items:center;width:30px;height:30px;border-radius:50%;background:#0f172a;color:#ffffff;">→</span>`)),
  variant('external', copy('External link', 'Dış bağlantı'), (T) => a('padding:4px 0;color:#7c3aed;gap:6px;', `${T('Visit website', 'Web sitesine gidin')} <span aria-hidden="true">↗</span>`)),
  variant('back', copy('Back link', 'Geri bağlantısı'), (T) => a('padding:4px 0;color:#475569;font-weight:600;gap:6px;', `<span aria-hidden="true">←</span> ${T('Back', 'Geri')}`)),
  variant('thick-underline', copy('Thick underline', 'Kalın alt çizgi'), (T) => a('padding:2px 0;color:#0f172a;text-decoration:underline;text-decoration-color:#f59e0b;text-decoration-thickness:4px;text-underline-offset:6px;', T('Our story', 'Hikâyemiz'))),
  variant('muted-small', copy('Small muted link', 'Küçük soluk bağlantı'), (T) => a('padding:2px 0;color:#64748b;font-weight:600;font-size:13.5px;text-decoration:underline;text-underline-offset:3px;', T('Terms and conditions', 'Şartlar ve koşullar'))),
  variant('marker', copy('Marker highlight', 'Fosforlu vurgu'), (T) => a('padding:2px 6px;color:#0f172a;background:linear-gradient(transparent 55%,#fde68a 55%);', T('See how it works', 'Nasıl çalıştığını görün'))),
  variant('caps-small', copy('Small capitals link', 'Küçük büyük harf bağlantısı'), (T) => a('padding:4px 0;color:#be123c;font-size:12.5px;letter-spacing:0.16em;text-transform:uppercase;gap:8px;', `${T('Discover', 'Keşfedin')} <span aria-hidden="true">→</span>`)),
  variant('download-link', copy('Download link', 'İndirme bağlantısı'), (T) => a('padding:4px 0;color:#15803d;gap:8px;', `<span aria-hidden="true">↓</span> ${T('Download brochure', 'Broşürü indirin')}`)),
  variant('email', copy('Email link', 'E-posta bağlantısı'), () => a('padding:4px 0;color:#0f172a;font-weight:600;gap:8px;', '<span aria-hidden="true">✉</span> hello@example.com')),
]

export const BADGES = [
  variant('new-gradient', copy('New', 'Yeni'), (T) => pill('padding:5px 12px;border-radius:999px;background:linear-gradient(90deg,#6366f1,#ec4899);color:#ffffff;', T('New', 'Yeni'))),
  variant('sale', copy('Sale', 'İndirim'), () => pill('padding:5px 10px;border-radius:8px;background:#dc2626;color:#ffffff;', '−20%')),
  variant('live', copy('Live', 'Canlı'), (T) => pill('padding:5px 12px;border-radius:999px;background:#fef2f2;color:#b91c1c;border:1px solid #fecaca;', `<span aria-hidden="true" style="width:8px;height:8px;border-radius:50%;background:#ef4444;box-shadow:0 0 0 3px rgba(239,68,68,0.2);"></span>${T('Live', 'Canlı')}`)),
  variant('beta', copy('Beta', 'Beta'), () => pill('padding:4px 11px;border-radius:999px;border:1.5px solid #7c3aed;color:#6d28d9;letter-spacing:0.08em;text-transform:uppercase;font-size:11.5px;', 'Beta')),
  variant('verified', copy('Verified', 'Doğrulanmış'), (T) => pill('padding:5px 12px;border-radius:999px;background:#eff6ff;color:#1d4ed8;', `<span aria-hidden="true" style="display:inline-grid;place-items:center;width:15px;height:15px;border-radius:50%;background:#2563eb;color:#ffffff;font-size:10px;">✓</span>${T('Verified', 'Doğrulanmış')}`)),
  variant('pro', copy('Pro', 'Pro'), () => pill('padding:4px 10px;border-radius:6px;background:#111827;color:#fcd34d;letter-spacing:0.1em;font-size:11.5px;', 'PRO')),
  variant('popular', copy('Popular', 'Popüler'), (T) => pill('padding:5px 12px;border-radius:999px;background:#fff7ed;color:#c2410c;', `<span aria-hidden="true">★</span>${T('Popular', 'Popüler')}`)),
  variant('online', copy('Online status', 'Çevrimiçi durumu'), (T) => pill('padding:5px 12px;border-radius:999px;background:#f0fdf4;color:#15803d;', `<span aria-hidden="true" style="width:8px;height:8px;border-radius:50%;background:#22c55e;"></span>${T('Online', 'Çevrimiçi')}`)),
  variant('away', copy('Away status', 'Uzakta durumu'), (T) => pill('padding:5px 12px;border-radius:999px;background:#fffbeb;color:#b45309;', `<span aria-hidden="true" style="width:8px;height:8px;border-radius:50%;background:#f59e0b;"></span>${T('Away', 'Uzakta')}`)),
  variant('version', copy('Version', 'Sürüm'), () => pill('padding:4px 9px;border-radius:6px;background:#f1f5f9;color:#334155;border:1px solid #e2e8f0;font-family:ui-monospace,Menlo,monospace;font-weight:600;', 'v2.4.0')),
  variant('rating', copy('Rating', 'Puan'), () => pill('padding:5px 11px;border-radius:999px;background:#fefce8;color:#854d0e;', '<span aria-hidden="true" style="color:#eab308;">★</span>4.9')),
  variant('hashtag', copy('Topic tag', 'Konu etiketi'), (T) => pill('padding:5px 12px;border-radius:8px;background:#f5f3ff;color:#6d28d9;font-weight:600;', `#${T('design', 'tasarım')}`)),
  variant('teal-soft', copy('Soft teal', 'Yumuşak camgöbeği'), (T) => pill('padding:5px 12px;border-radius:999px;background:#ccfbf1;color:#115e59;', T('In stock', 'Stokta'))),
  variant('ribbon', copy('Corner ribbon', 'Köşe şeridi'), (T) => pill('padding:6px 14px;border-radius:0 10px 0 10px;background:#0f766e;color:#ffffff;letter-spacing:0.1em;text-transform:uppercase;font-size:11.5px;', T('Best value', 'En avantajlı'))),
  variant('price', copy('Price tag', 'Fiyat etiketi'), () => pill('padding:6px 12px;border-radius:10px;background:#111827;color:#ffffff;font-size:15px;', '€29')),
  variant('limited', copy('Limited', 'Sınırlı'), (T) => pill('padding:4px 11px;border-radius:999px;border:1px dashed #be185d;color:#be185d;', T('Limited edition', 'Sınırlı sayıda'))),
  variant('eco', copy('Eco', 'Doğa dostu'), (T) => pill('padding:5px 12px;border-radius:999px;background:#ecfccb;color:#3f6212;', `<span aria-hidden="true">✿</span>${T('Eco friendly', 'Doğa dostu')}`)),
]

export const ICONS = [
  variant('star-amber', copy('Amber star', 'Kehribar yıldız'), () => glyph('border-radius:999px;background:#fef3c7;color:#d97706;', '★')),
  variant('heart-rose', copy('Rose heart', 'Gül kalp'), () => glyph('border-radius:28%;background:#ffe4e6;color:#e11d48;', '♥\uFE0E')),
  variant('check-green', copy('Green check', 'Yeşil onay'), () => glyph('border-radius:999px;background:#16a34a;color:#ffffff;', '✓')),
  variant('phone-sky', copy('Phone', 'Telefon'), () => glyph('border-radius:22%;background:#e0f2fe;color:#0369a1;', '☎\uFE0E')),
  variant('mail-violet', copy('Mail', 'Posta'), () => glyph('border-radius:22%;background:#ede9fe;color:#6d28d9;', '✉\uFE0E')),
  variant('bolt-dark', copy('Lightning, dark', 'Şimşek, koyu'), () => glyph('border-radius:999px;background:#0f172a;color:#facc15;', 'ϟ')),
  variant('sun-sunset', copy('Sun gradient', 'Güneş degrade'), () => glyph('border-radius:30%;background:linear-gradient(135deg,#f97316,#ec4899);color:#ffffff;', '☀\uFE0E')),
  variant('moon-night', copy('Moon', 'Ay'), () => glyph('border-radius:999px;background:linear-gradient(160deg,#1e1b4b,#4338ca);color:#e0e7ff;', '☾')),
  variant('home-outline', copy('Home outline', 'Ev, çerçeveli'), () => glyph('border-radius:24%;border:2px solid #0f766e;color:#0f766e;', '⌂')),
  variant('target-ring', copy('Target', 'Hedef'), () => glyph('border-radius:999px;background:#ffffff;color:#dc2626;box-shadow:inset 0 0 0 3px #fecaca;', '◎')),
  variant('sparkle-indigo', copy('Sparkle', 'Parıltı'), () => glyph('border-radius:26%;background:#eef2ff;color:#4f46e5;', '✦')),
  variant('note-teal', copy('Music note', 'Nota'), () => glyph('border-radius:999px;background:#ccfbf1;color:#0f766e;', '♪')),
  variant('flag-plain', copy('Flag', 'Bayrak'), () => glyph('border-radius:20%;background:#f1f5f9;color:#334155;', '⚑')),
  variant('flower-lime', copy('Flower', 'Çiçek'), () => glyph('border-radius:40% 12%;background:#ecfccb;color:#4d7c0f;', '✿')),
]
