// Words and pictures: headings, text, quotes, lists, images and dividers.
import { FONT, copy, photo, variant } from './kit.js'

export const HEADINGS = [
  variant('serif-italic', copy('Serif italic', 'İtalik serif'), (T) => `<h2 style="${FONT}margin:0;font-family:Georgia,'Times New Roman',serif;font-style:italic;font-weight:400;font-size:clamp(32px,5vw,48px);line-height:1.1;color:#1c1917;">${T('The art of slow mornings', 'Yavaş sabahların sanatı')}</h2>`),
  variant('accent-underline', copy('Accent underline', 'Vurgulu alt çizgi'), (T) => `<div style="${FONT}"><h2 style="margin:0 0 14px;font-size:36px;font-weight:800;line-height:1.15;color:#0f172a;">${T('What we do best', 'En iyi yaptığımız işler')}</h2><span aria-hidden="true" style="display:block;width:64px;height:5px;border-radius:99px;background:#4f46e5;"></span></div>`),
  variant('marker', copy('Marker highlight', 'Fosforlu vurgu'), (T) => `<h2 style="${FONT}margin:0;font-size:40px;font-weight:800;line-height:1.2;color:#0f172a;">${T('Simple tools for', 'Yoğun ekipler için')} <span style="background:linear-gradient(transparent 58%,#fde047 58%);padding:0 4px;">${T('busy teams', 'basit araçlar')}</span></h2>`),
  variant('outline-text', copy('Outline letters', 'Çerçeve harfler'), (T) => `<h1 style="${FONT}margin:0;font-size:clamp(44px,8vw,80px);font-weight:900;line-height:1;letter-spacing:-0.03em;color:transparent;-webkit-text-stroke:2px #0f172a;">${T('Studio', 'Stüdyo')}</h1>`),
  variant('two-tone', copy('Two-tone', 'İki renkli'), (T) => `<h2 style="${FONT}margin:0;font-size:44px;font-weight:800;line-height:1.1;letter-spacing:-0.02em;color:#0f172a;">${T('Made by hand,', 'El yapımı,')} <span style="color:#94a3b8;">${T('built to last.', 'uzun ömürlü.')}</span></h2>`),
  variant('kicker-subline', copy('Kicker and subline', 'Üst başlık ve alt satır'), (T) => `<div style="${FONT}text-align:center;"><p style="margin:0 0 10px;font-size:13px;font-weight:800;letter-spacing:0.16em;text-transform:uppercase;color:#0d9488;">${T('Our services', 'Hizmetlerimiz')}</p><h2 style="margin:0 0 10px;font-size:38px;font-weight:800;line-height:1.15;color:#0f172a;">${T('Everything your garden needs', 'Bahçenizin ihtiyacı olan her şey')}</h2><p style="margin:0;font-size:17px;line-height:1.6;color:#64748b;">${T('Design, planting and care, all year round.', 'Tasarım, dikim ve bakım, bütün yıl boyunca.')}</p></div>`),
  variant('numbered', copy('Numbered', 'Numaralı'), (T) => `<div style="${FONT}display:flex;align-items:baseline;gap:16px;"><span style="font-size:48px;font-weight:900;line-height:1;color:#e11d48;">01</span><h2 style="margin:0;font-size:32px;font-weight:800;line-height:1.2;color:#0f172a;">${T('Tell us what you need', 'Neye ihtiyacınız olduğunu anlatın')}</h2></div>`),
  variant('tracked-caps', copy('Tracked capitals', 'Aralıklı büyük harf'), (T) => `<h2 style="${FONT}margin:0;font-size:22px;font-weight:700;letter-spacing:0.3em;text-transform:uppercase;color:#1f2937;">${T('Collection', 'Koleksiyon')}</h2>`),
  variant('with-badge', copy('Title with badge', 'Rozetli başlık'), (T) => `<div style="${FONT}"><span style="display:inline-block;margin-bottom:12px;padding:5px 12px;border-radius:999px;background:#ecfdf5;color:#047857;font-size:13px;font-weight:700;">${T('New this month', 'Bu ay yeni')}</span><h2 style="margin:0;font-size:36px;font-weight:800;line-height:1.15;color:#0f172a;">${T('Meet the spring menu', 'Bahar menüsüyle tanışın')}</h2></div>`),
  variant('left-bar', copy('Left bar', 'Sol çizgili'), (T) => `<h2 style="${FONT}margin:0;padding:4px 0 4px 18px;border-left:5px solid #f97316;font-size:30px;font-weight:800;line-height:1.2;color:#1c1917;">${T('Opening hours', 'Çalışma saatleri')}</h2>`),
  variant('dark-band', copy('Dark band', 'Koyu bant'), (T) => `<h2 style="${FONT}margin:0;padding:18px 26px;border-radius:14px;background:#0f172a;color:#f8fafc;font-size:28px;font-weight:800;line-height:1.2;">${T('Frequently asked questions', 'Sıkça sorulan sorular')}</h2>`),
  variant('center-lines', copy('Between lines', 'Çizgiler arasında'), (T) => `<div style="${FONT}display:flex;align-items:center;gap:18px;"><span aria-hidden="true" style="flex:1;height:1px;background:#cbd5e1;"></span><h2 style="margin:0;font-size:26px;font-weight:700;color:#334155;white-space:nowrap;">${T('Our partners', 'Ortaklarımız')}</h2><span aria-hidden="true" style="flex:1;height:1px;background:#cbd5e1;"></span></div>`),
  variant('mono', copy('Monospace', 'Eş aralıklı'), (T) => `<h2 style="${FONT}margin:0;font-family:ui-monospace,Menlo,Consolas,monospace;font-size:34px;font-weight:700;line-height:1.2;color:#0f172a;">&gt; ${T('hello, world', 'merhaba, dünya')}<span style="color:#22c55e;">_</span></h2>`),
  variant('warm-gradient', copy('Warm gradient text', 'Sıcak degrade yazı'), (T) => `<h1 style="${FONT}margin:0;font-size:52px;font-weight:900;line-height:1.05;letter-spacing:-0.03em;background:linear-gradient(90deg,#f97316,#db2777);-webkit-background-clip:text;background-clip:text;color:transparent;">${T('Summer is here', 'Yaz geldi')}</h1>`),
]

export const TEXTS = [
  variant('two-columns', copy('Two columns', 'İki sütun'), (T) => `<p style="${FONT}margin:0;columns:2 220px;column-gap:32px;font-size:16px;line-height:1.7;color:#334155;">${T('We started with a single oven and a simple idea: bake bread the slow way, with flour from farms we can visit. Twenty years later we still do, and the queue on Saturday mornings tells us it was worth it. Every loaf is shaped by hand and baked before sunrise.', 'Tek bir fırın ve basit bir fikirle başladık: ekmeği, ziyaret edebildiğimiz çiftliklerden gelen unla, yavaş yoldan pişirmek. Yirmi yıl sonra hâlâ böyle yapıyoruz ve cumartesi sabahlarındaki kuyruk buna değdiğini söylüyor. Her somun elle şekillendirilir ve gün doğmadan pişirilir.')}</p>`),
  variant('drop-cap', copy('Drop cap', 'Büyük ilk harf'), (T) => {
    const text = T('Once a week we close the shop early and cook for the whole street. It started as a thank-you and turned into a tradition.', 'Haftada bir dükkânı erken kapatıp bütün sokak için yemek yapıyoruz. Bir teşekkür olarak başladı, bir geleneğe dönüştü.')
    return `<p style="${FONT}margin:0;font-size:17px;line-height:1.7;color:#334155;"><span style="float:left;margin:4px 10px 0 0;font-family:Georgia,serif;font-size:58px;line-height:0.85;font-weight:700;color:#b45309;">${text[0]}</span>${text.slice(1)}</p>`
  }),
  variant('callout-note', copy('Callout note', 'Not kutusu'), (T) => `<p style="${FONT}margin:0;padding:16px 18px;border-radius:12px;background:#fefce8;border:1px solid #fde68a;font-size:15.5px;line-height:1.6;color:#713f12;"><strong>${T('Note:', 'Not:')}</strong> ${T('Orders placed after 2 pm ship the next working day.', 'Saat 14.00’ten sonra verilen siparişler bir sonraki iş günü kargolanır.')}</p>`),
  variant('serif-lead', copy('Serif lead', 'Serif giriş'), (T) => `<p style="${FONT}margin:0;font-family:Georgia,serif;font-size:24px;line-height:1.55;color:#1f2937;">${T('A small guest house on the edge of the old town, with seven rooms, a garden and breakfast that lasts until noon.', 'Eski şehrin kıyısında yedi odalı, bahçeli ve öğlene kadar süren kahvaltısıyla küçük bir pansiyon.')}</p>`),
  variant('caption', copy('Caption', 'Görsel açıklaması'), (T) => `<p style="${FONT}margin:0;padding-top:10px;border-top:1px solid #e2e8f0;font-size:13.5px;font-style:italic;line-height:1.5;color:#64748b;">${T('The workshop in winter, photographed by one of our apprentices.', 'Kışın atölye; çıraklarımızdan birinin objektifinden.')}</p>`),
  variant('highlight', copy('With highlight', 'Vurgulu'), (T) => `<p style="${FONT}margin:0;font-size:18px;line-height:1.7;color:#334155;">${T('Delivery is', 'Teslimat')} <mark style="background:#dcfce7;color:#14532d;padding:1px 5px;border-radius:4px;">${T('free on every order over €50', '€50 üzeri her siparişte ücretsiz')}</mark>${T(', and returns are always free.', '; iadeler ise her zaman ücretsiz.')}</p>`),
  variant('signature', copy('Signed note', 'İmzalı not'), (T) => `<div style="${FONT}max-width:520px;"><p style="margin:0 0 14px;font-size:17px;line-height:1.7;color:#334155;">${T('Thank you for being here. Every order is packed by one of the six of us, and we read every message you send.', 'Burada olduğunuz için teşekkürler. Her sipariş altı kişilik ekibimizden biri tarafından paketlenir ve gönderdiğiniz her mesajı okuruz.')}</p><p style="margin:0;font-family:'Brush Script MT','Segoe Script',cursive;font-size:30px;color:#0f172a;">Elif</p></div>`),
  variant('fine-print', copy('Fine print', 'Küçük yazı'), (T) => `<p style="${FONT}margin:0;font-size:12px;line-height:1.6;color:#94a3b8;">${T('Prices include VAT. Offer valid while stocks last and cannot be combined with other discounts.', 'Fiyatlara KDV dahildir. Kampanya stoklarla sınırlıdır ve diğer indirimlerle birleştirilemez.')}</p>`),
  variant('address', copy('Address block', 'Adres bloğu'), (T) => `<address style="${FONT}margin:0;font-style:normal;font-size:16px;line-height:1.7;color:#334155;"><strong style="color:#0f172a;">${T('Olive Tree Studio', 'Zeytin Ağacı Stüdyo')}</strong><br />${T('Moda Street 21', 'Moda Caddesi 21')}<br />${T('Kadıköy, Istanbul', 'Kadıköy, İstanbul')}<br /><a href="#" style="color:#2563eb;">hello@example.com</a></address>`),
  variant('stat-sentence', copy('Big number sentence', 'Büyük rakamlı cümle'), (T) => `<p style="${FONT}margin:0;font-size:20px;line-height:1.5;color:#334155;"><strong style="display:block;font-size:48px;line-height:1;letter-spacing:-0.03em;color:#4f46e5;">12,000+</strong>${T('small businesses run their website with us.', 'küçük işletme web sitesini bizimle yönetiyor.')}</p>`),
]

export const QUOTES = [
  variant('serif-center', copy('Centred serif', 'Ortalanmış serif'), (T) => `<figure style="${FONT}margin:0;text-align:center;"><blockquote style="margin:0 0 14px;font-family:Georgia,serif;font-size:26px;line-height:1.45;color:#1c1917;">“${T('The best meal we had on the whole trip.', 'Bütün yolculuktaki en iyi yemeğimizdi.')}”</blockquote><figcaption style="font-size:14px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#78716c;">— ${T('Travel weekly', 'Seyahat Haftalık')}</figcaption></figure>`),
  variant('with-avatar', copy('Quote with avatar', 'Avatarlı alıntı'), (T) => `<figure style="${FONT}margin:0;"><blockquote style="margin:0 0 16px;font-size:19px;line-height:1.6;color:#0f172a;">“${T('We launched in a weekend and had our first booking on Monday morning.', 'Bir hafta sonunda yayına çıktık, ilk rezervasyonumuzu pazartesi sabahı aldık.')}”</blockquote><figcaption style="display:flex;align-items:center;gap:12px;"><span aria-hidden="true" style="display:grid;place-items:center;width:44px;height:44px;border-radius:50%;background:#4f46e5;color:#ffffff;font-weight:800;">S</span><span><strong style="display:block;color:#0f172a;">Selin Kaya</strong><span style="font-size:14px;color:#64748b;">${T('Yoga teacher', 'Yoga eğitmeni')}</span></span></figcaption></figure>`),
  variant('dark-card', copy('Dark quote card', 'Koyu alıntı kartı'), (T) => `<figure style="${FONT}margin:0;padding:28px;border-radius:18px;background:#0f172a;color:#e2e8f0;"><span aria-hidden="true" style="display:block;font-family:Georgia,serif;font-size:56px;line-height:0.6;color:#818cf8;margin-bottom:14px;">“</span><blockquote style="margin:0 0 16px;font-size:18px;line-height:1.6;color:#f8fafc;">${T('Fast, friendly and the result looks better than we imagined.', 'Hızlı, güler yüzlü ve sonuç hayal ettiğimizden daha iyi.')}</blockquote><figcaption style="font-size:14px;color:#94a3b8;">— Mark Jensen</figcaption></figure>`),
  variant('social-post', copy('Social post', 'Sosyal medya gönderisi'), (T) => `<figure style="${FONT}margin:0;padding:18px 20px;border-radius:16px;background:#ffffff;border:1px solid #e2e8f0;"><figcaption style="display:flex;align-items:center;gap:10px;margin-bottom:12px;"><span aria-hidden="true" style="display:grid;place-items:center;width:40px;height:40px;border-radius:50%;background:#f97316;color:#ffffff;font-weight:800;">A</span><span><strong style="display:block;color:#0f172a;font-size:15px;">Ada Lin</strong><span style="font-size:13.5px;color:#64748b;">@adalin</span></span></figcaption><blockquote style="margin:0 0 10px;font-size:15.5px;line-height:1.6;color:#0f172a;">${T('Found my new favourite coffee place. The cardamom bun alone is worth the trip.', 'Yeni favori kahve mekânımı buldum. Sadece kakuleli çörek için bile gitmeye değer.')}</blockquote><span style="font-size:13px;color:#94a3b8;">♥ 248 · ${T('2 days ago', '2 gün önce')}</span></figure>`),
  variant('big-mark', copy('Big quote mark', 'Büyük tırnak'), (T) => `<blockquote style="${FONT}position:relative;margin:0;padding:34px 0 0 0;font-size:22px;font-weight:600;line-height:1.5;color:#0f172a;"><span aria-hidden="true" style="position:absolute;top:-6px;left:-4px;font-family:Georgia,serif;font-size:90px;line-height:1;color:#fde68a;">“</span><span style="position:relative;">${T('Good design is as little design as possible.', 'İyi tasarım, olabildiğince az tasarımdır.')}</span></blockquote>`),
  variant('top-border', copy('Top border', 'Üst çizgili'), (T) => `<blockquote style="${FONT}margin:0;padding-top:18px;border-top:3px solid #0d9488;font-size:19px;line-height:1.6;color:#134e4a;">${T('“They treated our old house like it was their own.”', '“Eski evimize kendi evleri gibi davrandılar.”')}<footer style="margin-top:10px;font-size:14px;font-weight:700;color:#0f766e;">— ${T('The Yıldız family', 'Yıldız ailesi')}</footer></blockquote>`),
  variant('rated', copy('Quote with stars', 'Yıldızlı alıntı'), (T) => `<figure style="${FONT}margin:0;padding:22px;border-radius:16px;background:#fffbeb;"><div aria-label="5/5" style="margin-bottom:10px;color:#f59e0b;letter-spacing:2px;">★★★★★</div><blockquote style="margin:0 0 12px;font-size:17px;line-height:1.6;color:#422006;">“${T('Arrived a day early and fits perfectly.', 'Bir gün erken geldi ve tam oldu.')}”</blockquote><figcaption style="font-size:14px;font-weight:700;color:#92400e;">Zeynep · ${T('Verified buyer', 'Doğrulanmış alıcı')}</figcaption></figure>`),
  variant('gradient-bar', copy('Gradient bar', 'Degrade çizgili'), (T) => `<blockquote style="${FONT}margin:0;padding:6px 0 6px 22px;border-left:5px solid;border-image:linear-gradient(#8b5cf6,#ec4899) 1;font-size:21px;font-style:italic;line-height:1.5;color:#1e1b4b;">${T('Design is not just what it looks like. It is how it works.', 'Tasarım yalnızca nasıl göründüğü değil, nasıl çalıştığıdır.')}</blockquote>`),
]

const li = (content, extra = '') => `<li style="display:flex;gap:12px;align-items:flex-start;${extra}">${content}</li>`

export const LISTS = [
  variant('icon-features', copy('Icon features', 'Simgeli özellikler'), (T) => `<ul style="${FONT}margin:0;padding:0;list-style:none;display:grid;gap:16px;">${[['⚡', T('Fast setup', 'Hızlı kurulum'), T('Live in ten minutes.', 'On dakikada yayında.')], ['🔒', T('Private by default', 'Varsayılan olarak gizli'), T('Your data stays yours.', 'Verileriniz sizde kalır.')], ['💬', T('Real support', 'Gerçek destek'), T('People, not bots.', 'Botlar değil, insanlar.')]].map(([mark, title, text]) => li(`<span aria-hidden="true" style="display:grid;place-items:center;flex-shrink:0;width:40px;height:40px;border-radius:12px;background:#eef2ff;">${mark}</span><span><strong style="display:block;color:#0f172a;">${title}</strong><span style="color:#64748b;font-size:15px;">${text}</span></span>`)).join('')}</ul>`),
  variant('steps', copy('Numbered steps', 'Numaralı adımlar'), (T) => `<ol style="${FONT}margin:0;padding:0;list-style:none;display:grid;gap:14px;">${[T('Choose a template', 'Bir şablon seçin'), T('Add your words and photos', 'Yazılarınızı ve fotoğraflarınızı ekleyin'), T('Publish with one click', 'Tek tıkla yayınlayın')].map((text, i) => li(`<span style="display:grid;place-items:center;flex-shrink:0;width:30px;height:30px;border-radius:50%;background:#0f172a;color:#ffffff;font-weight:800;font-size:14px;">${i + 1}</span><span style="padding-top:4px;color:#0f172a;font-size:16px;">${text}</span>`)).join('')}</ol>`),
  variant('two-column-check', copy('Two-column checklist', 'İki sütunlu kontrol listesi'), (T) => `<ul style="${FONT}margin:0;padding:0;list-style:none;display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px 24px;">${[T('Free delivery', 'Ücretsiz teslimat'), T('30-day returns', '30 gün iade'), T('Secure payment', 'Güvenli ödeme'), T('Gift wrapping', 'Hediye paketi'), T('Live chat', 'Canlı destek'), T('Loyalty points', 'Sadakat puanı')].map((text) => li(`<span aria-hidden="true" style="color:#16a34a;font-weight:900;">✓</span><span style="color:#1e293b;">${text}</span>`)).join('')}</ul>`),
  variant('pros-cons', copy('Pros and cons', 'Artılar ve eksiler'), (T) => `<div style="${FONT}display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;"><div style="padding:16px;border-radius:14px;background:#f0fdf4;"><strong style="display:block;margin-bottom:8px;color:#166534;">${T('Pros', 'Artılar')}</strong>${[T('Light and quiet', 'Hafif ve sessiz'), T('Two-year warranty', 'İki yıl garanti')].map((text) => `<div style="color:#14532d;line-height:1.8;">✓ ${text}</div>`).join('')}</div><div style="padding:16px;border-radius:14px;background:#fef2f2;"><strong style="display:block;margin-bottom:8px;color:#991b1b;">${T('Cons', 'Eksiler')}</strong>${[T('No carry case', 'Taşıma çantası yok'), T('Slow to charge', 'Yavaş şarj oluyor')].map((text) => `<div style="color:#7f1d1d;line-height:1.8;">✗ ${text}</div>`).join('')}</div></div>`),
  variant('definitions', copy('Definition list', 'Tanım listesi'), (T) => `<dl style="${FONT}margin:0;display:grid;grid-template-columns:auto 1fr;gap:10px 22px;font-size:15.5px;">${[[T('Size', 'Boyut'), '120 × 80 cm'], [T('Material', 'Malzeme'), T('Solid oak', 'Masif meşe')], [T('Weight', 'Ağırlık'), '18 kg'], [T('Delivery', 'Teslimat'), T('2–4 days', '2–4 gün')]].map(([term, value]) => `<dt style="font-weight:700;color:#0f172a;">${term}</dt><dd style="margin:0;color:#475569;">${value}</dd>`).join('')}</dl>`),
  variant('timeline', copy('Mini timeline', 'Mini zaman çizelgesi'), (T) => `<ol style="${FONT}margin:0;padding:0 0 0 22px;list-style:none;border-left:2px solid #e2e8f0;display:grid;gap:16px;">${[['2019', T('Founded', 'Kuruluş')], ['2022', T('Second studio', 'İkinci stüdyo')], ['2025', T('1,000 clients', '1.000 müşteri')]].map(([year, text]) => `<li style="position:relative;"><span aria-hidden="true" style="position:absolute;left:-30px;top:4px;width:14px;height:14px;border-radius:50%;background:#4f46e5;border:3px solid #ffffff;"></span><strong style="color:#4f46e5;">${year}</strong> <span style="color:#0f172a;">${text}</span></li>`).join('')}</ol>`),
  variant('arrows', copy('Arrow bullets', 'Oklu maddeler'), (T) => `<ul style="${FONT}margin:0;padding:0;list-style:none;display:grid;gap:8px;font-size:16px;">${[T('Plan the week in minutes', 'Haftayı dakikalar içinde planlayın'), T('Share it with the team', 'Ekiple paylaşın'), T('Get reminders on your phone', 'Telefonunuza hatırlatma alın')].map((text) => li(`<span aria-hidden="true" style="color:#ea580c;font-weight:800;">→</span><span style="color:#1f2937;">${text}</span>`)).join('')}</ul>`),
  variant('tags', copy('Tag list', 'Etiket listesi'), (T) => `<ul style="${FONT}margin:0;padding:0;list-style:none;display:flex;flex-wrap:wrap;gap:8px;">${[T('Branding', 'Marka'), T('Web design', 'Web tasarımı'), T('Photography', 'Fotoğraf'), T('Packaging', 'Ambalaj'), T('Print', 'Basılı')].map((text) => `<li style="padding:6px 14px;border-radius:999px;background:#f1f5f9;color:#334155;font-size:14px;font-weight:600;">${text}</li>`).join('')}</ul>`),
  variant('price-list', copy('Price list', 'Fiyat listesi'), (T) => `<ul style="${FONT}margin:0;padding:0;list-style:none;display:grid;gap:10px;font-size:16px;">${[[T('Espresso', 'Espresso'), '€2.5'], [T('Flat white', 'Flat white'), '€3.5'], [T('Cardamom bun', 'Kakuleli çörek'), '€3']].map(([item, price]) => `<li style="display:flex;align-items:baseline;gap:8px;"><span style="color:#0f172a;font-weight:600;">${item}</span><span aria-hidden="true" style="flex:1;border-bottom:1px dotted #cbd5e1;"></span><span style="color:#b45309;font-weight:700;">${price}</span></li>`).join('')}</ul>`),
  variant('link-rows', copy('Link rows', 'Bağlantı satırları'), (T) => `<ul style="${FONT}margin:0;padding:0;list-style:none;border-top:1px solid #e2e8f0;">${[T('Shipping and returns', 'Kargo ve iade'), T('Size guide', 'Beden rehberi'), T('Care instructions', 'Bakım talimatları')].map((text) => `<li style="border-bottom:1px solid #e2e8f0;"><a href="#" style="display:flex;justify-content:space-between;padding:14px 2px;color:#0f172a;text-decoration:none;font-weight:600;">${text}<span aria-hidden="true" style="color:#94a3b8;">→</span></a></li>`).join('')}</ul>`),
]

export const IMAGES = [
  variant('polaroid', copy('Polaroid', 'Polaroid'), (T) => `<figure style="${FONT}margin:10px;padding:12px 12px 16px;background:#ffffff;box-shadow:0 12px 30px rgba(15,23,42,0.16);transform:rotate(-2deg);">${photo('polaroid-summer', 600, 520)}<figcaption style="margin-top:12px;text-align:center;font-family:'Segoe Print','Bradley Hand',cursive;font-size:17px;color:#334155;">${T('Summer 2025', 'Yaz 2025')}</figcaption></figure>`),
  variant('extra-round', copy('Extra rounded', 'Çok yuvarlak'), () => photo('rounded-hills', 800, 520, 'border-radius:32px;')),
  variant('blob', copy('Blob shape', 'Organik şekil'), () => photo('blob-portrait', 600, 600, 'border-radius:42% 58% 63% 37% / 41% 44% 56% 59%;')),
  variant('tilted-shadow', copy('Tilted with shadow', 'Eğik ve gölgeli'), () => photo('tilted-desk', 800, 560, 'width:calc(100% - 28px);margin:14px;border-radius:16px;transform:rotate(2deg);box-shadow:0 18px 36px rgba(15,23,42,0.22);')),
  variant('caption-overlay', copy('Caption overlay', 'Üzerinde açıklama'), (T) => `<figure style="${FONT}position:relative;margin:0;border-radius:18px;overflow:hidden;">${photo('overlay-harbour', 800, 520)}<figcaption style="position:absolute;left:0;right:0;bottom:0;padding:28px 18px 14px;background:linear-gradient(transparent,rgba(0,0,0,0.75));color:#ffffff;font-weight:700;">${T('The harbour at dawn', 'Şafakta liman')}</figcaption></figure>`),
  variant('arch', copy('Arch', 'Kemer'), () => photo('arch-garden', 500, 640, 'border-radius:999px 999px 18px 18px;')),
  variant('grayscale', copy('Black and white', 'Siyah beyaz'), () => photo('mono-street', 800, 520, 'border-radius:12px;filter:grayscale(1) contrast(1.1);')),
  variant('offset-frame', copy('Offset frame', 'Kaydırılmış çerçeve'), () => photo('offset-studio', 700, 520, 'border-radius:14px;box-shadow:14px 14px 0 #fde68a;')),
  variant('panorama', copy('Panorama', 'Panorama'), () => photo('panorama-coast', 1400, 600, 'border-radius:16px;')),
  variant('gradient-ring', copy('Gradient ring avatar', 'Degrade halkalı avatar'), () => `<span style="display:inline-block;padding:4px;border-radius:50%;background:linear-gradient(135deg,#f59e0b,#ec4899,#8b5cf6);">${photo('ring-person', 240, 240, 'width:120px;height:120px;border-radius:50%;border:3px solid #ffffff;')}</span>`),
]

export const DIVIDERS = [
  variant('gradient', copy('Gradient line', 'Degrade çizgi'), () => '<hr style="margin:28px 0;border:0;height:3px;border-radius:99px;background:linear-gradient(90deg,#6366f1,#ec4899,#f59e0b);" />'),
  variant('short-bar', copy('Short centred bar', 'Kısa orta çizgi'), () => '<hr style="width:64px;margin:28px auto;border:0;height:4px;border-radius:99px;background:#0f172a;" />'),
  variant('or-text', copy('“Or” divider', '“Ya da” ayracı'), (T) => `<div style="${FONT}display:flex;align-items:center;gap:14px;margin:24px 0;color:#94a3b8;font-size:13px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;"><span aria-hidden="true" style="flex:1;height:1px;background:#e2e8f0;"></span>${T('or', 'ya da')}<span aria-hidden="true" style="flex:1;height:1px;background:#e2e8f0;"></span></div>`),
  variant('sparkles', copy('Sparkles', 'Parıltılar'), () => '<div aria-hidden="true" style="margin:24px 0;text-align:center;color:#c4b5fd;letter-spacing:18px;font-size:18px;">✦✦✦</div>'),
  variant('wave', copy('Wave', 'Dalga'), () => '<svg aria-hidden="true" viewBox="0 0 1200 40" preserveAspectRatio="none" style="display:block;width:100%;height:40px;margin:18px 0;"><path d="M0 20 Q 75 0 150 20 T 300 20 T 450 20 T 600 20 T 750 20 T 900 20 T 1050 20 T 1200 20" fill="none" stroke="#38bdf8" stroke-width="3"/></svg>'),
  variant('zigzag', copy('Zigzag', 'Zikzak'), () => '<svg aria-hidden="true" viewBox="0 0 1200 24" preserveAspectRatio="none" style="display:block;width:100%;height:24px;margin:20px 0;"><path d="M0 18 L 30 6 L 60 18 L 90 6 L 120 18 L 150 6 L 180 18 L 210 6 L 240 18 L 270 6 L 300 18 L 330 6 L 360 18 L 390 6 L 420 18 L 450 6 L 480 18 L 510 6 L 540 18 L 570 6 L 600 18 L 630 6 L 660 18 L 690 6 L 720 18 L 750 6 L 780 18 L 810 6 L 840 18 L 870 6 L 900 18 L 930 6 L 960 18 L 990 6 L 1020 18 L 1050 6 L 1080 18 L 1110 6 L 1140 18 L 1170 6 L 1200 18" fill="none" stroke="#f97316" stroke-width="2.5"/></svg>'),
  variant('double', copy('Double line', 'Çift çizgi'), () => '<hr style="margin:28px 0;border:0;border-top:4px double #cbd5e1;" />'),
  variant('dots-row', copy('Dot row', 'Nokta dizisi'), () => '<div aria-hidden="true" style="display:flex;justify-content:center;gap:10px;margin:26px 0;"><span style="width:7px;height:7px;border-radius:50%;background:#cbd5e1;"></span><span style="width:7px;height:7px;border-radius:50%;background:#94a3b8;"></span><span style="width:7px;height:7px;border-radius:50%;background:#cbd5e1;"></span></div>'),
  variant('fade', copy('Fading line', 'Solan çizgi'), () => '<hr style="margin:28px 0;border:0;height:1px;background:linear-gradient(90deg,transparent,#94a3b8,transparent);" />'),
  variant('label-left', copy('Label and line', 'Etiket ve çizgi'), (T) => `<div style="${FONT}display:flex;align-items:center;gap:14px;margin:24px 0;"><span style="font-size:13px;font-weight:800;letter-spacing:0.14em;text-transform:uppercase;color:#4f46e5;white-space:nowrap;">${T('Chapter two', 'İkinci bölüm')}</span><span aria-hidden="true" style="flex:1;height:1px;background:#c7d2fe;"></span></div>`),
]
