// Widgets: small ready-made pieces that are more than one component but less
// than a page section — a rating summary, a countdown, a breadcrumb trail, a
// toggle. They drop as editable HTML like any other snippet.
import { FONT, copy, photo, variant } from './kit.js'

const box = (style, inner) => `<div style="${FONT}color:#0f172a;${style}">${inner}</div>`
const muted = (text, extra = '') => `<span style="color:#64748b;font-size:13.5px;${extra}">${text}</span>`
const stars = (count = 5, colour = '#f59e0b') => `<span aria-label="${count}/5" style="color:${colour};letter-spacing:2px;">${'★'.repeat(count)}${'☆'.repeat(5 - count)}</span>`
const circle = (letter, colour, size = 40, extra = '') => `<span aria-hidden="true" style="display:inline-grid;place-items:center;flex-shrink:0;width:${size}px;height:${size}px;border-radius:50%;background:${colour};color:#ffffff;font-weight:800;font-size:${Math.round(size * 0.4)}px;${extra}">${letter}</span>`

const RATING = [
  variant('rating-summary', copy('Rating summary', 'Puan özeti'), (T) => box('display:flex;align-items:center;gap:16px;padding:18px 20px;border-radius:16px;background:#ffffff;border:1px solid #e2e8f0;max-width:340px;', `<b style="font-size:44px;line-height:1;letter-spacing:-0.03em;">4.9</b><div>${stars()}<br />${muted(T('from 1,284 reviews', '1.284 değerlendirmeden'))}</div>`)),
  variant('rating-bars', copy('Rating bars', 'Puan çubukları'), (T) => box('max-width:360px;', `${[[5, 84], [4, 11], [3, 3], [2, 1], [1, 1]].map(([n, pct]) => `<div style="display:flex;align-items:center;gap:10px;margin-bottom:7px;font-size:13.5px;color:#475569;"><span style="width:26px;">${n} ★</span><div style="flex:1;height:8px;border-radius:99px;background:#f1f5f9;overflow:hidden;"><div style="width:${pct}%;height:100%;background:#f59e0b;"></div></div><span style="width:34px;text-align:right;">${pct}%</span></div>`).join('')}${muted(T('Based on 1,284 reviews', '1.284 değerlendirmeye göre'))}`)),
  variant('trust-badge', copy('Trust badge', 'Güven rozeti'), (T) => box('display:inline-flex;align-items:center;gap:12px;padding:12px 16px;border-radius:14px;background:#f0fdf4;border:1px solid #bbf7d0;', `<span aria-hidden="true" style="display:grid;place-items:center;width:38px;height:38px;border-radius:10px;background:#16a34a;color:#ffffff;font-weight:900;">✓</span><span><b style="display:block;color:#14532d;">${T('Rated excellent', 'Mükemmel puanlı')}</b>${stars(5, '#16a34a')} ${muted('4.8 / 5')}</span>`)),
  variant('review-snippet', copy('Review snippet', 'Yorum kesiti'), (T) => box('max-width:380px;padding:18px;border-radius:16px;background:#fffbeb;', `<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px;"><span style="display:flex;align-items:center;gap:10px;">${circle('E', '#d97706', 34)}<b>Ece</b></span>${stars()}</div><p style="margin:0;line-height:1.6;color:#422006;">“${T('The best brunch in the neighbourhood, hands down.', 'Mahallenin açık ara en iyi brunch’ı.')}”</p>`)),
  variant('thumbs', copy('Was this helpful?', 'Faydalı oldu mu?'), (T) => box('display:inline-flex;flex-wrap:wrap;align-items:center;gap:12px;padding:12px 16px;border-radius:14px;border:1px solid #e2e8f0;background:#ffffff;', `<span style="font-weight:600;">${T('Was this page helpful?', 'Bu sayfa faydalı oldu mu?')}</span><a href="#" style="padding:6px 14px;border-radius:999px;background:#f1f5f9;color:#0f172a;text-decoration:none;font-weight:700;">👍 ${T('Yes', 'Evet')}</a><a href="#" style="padding:6px 14px;border-radius:999px;background:#f1f5f9;color:#0f172a;text-decoration:none;font-weight:700;">👎 ${T('No', 'Hayır')}</a>`)),
]

const PROGRESS = [
  variant('progress-bar', copy('Progress bar', 'İlerleme çubuğu'), (T) => box('max-width:420px;', `<div style="display:flex;justify-content:space-between;margin-bottom:8px;font-size:14.5px;"><b>${T('Profile complete', 'Profil tamamlandı')}</b><span style="color:#4f46e5;font-weight:700;">72%</span></div><div style="height:10px;border-radius:99px;background:#e0e7ff;overflow:hidden;"><div style="width:72%;height:100%;border-radius:99px;background:linear-gradient(90deg,#6366f1,#8b5cf6);"></div></div>`)),
  variant('stepper', copy('Stepper', 'Adım göstergesi'), (T) => box('display:flex;align-items:center;max-width:520px;', [T('Cart', 'Sepet'), T('Delivery', 'Teslimat'), T('Payment', 'Ödeme')].map((label, i) => `${i ? `<span aria-hidden="true" style="flex:1;height:2px;margin:0 8px;background:${i <= 1 ? '#4f46e5' : '#e2e8f0'};"></span>` : ''}<span style="display:flex;align-items:center;gap:8px;white-space:nowrap;"><span style="display:grid;place-items:center;width:28px;height:28px;border-radius:50%;font-weight:800;font-size:13px;${i < 1 ? 'background:#4f46e5;color:#ffffff;' : i === 1 ? 'border:2px solid #4f46e5;color:#4f46e5;' : 'border:2px solid #e2e8f0;color:#94a3b8;'}">${i < 1 ? '✓' : i + 1}</span><span style="font-size:14px;font-weight:600;color:${i <= 1 ? '#0f172a' : '#94a3b8'};">${label}</span></span>`).join(''))),
  variant('ring', copy('Progress ring', 'İlerleme halkası'), (T) => box('display:inline-flex;align-items:center;gap:16px;', `<span style="display:grid;place-items:center;width:96px;height:96px;border-radius:50%;background:conic-gradient(#0d9488 0 68%,#ccfbf1 68% 100%);"><span style="display:grid;place-items:center;width:74px;height:74px;border-radius:50%;background:#ffffff;font-weight:800;font-size:20px;">68%</span></span><span><b style="display:block;font-size:17px;">${T('Weekly goal', 'Haftalık hedef')}</b>${muted(T('17 of 25 hours', '25 saatin 17’si'))}</span>`)),
  variant('skills', copy('Skill bars', 'Yetenek çubukları'), (T) => box('max-width:400px;display:grid;gap:12px;', [[T('Branding', 'Marka'), 90], [T('Web design', 'Web tasarımı'), 80], [T('Illustration', 'İllüstrasyon'), 65]].map(([label, pct]) => `<div><div style="display:flex;justify-content:space-between;margin-bottom:5px;font-size:14px;font-weight:600;"><span>${label}</span><span style="color:#64748b;">${pct}%</span></div><div style="height:6px;border-radius:99px;background:#f1f5f9;"><div style="width:${pct}%;height:100%;border-radius:99px;background:#0f172a;"></div></div></div>`).join(''))),
  variant('fundraiser', copy('Fundraising goal', 'Bağış hedefi'), (T) => box('max-width:380px;padding:20px;border-radius:16px;background:#f0fdf4;', `<div style="display:flex;align-items:baseline;gap:8px;margin-bottom:10px;"><b style="font-size:28px;color:#166534;">€18,420</b>${muted(T('raised of €25,000', '€25.000 hedefin'))}</div><div style="height:12px;border-radius:99px;background:#dcfce7;overflow:hidden;margin-bottom:10px;"><div style="width:74%;height:100%;background:#16a34a;"></div></div><div style="display:flex;justify-content:space-between;font-size:13.5px;color:#166534;"><span>312 ${T('donors', 'bağışçı')}</span><span>${T('9 days left', '9 gün kaldı')}</span></div>`)),
]

const TIME = [
  variant('countdown', copy('Countdown', 'Geri sayım'), (T) => box('display:flex;gap:10px;', [['12', T('days', 'gün')], ['08', T('hours', 'saat')], ['45', T('min', 'dk')], ['20', T('sec', 'sn')]].map(([n, l]) => `<div style="min-width:72px;padding:12px 6px;border-radius:14px;background:#0f172a;color:#ffffff;text-align:center;"><b style="display:block;font-size:28px;font-variant-numeric:tabular-nums;">${n}</b><span style="font-size:12px;color:#94a3b8;">${l}</span></div>`).join(''))),
  variant('hours-card', copy('Opening hours', 'Çalışma saatleri'), (T) => box('max-width:320px;padding:18px 20px;border-radius:16px;background:#ffffff;border:1px solid #e2e8f0;', `<b style="display:block;margin-bottom:10px;">${T('Opening hours', 'Çalışma saatleri')}</b>${[[T('Mon–Fri', 'Pzt–Cum'), '08:00 – 19:00'], [T('Saturday', 'Cumartesi'), '09:00 – 17:00'], [T('Sunday', 'Pazar'), T('Closed', 'Kapalı')]].map(([day, hours]) => `<div style="display:flex;justify-content:space-between;padding:6px 0;font-size:14.5px;border-top:1px solid #f1f5f9;"><span style="color:#475569;">${day}</span><span style="font-weight:600;">${hours}</span></div>`).join('')}`)),
  variant('mini-calendar', copy('Mini calendar', 'Mini takvim'), (T) => {
    const days = Array.from({ length: 30 }, (_, i) => i + 1)
    return box('max-width:300px;padding:16px;border-radius:16px;background:#ffffff;border:1px solid #e2e8f0;', `<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px;"><b>${T('June 2026', 'Haziran 2026')}</b><span style="color:#94a3b8;">‹ ›</span></div><div style="display:grid;grid-template-columns:repeat(7,1fr);gap:4px;text-align:center;font-size:12.5px;">${[T('M', 'P'), T('T', 'S'), T('W', 'Ç'), T('T', 'P'), T('F', 'C'), T('S', 'C'), T('S', 'P')].map((d) => `<span style="color:#94a3b8;font-weight:700;">${d}</span>`).join('')}${days.map((d) => `<span style="padding:6px 0;border-radius:8px;${d === 14 ? 'background:#4f46e5;color:#ffffff;font-weight:800;' : d === 21 || d === 22 ? 'background:#eef2ff;color:#4338ca;font-weight:700;' : ''}">${d}</span>`).join('')}</div>`)
  }),
  variant('open-now', copy('Open now', 'Şu an açık'), (T) => box('display:inline-flex;align-items:center;gap:10px;padding:8px 14px;border-radius:999px;background:#f0fdf4;border:1px solid #bbf7d0;', `<span aria-hidden="true" style="width:9px;height:9px;border-radius:50%;background:#22c55e;box-shadow:0 0 0 4px rgba(34,197,94,0.2);"></span><b style="color:#166534;font-size:14.5px;">${T('Open now', 'Şu an açık')}</b>${muted(T('until 20:00', '20.00’ye kadar'))}`)),
  variant('date-block', copy('Date and time', 'Tarih ve saat'), (T) => box('display:inline-flex;align-items:center;gap:14px;', `<div style="display:grid;place-items:center;width:64px;height:70px;border-radius:14px;background:#fef2f2;color:#b91c1c;line-height:1.05;text-align:center;"><span style="font-size:12px;font-weight:800;text-transform:uppercase;">${T('Sat', 'Cmt')}</span><b style="font-size:26px;">21</b><span style="font-size:12px;font-weight:700;">${T('Jun', 'Haz')}</span></div><div><b style="display:block;">${T('Garden party', 'Bahçe partisi')}</b>${muted('18:00 – 23:00')}</div>`)),
]

const SOCIAL = [
  variant('social-icons', copy('Social icons', 'Sosyal simgeler'), () => box('display:flex;gap:10px;', [['IG', '#e1306c'], ['in', '#0a66c2'], ['▶', '#dc2626'], ['X', '#0f172a'], ['f', '#1d4ed8']].map(([mark, colour]) => `<a href="#" aria-label="${mark}" style="display:grid;place-items:center;width:42px;height:42px;border-radius:50%;background:${colour};color:#ffffff;text-decoration:none;font-weight:800;font-size:15px;">${mark}</a>`).join(''))),
  variant('share', copy('Share buttons', 'Paylaş düğmeleri'), (T) => box('display:flex;flex-wrap:wrap;align-items:center;gap:8px;', `<b style="margin-right:4px;font-size:14.5px;">${T('Share', 'Paylaş')}</b>${['X', 'in', 'f'].map((mark) => `<a href="#" aria-label="${mark}" style="display:grid;place-items:center;width:36px;height:36px;border-radius:10px;border:1px solid #e2e8f0;color:#0f172a;text-decoration:none;font-weight:800;font-size:13px;">${mark}</a>`).join('')}<a href="#" style="padding:8px 14px;border-radius:10px;background:#f1f5f9;color:#0f172a;text-decoration:none;font-weight:700;font-size:13.5px;">🔗 ${T('Copy link', 'Bağlantıyı kopyala')}</a>`)),
  variant('avatar-group', copy('Avatar group', 'Avatar grubu'), (T) => box('display:inline-flex;align-items:center;gap:12px;', `<span style="display:flex;">${[['A', '#6366f1'], ['K', '#ec4899'], ['M', '#f59e0b'], ['S', '#10b981']].map(([l, c], i) => circle(l, c, 40, `margin-left:${i ? -10 : 0}px;border:3px solid #ffffff;`)).join('')}<span style="display:inline-grid;place-items:center;width:40px;height:40px;margin-left:-10px;border-radius:50%;background:#f1f5f9;border:3px solid #ffffff;font-size:12.5px;font-weight:800;color:#475569;">+12</span></span>${muted(T('joined this week', 'bu hafta katıldı'), 'font-weight:600;')}`)),
  variant('follow-count', copy('Follow card', 'Takip kartı'), (T) => box('display:flex;align-items:center;gap:14px;max-width:360px;padding:14px 16px;border-radius:16px;border:1px solid #e2e8f0;background:#ffffff;', `${circle('S', 'linear-gradient(135deg,#f97316,#db2777)', 48)}<div style="flex:1;"><b style="display:block;">@studio.north</b>${muted(T('12.4K followers', '12,4 B takipçi'))}</div><a href="#" style="padding:8px 16px;border-radius:999px;background:#0f172a;color:#ffffff;text-decoration:none;font-weight:700;font-size:14px;">${T('Follow', 'Takip et')}</a>`)),
  variant('reactions', copy('Like and comment bar', 'Beğeni ve yorum çubuğu'), (T) => box('display:flex;gap:18px;padding:10px 0;border-top:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;font-size:14.5px;font-weight:600;color:#475569;', `<span>♥ 1.2K</span><span>💬 84 ${T('comments', 'yorum')}</span><span>↗ ${T('Share', 'Paylaş')}</span>`)),
]

const NAVIGATION = [
  variant('breadcrumbs', copy('Breadcrumbs', 'İçerik haritası'), (T) => `<nav aria-label="${T('Breadcrumb', 'İçerik haritası')}" style="${FONT}display:flex;flex-wrap:wrap;gap:8px;font-size:14px;color:#64748b;"><a href="#" style="color:#64748b;text-decoration:none;">${T('Home', 'Ana sayfa')}</a><span aria-hidden="true">›</span><a href="#" style="color:#64748b;text-decoration:none;">${T('Shop', 'Mağaza')}</a><span aria-hidden="true">›</span><span aria-current="page" style="color:#0f172a;font-weight:600;">${T('Linen shirt', 'Keten gömlek')}</span></nav>`),
  variant('pagination', copy('Pagination', 'Sayfalama'), (T) => `<nav aria-label="${T('Pages', 'Sayfalar')}" style="${FONT}display:flex;align-items:center;gap:6px;">${['‹', '1', '2', '3', '…', '8', '›'].map((n, i) => (n === '…' ? '<span style="padding:0 6px;color:#94a3b8;">…</span>' : `<a href="#"${i === 2 ? ' aria-current="page"' : ''} style="display:grid;place-items:center;min-width:38px;height:38px;border-radius:10px;text-decoration:none;font-weight:700;font-size:14.5px;${i === 2 ? 'background:#4f46e5;color:#ffffff;' : 'border:1px solid #e2e8f0;color:#0f172a;'}">${n}</a>`)).join('')}</nav>`),
  variant('segmented', copy('Segmented control', 'Bölmeli seçici'), (T) => box('display:inline-flex;padding:4px;border-radius:12px;background:#f1f5f9;', [T('Day', 'Gün'), T('Week', 'Hafta'), T('Month', 'Ay')].map((label, i) => `<a href="#" style="padding:8px 18px;border-radius:9px;text-decoration:none;font-weight:700;font-size:14px;${i === 1 ? 'background:#ffffff;color:#0f172a;box-shadow:0 1px 3px rgba(15,23,42,0.15);' : 'color:#64748b;'}">${label}</a>`).join(''))),
  variant('back-to-top', copy('Back to top', 'Başa dön'), (T) => `<a href="#" style="${FONT}display:inline-flex;align-items:center;gap:8px;padding:10px 16px;border-radius:999px;background:#0f172a;color:#ffffff;text-decoration:none;font-weight:700;font-size:14px;box-shadow:0 10px 24px rgba(15,23,42,0.25);"><span aria-hidden="true">↑</span>${T('Back to top', 'Başa dön')}</a>`),
  variant('table-of-contents', copy('Table of contents', 'İçindekiler'), (T) => `<nav style="${FONT}max-width:300px;padding:18px 20px;border-radius:16px;background:#f8fafc;border:1px solid #e2e8f0;"><b style="display:block;margin-bottom:10px;font-size:14px;letter-spacing:0.08em;text-transform:uppercase;color:#64748b;">${T('On this page', 'Bu sayfada')}</b>${[T('Getting started', 'Başlarken'), T('Adding products', 'Ürün eklemek'), T('Taking payments', 'Ödeme almak'), T('Going live', 'Yayına almak')].map((item, i) => `<a href="#" style="display:block;padding:6px 0 6px 12px;border-left:2px solid ${i === 1 ? '#4f46e5' : '#e2e8f0'};color:${i === 1 ? '#4338ca' : '#334155'};font-weight:${i === 1 ? 700 : 500};text-decoration:none;font-size:14.5px;">${item}</a>`).join('')}</nav>`),
]

const COMMERCE = [
  variant('price-tag', copy('Price with discount', 'İndirimli fiyat'), (T) => box('display:inline-flex;align-items:baseline;gap:10px;', `<b style="font-size:32px;color:#dc2626;">€59</b><s style="color:#94a3b8;font-size:18px;">€79</s><span style="padding:3px 8px;border-radius:6px;background:#fee2e2;color:#b91c1c;font-size:13px;font-weight:800;">−25%</span><span style="font-size:13px;color:#64748b;">${T('incl. VAT', 'KDV dahil')}</span>`)),
  variant('buy-row', copy('Quantity and add to cart', 'Adet ve sepete ekle'), (T) => box('display:flex;flex-wrap:wrap;gap:10px;align-items:center;', `<span style="display:inline-flex;align-items:center;border:1px solid #cbd5e1;border-radius:12px;"><span aria-hidden="true" style="padding:10px 14px;font-weight:800;">−</span><b style="min-width:24px;text-align:center;">1</b><span aria-hidden="true" style="padding:10px 14px;font-weight:800;">+</span></span><a href="#" style="flex:1 1 180px;padding:13px 20px;border-radius:12px;background:#0f172a;color:#ffffff;text-decoration:none;font-weight:700;text-align:center;">${T('Add to cart', 'Sepete ekle')} · €59</a>`)),
  variant('coupon-code', copy('Coupon code', 'Kupon kodu'), (T) => box('display:inline-flex;align-items:center;gap:12px;padding:10px 12px 10px 16px;border-radius:14px;border:2px dashed #7c3aed;background:#faf5ff;', `<span style="font-size:14px;color:#6d28d9;">${T('Code', 'Kod')}</span><code style="font-size:18px;font-weight:800;letter-spacing:0.12em;color:#4c1d95;">SPRING20</code><a href="#" style="padding:6px 12px;border-radius:8px;background:#7c3aed;color:#ffffff;text-decoration:none;font-weight:700;font-size:13.5px;">${T('Copy', 'Kopyala')}</a>`)),
  variant('free-shipping', copy('Free delivery progress', 'Ücretsiz teslimat ilerlemesi'), (T) => box('max-width:400px;padding:14px 16px;border-radius:14px;background:#eff6ff;', `<p style="margin:0 0 8px;font-size:14.5px;color:#1e3a8a;">${T('Add', 'Ücretsiz teslimat için')} <b>€12</b> ${T('more for free delivery', 'daha ekleyin')}</p><div style="height:8px;border-radius:99px;background:#dbeafe;overflow:hidden;"><div style="width:76%;height:100%;background:#2563eb;"></div></div>`)),
  variant('payment-methods', copy('Payment methods', 'Ödeme yöntemleri'), (T) => box('display:flex;flex-wrap:wrap;align-items:center;gap:8px;', `${muted(T('We accept', 'Kabul ettiklerimiz'), 'font-weight:600;margin-right:4px;')}${[T('Card', 'Kart'), T('Bank transfer', 'Havale'), T('Cash on delivery', 'Kapıda ödeme'), T('Gift card', 'Hediye kartı')].map((label) => `<span style="padding:6px 10px;border-radius:8px;border:1px solid #e2e8f0;background:#ffffff;font-size:13px;font-weight:700;color:#334155;">${label}</span>`).join('')}`)),
  variant('stock', copy('Stock indicator', 'Stok göstergesi'), (T) => box('max-width:300px;', `<p style="margin:0 0 6px;font-size:14px;font-weight:700;color:#b45309;">${T('Only 3 left in stock', 'Stokta yalnızca 3 adet kaldı')}</p><div style="height:6px;border-radius:99px;background:#fef3c7;"><div style="width:15%;height:100%;border-radius:99px;background:#f59e0b;"></div></div>`)),
]

const CONTACT = [
  variant('contact-chips', copy('Contact chips', 'İletişim etiketleri'), () => box('display:flex;flex-wrap:wrap;gap:8px;', [['☎', '+90 212 555 01 01'], ['✉', 'hello@example.com']].map(([mark, text]) => `<a href="#" style="display:inline-flex;align-items:center;gap:8px;padding:8px 14px;border-radius:999px;background:#f1f5f9;color:#0f172a;text-decoration:none;font-weight:600;font-size:14px;"><span aria-hidden="true">${mark}</span>${text}</a>`).join(''))),
  variant('address-card', copy('Address card', 'Adres kartı'), (T) => box('max-width:320px;padding:18px 20px;border-radius:16px;background:#ffffff;border:1px solid #e2e8f0;', `<b style="display:block;margin-bottom:8px;">${T('Visit the studio', 'Stüdyoyu ziyaret edin')}</b><p style="margin:0 0 12px;line-height:1.6;color:#475569;font-size:14.5px;">${T('Moda Street 21, Kadıköy, Istanbul', 'Moda Caddesi 21, Kadıköy, İstanbul')}</p><a href="#" style="color:#2563eb;font-weight:700;text-decoration:none;font-size:14.5px;">${T('Get directions →', 'Yol tarifi alın →')}</a>`)),
  variant('chat-bubble', copy('Chat bubble', 'Sohbet balonu'), (T) => box('display:flex;align-items:flex-end;gap:10px;max-width:360px;', `${circle('M', '#0d9488', 38)}<div style="padding:12px 16px;border-radius:18px 18px 18px 4px;background:#f1f5f9;"><b style="display:block;font-size:13.5px;color:#0f766e;margin-bottom:2px;">Mert · ${T('Support', 'Destek')}</b><span style="font-size:14.5px;line-height:1.5;">${T('Hi! How can we help you today?', 'Merhaba! Bugün size nasıl yardımcı olabiliriz?')}</span></div>`)),
  variant('business-card', copy('Business card', 'Kartvizit'), (T) => box('max-width:360px;padding:22px;border-radius:18px;background:linear-gradient(135deg,#0f172a,#1e293b);color:#e2e8f0;', `<b style="display:block;font-size:19px;color:#ffffff;">Elif Aydın</b><span style="font-size:14px;color:#a5b4fc;">${T('Architect', 'Mimar')}</span><div style="margin-top:18px;line-height:1.8;font-size:14px;">✉ elif@example.com<br />☎ +90 532 555 22 11<br />⌂ ${T('Istanbul', 'İstanbul')}</div>`)),
  variant('chat-float', copy('Floating chat button', 'Yüzen sohbet düğmesi'), (T) => `<a href="#" style="${FONT}display:inline-flex;align-items:center;gap:10px;padding:12px 18px 12px 12px;border-radius:999px;background:#16a34a;color:#ffffff;text-decoration:none;font-weight:700;box-shadow:0 12px 28px rgba(22,163,74,0.35);"><span aria-hidden="true" style="display:grid;place-items:center;width:32px;height:32px;border-radius:50%;background:rgba(255,255,255,0.2);">✆</span>${T('Chat with us', 'Bize yazın')}</a>`),
]

const MEDIA = [
  variant('audio-mini', copy('Mini audio player', 'Mini ses oynatıcı'), (T) => box('display:flex;align-items:center;gap:12px;max-width:380px;padding:12px 14px;border-radius:999px;background:#f1f5f9;', `<a href="#" aria-label="${T('Play', 'Oynat')}" style="display:grid;place-items:center;flex-shrink:0;width:38px;height:38px;border-radius:50%;background:#0f172a;color:#ffffff;text-decoration:none;">▶</a><div style="flex:1;height:5px;border-radius:99px;background:#cbd5e1;"><div style="width:30%;height:100%;border-radius:99px;background:#0f172a;"></div></div><span style="font-size:13px;color:#475569;">0:48 / 2:30</span>`)),
  variant('video-thumb', copy('Video thumbnail', 'Video küçük resmi'), (T) => box('position:relative;max-width:420px;border-radius:18px;overflow:hidden;', `${photo('widget-video', 840, 472)}<a href="#" aria-label="${T('Play video', 'Videoyu oynat')}" style="position:absolute;inset:0;margin:auto;display:grid;place-items:center;width:64px;height:64px;border-radius:50%;background:rgba(255,255,255,0.92);color:#0f172a;text-decoration:none;font-size:22px;">▶</a><span style="position:absolute;right:12px;bottom:12px;padding:3px 8px;border-radius:6px;background:rgba(0,0,0,0.75);color:#ffffff;font-size:12.5px;font-weight:700;">3:12</span>`)),
  variant('photo-strip', copy('Photo strip', 'Fotoğraf şeridi'), () => box('display:grid;grid-template-columns:repeat(3,1fr);gap:8px;max-width:480px;', ['strip-a', 'strip-b', 'strip-c'].map((seed) => photo(seed, 300, 300, 'border-radius:12px;')).join(''))),
  variant('slider-dots', copy('Slider with dots', 'Noktalı kaydırıcı'), (T) => box('max-width:440px;', `<div style="position:relative;border-radius:18px;overflow:hidden;">${photo('widget-slide', 880, 520)}<a href="#" aria-label="${T('Previous', 'Önceki')}" style="position:absolute;left:10px;top:50%;transform:translateY(-50%);display:grid;place-items:center;width:34px;height:34px;border-radius:50%;background:rgba(255,255,255,0.9);color:#0f172a;text-decoration:none;">‹</a><a href="#" aria-label="${T('Next', 'Sonraki')}" style="position:absolute;right:10px;top:50%;transform:translateY(-50%);display:grid;place-items:center;width:34px;height:34px;border-radius:50%;background:rgba(255,255,255,0.9);color:#0f172a;text-decoration:none;">›</a></div><div style="display:flex;justify-content:center;gap:6px;margin-top:10px;">${[0, 1, 2, 3].map((i) => `<i style="display:block;width:${i ? 8 : 22}px;height:8px;border-radius:99px;background:${i ? '#cbd5e1' : '#0f172a'};"></i>`).join('')}</div>`)),
]

const FEEDBACK = [
  variant('toast', copy('Toast', 'Bildirim'), (T) => box('display:flex;align-items:center;gap:12px;max-width:380px;padding:12px 16px;border-radius:14px;background:#ffffff;border:1px solid #e2e8f0;box-shadow:0 14px 34px rgba(15,23,42,0.14);', `<span aria-hidden="true" style="display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:#dcfce7;color:#16a34a;font-weight:900;">✓</span><div style="flex:1;"><b style="display:block;font-size:14.5px;">${T('Saved', 'Kaydedildi')}</b>${muted(T('Your changes are live.', 'Değişiklikleriniz yayında.'))}</div><span aria-hidden="true" style="color:#94a3b8;">✕</span>`)),
  variant('tooltip', copy('Tooltip', 'İpucu balonu'), (T) => box('display:inline-flex;flex-direction:column;align-items:center;gap:0;', `<span style="padding:8px 12px;border-radius:10px;background:#0f172a;color:#ffffff;font-size:13.5px;font-weight:600;">${T('Copied to clipboard', 'Panoya kopyalandı')}</span><span aria-hidden="true" style="width:0;height:0;border:7px solid transparent;border-top-color:#0f172a;"></span>`)),
  variant('empty-state', copy('Empty state', 'Boş durum'), (T) => box('max-width:360px;padding:30px 24px;border-radius:18px;border:1.5px dashed #cbd5e1;text-align:center;', `<span aria-hidden="true" style="display:inline-grid;place-items:center;width:56px;height:56px;border-radius:16px;background:#f1f5f9;font-size:26px;margin-bottom:12px;">🛒</span><b style="display:block;margin-bottom:6px;font-size:17px;">${T('Your cart is empty', 'Sepetiniz boş')}</b><p style="margin:0 0 16px;color:#64748b;font-size:14.5px;">${T('Find something you love in the shop.', 'Mağazada sevdiğiniz bir şey bulun.')}</p><a href="#" style="display:inline-block;padding:10px 18px;border-radius:10px;background:#0f172a;color:#ffffff;text-decoration:none;font-weight:700;font-size:14.5px;">${T('Start shopping', 'Alışverişe başlayın')}</a>`)),
  variant('skeleton', copy('Loading placeholder', 'Yükleniyor yer tutucusu'), (T) => box('display:flex;gap:14px;align-items:center;max-width:380px;', `<span aria-hidden="true" style="flex-shrink:0;width:52px;height:52px;border-radius:14px;background:#e2e8f0;"></span><div style="flex:1;display:grid;gap:8px;" aria-label="${T('Loading', 'Yükleniyor')}"><span style="display:block;height:12px;width:70%;border-radius:6px;background:#e2e8f0;"></span><span style="display:block;height:12px;width:45%;border-radius:6px;background:#f1f5f9;"></span></div>`)),
  variant('confirmation', copy('Confirmation', 'Onay'), (T) => box('max-width:340px;text-align:center;', `<span aria-hidden="true" style="display:inline-grid;place-items:center;width:64px;height:64px;border-radius:50%;background:#16a34a;color:#ffffff;font-size:30px;font-weight:900;margin-bottom:12px;">✓</span><b style="display:block;font-size:19px;margin-bottom:6px;">${T('Thank you!', 'Teşekkürler!')}</b><p style="margin:0;color:#64748b;line-height:1.6;">${T('We have received your message and will reply within a day.', 'Mesajınızı aldık, bir gün içinde yanıt vereceğiz.')}</p>`)),
  variant('notification-dot', copy('Notification bell', 'Bildirim zili'), (T) => `<a href="#" aria-label="${T('Notifications', 'Bildirimler')}" style="${FONT}position:relative;display:inline-grid;place-items:center;width:46px;height:46px;margin:8px 8px 0 0;border-radius:14px;background:#f1f5f9;color:#0f172a;text-decoration:none;font-size:20px;">🔔<span style="position:absolute;top:-4px;right:-4px;display:grid;place-items:center;min-width:20px;height:20px;padding:0 5px;border-radius:999px;background:#ef4444;color:#ffffff;font-size:11.5px;font-weight:800;border:2px solid #ffffff;">3</span></a>`),
]

const DATA = [
  variant('table', copy('Table', 'Tablo'), (T) => `<table style="${FONT}width:100%;max-width:520px;border-collapse:collapse;font-size:14.5px;color:#0f172a;"><thead><tr>${[T('Plan', 'Plan'), T('Users', 'Kullanıcı'), T('Price', 'Fiyat')].map((h) => `<th style="text-align:left;padding:10px 12px;background:#f8fafc;border-bottom:1px solid #e2e8f0;font-weight:700;">${h}</th>`).join('')}</tr></thead><tbody>${[[T('Starter', 'Başlangıç'), '1', '€0'], ['Pro', '5', '€12'], [T('Team', 'Ekip'), '20', '€39']].map((row) => `<tr>${row.map((cell) => `<td style="padding:10px 12px;border-bottom:1px solid #f1f5f9;">${cell}</td>`).join('')}</tr>`).join('')}</tbody></table>`),
  variant('key-values', copy('Key facts', 'Temel bilgiler'), (T) => box('display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:12px;max-width:480px;', [[T('Founded', 'Kuruluş'), '2012'], [T('Team', 'Ekip'), '24'], [T('Countries', 'Ülke'), '11']].map(([k, v]) => `<div style="padding:14px;border-radius:14px;background:#f8fafc;">${muted(k, 'display:block;margin-bottom:4px;')}<b style="font-size:22px;">${v}</b></div>`).join(''))),
  variant('kpi-sparkline', copy('KPI with chart', 'Grafikli gösterge'), (T) => box('max-width:320px;padding:18px;border-radius:16px;background:#0f172a;color:#e2e8f0;', `${muted(T('Revenue this month', 'Bu ayki gelir'), 'color:#94a3b8;')}<div style="display:flex;align-items:baseline;gap:8px;margin:4px 0 10px;"><b style="font-size:30px;color:#ffffff;">€48.2K</b><span style="color:#4ade80;font-size:13.5px;font-weight:700;">▲ 8.4%</span></div><svg aria-hidden="true" viewBox="0 0 200 50" style="display:block;width:100%;height:50px;"><path d="M0 42 L20 38 L40 40 L60 30 L80 32 L100 22 L120 26 L140 16 L160 18 L180 8 L200 10 L200 50 L0 50 Z" fill="rgba(74,222,128,0.15)"/><path d="M0 42 L20 38 L40 40 L60 30 L80 32 L100 22 L120 26 L140 16 L160 18 L180 8 L200 10" fill="none" stroke="#4ade80" stroke-width="2.5"/></svg>`)),
  variant('bar-chart', copy('Bar chart', 'Çubuk grafik'), (T) => box('max-width:380px;', `<div style="display:flex;align-items:flex-end;gap:10px;height:140px;padding-bottom:6px;border-bottom:1px solid #e2e8f0;">${[40, 65, 50, 80, 72, 95].map((h, i) => `<div style="flex:1;height:${h}%;border-radius:8px 8px 3px 3px;background:${i === 5 ? '#4f46e5' : '#c7d2fe'};"></div>`).join('')}</div><div style="display:flex;gap:10px;margin-top:6px;">${[T('Jan', 'Oca'), T('Feb', 'Şub'), T('Mar', 'Mar'), T('Apr', 'Nis'), T('May', 'May'), T('Jun', 'Haz')].map((m) => `<span style="flex:1;text-align:center;font-size:12px;color:#64748b;">${m}</span>`).join('')}</div>`)),
  variant('code-block', copy('Code block', 'Kod bloğu'), () => `<pre style="${FONT}margin:0;max-width:480px;padding:16px 18px;border-radius:14px;background:#0f172a;color:#e2e8f0;font-family:ui-monospace,Menlo,Consolas,monospace;font-size:13.5px;line-height:1.7;overflow:auto;"><code><span style="color:#c084fc;">const</span> site = <span style="color:#38bdf8;">build</span>({\n  name: <span style="color:#86efac;">'Studio North'</span>,\n  pages: <span style="color:#fbbf24;">4</span>,\n})</code></pre>`),
  variant('shortcut', copy('Keyboard shortcut', 'Klavye kısayolu'), (T) => box('display:inline-flex;align-items:center;gap:8px;font-size:14.5px;color:#475569;', `${T('Press', 'Arama için')} ${['Ctrl', 'K'].map((key) => `<kbd style="display:inline-block;padding:3px 8px;border-radius:7px;border:1px solid #cbd5e1;border-bottom-width:3px;background:#ffffff;color:#0f172a;font-family:ui-monospace,Menlo,monospace;font-size:13px;font-weight:700;">${key}</kbd>`).join('')} ${T('to search', 'tuşlarına basın')}`)),
]

const FORMS = [
  variant('toggle', copy('Toggle switch', 'Açma kapama anahtarı'), (T) => `<label style="${FONT}display:inline-flex;align-items:center;gap:12px;cursor:pointer;font-size:15px;color:#0f172a;"><input type="checkbox" name="notifications" checked style="position:absolute;opacity:0;width:1px;height:1px;" /><span aria-hidden="true" style="position:relative;width:46px;height:26px;border-radius:999px;background:#4f46e5;"><span style="position:absolute;top:3px;left:23px;width:20px;height:20px;border-radius:50%;background:#ffffff;box-shadow:0 1px 3px rgba(0,0,0,0.3);"></span></span>${T('Email notifications', 'E-posta bildirimleri')}</label>`),
  variant('checkboxes', copy('Checkbox group', 'Onay kutusu grubu'), (T) => `<fieldset style="${FONT}margin:0;padding:0;border:0;color:#0f172a;"><legend style="margin-bottom:10px;font-weight:700;">${T('Interests', 'İlgi alanları')}</legend>${[T('Yoga', 'Yoga'), T('Pilates', 'Pilates'), T('Meditation', 'Meditasyon')].map((label, i) => `<label style="display:flex;align-items:center;gap:10px;margin-bottom:8px;font-size:15px;cursor:pointer;"><input type="checkbox" name="interests" value="${label}"${i === 0 ? ' checked' : ''} style="width:18px;height:18px;accent-color:#4f46e5;" />${label}</label>`).join('')}</fieldset>`),
  variant('radio-cards', copy('Radio cards', 'Seçim kartları'), (T) => `<fieldset style="${FONT}margin:0;padding:0;border:0;display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px;max-width:460px;color:#0f172a;"><legend style="margin-bottom:10px;font-weight:700;">${T('Delivery', 'Teslimat')}</legend>${[[T('Standard', 'Standart'), T('2–3 days · free', '2–3 gün · ücretsiz')], [T('Express', 'Ekspres'), T('Next day · €6', 'Ertesi gün · €6')]].map(([title, note], i) => `<label style="display:flex;gap:10px;align-items:flex-start;padding:14px;border-radius:14px;cursor:pointer;${i === 0 ? 'border:2px solid #4f46e5;background:#eef2ff;' : 'border:1px solid #e2e8f0;'}"><input type="radio" name="delivery" value="${title}"${i === 0 ? ' checked' : ''} style="margin-top:3px;accent-color:#4f46e5;" /><span><b style="display:block;">${title}</b><span style="font-size:13.5px;color:#64748b;">${note}</span></span></label>`).join('')}</fieldset>`),
  variant('range', copy('Range slider', 'Aralık kaydırıcısı'), (T) => `<label style="${FONT}display:block;max-width:360px;color:#0f172a;"><span style="display:flex;justify-content:space-between;margin-bottom:8px;font-weight:700;">${T('Budget', 'Bütçe')}<span style="color:#4f46e5;">€2,500</span></span><input type="range" name="budget" min="500" max="10000" value="2500" style="width:100%;accent-color:#4f46e5;" /><span style="display:flex;justify-content:space-between;font-size:12.5px;color:#94a3b8;"><span>€500</span><span>€10,000</span></span></label>`),
  variant('file-upload', copy('File upload', 'Dosya yükleme'), (T) => `<label style="${FONT}display:grid;justify-items:center;gap:8px;max-width:420px;padding:28px 20px;border-radius:18px;border:2px dashed #cbd5e1;background:#f8fafc;text-align:center;cursor:pointer;color:#0f172a;"><span aria-hidden="true" style="display:grid;place-items:center;width:48px;height:48px;border-radius:14px;background:#e0e7ff;color:#4338ca;font-size:22px;">↑</span><b>${T('Drop files here or browse', 'Dosyaları buraya bırakın ya da seçin')}</b><span style="font-size:13px;color:#64748b;">${T('PDF, JPG or PNG, up to 10 MB', 'PDF, JPG ya da PNG, en fazla 10 MB')}</span><input type="file" name="attachment" style="position:absolute;opacity:0;width:1px;height:1px;" /></label>`),
  variant('code-boxes', copy('Verification code', 'Doğrulama kodu'), (T) => `<fieldset style="${FONT}margin:0;padding:0;border:0;color:#0f172a;"><legend style="margin-bottom:10px;font-weight:700;">${T('Enter the 6-digit code', '6 haneli kodu girin')}</legend><div style="display:flex;gap:8px;">${[1, 2, 3, 4, 5, 6].map((n) => `<input type="text" name="code-${n}" inputmode="numeric" maxlength="1" aria-label="${T('Digit', 'Hane')} ${n}" style="width:46px;height:54px;border:1px solid #cbd5e1;border-radius:12px;text-align:center;font-size:22px;font-weight:700;font-family:inherit;" />`).join('')}</div></fieldset>`),
  variant('mini-signup', copy('Mini sign-up', 'Mini kayıt formu'), (T) => `<form style="${FONT}display:flex;flex-wrap:wrap;gap:8px;max-width:440px;"><input type="email" name="email" placeholder="${T('Your email', 'E-postanız')}" aria-label="${T('Your email', 'E-postanız')}" style="flex:1 1 200px;min-width:0;padding:12px 14px;border:1px solid #cbd5e1;border-radius:12px;font-size:15px;font-family:inherit;" /><button type="submit" style="padding:12px 20px;border:0;border-radius:12px;background:#0f172a;color:#ffffff;font-weight:700;font-size:15px;font-family:inherit;cursor:pointer;">${T('Subscribe', 'Abone ol')}</button></form>`),
]

const PEOPLE = [
  variant('byline', copy('Author byline', 'Yazar satırı'), (T) => box('display:inline-flex;align-items:center;gap:12px;', `${circle('E', '#7c3aed', 44)}<span><b style="display:block;">Elena Petrova</b>${muted(`${T('12 May 2026', '12 Mayıs 2026')} · ${T('6 min read', '6 dk okuma')}`)}</span>`)),
  variant('avatar-status', copy('Avatar with status', 'Durumlu avatar'), () => box('position:relative;display:inline-block;', `${circle('K', '#0ea5e9', 64)}<span style="position:absolute;right:2px;bottom:2px;width:16px;height:16px;border-radius:50%;background:#22c55e;border:3px solid #ffffff;"></span>`)),
  variant('team-mini', copy('Mini team list', 'Mini ekip listesi'), (T) => box('max-width:320px;display:grid;gap:12px;', [['A', '#6366f1', 'Ayşe Demir', T('Founder', 'Kurucu')], ['L', '#ec4899', 'Leo Martin', T('Design', 'Tasarım')], ['M', '#f59e0b', 'Mert Koç', T('Engineering', 'Yazılım')]].map(([l, c, name, role]) => `<div style="display:flex;align-items:center;gap:12px;">${circle(l, c, 40)}<span><b style="display:block;font-size:15px;">${name}</b>${muted(role)}</span></div>`).join(''))),
  variant('mini-testimonial', copy('Mini testimonial', 'Mini müşteri yorumu'), (T) => box('display:flex;gap:12px;align-items:flex-start;max-width:380px;', `${circle('C', '#0d9488', 42)}<div><p style="margin:0 0 6px;line-height:1.55;font-size:15px;">“${T('Setup took ten minutes. I keep waiting for the catch.', 'Kurulum on dakika sürdü. Hâlâ bir bit yeniği arıyorum.')}”</p>${muted('Cem Uslu · Northwind')}</div>`)),
  variant('speaker', copy('Speaker', 'Konuşmacı'), (T) => box('display:flex;align-items:center;gap:14px;max-width:360px;', `<div style="width:72px;flex-shrink:0;">${photo('widget-speaker', 200, 200, 'border-radius:50%;')}</div><div><b style="display:block;font-size:16px;">Aylin Çınar</b>${muted(T('Designer, Studio North', 'Tasarımcı, Studio North'))}<br /><span style="font-size:13.5px;font-weight:700;color:#7c3aed;">${T('Talk: Building for people', 'Konuşma: İnsanlar için üretmek')}</span></div>`)),
]

const MARKETING = [
  variant('announcement-pill', copy('Announcement pill', 'Duyuru hapı'), (T) => `<a href="#" style="${FONT}display:inline-flex;align-items:center;gap:10px;padding:5px 14px 5px 5px;border-radius:999px;border:1px solid #e2e8f0;background:#ffffff;color:#0f172a;text-decoration:none;font-size:14px;"><span style="padding:4px 10px;border-radius:999px;background:#4f46e5;color:#ffffff;font-weight:800;font-size:12.5px;">${T('New', 'Yeni')}</span>${T('Online booking is here', 'Online rezervasyon geldi')} <span aria-hidden="true" style="color:#94a3b8;">→</span></a>`),
  variant('guarantee', copy('Guarantee seal', 'Garanti mührü'), (T) => box('display:inline-flex;align-items:center;gap:14px;', `<span aria-hidden="true" style="display:grid;place-items:center;width:70px;height:70px;border-radius:50%;background:#fef3c7;border:3px dashed #d97706;color:#92400e;font-weight:900;font-size:15px;text-align:center;line-height:1;">30<br /><small style="font-size:10px;">${T('DAYS', 'GÜN')}</small></span><span><b style="display:block;">${T('Money-back guarantee', 'Para iade garantisi')}</b>${muted(T('Not happy? Full refund, no questions.', 'Memnun kalmazsanız koşulsuz tam iade.'))}</span>`)),
  variant('mini-stats', copy('Mini stats row', 'Mini istatistik satırı'), (T) => box('display:flex;flex-wrap:wrap;gap:28px;', [['12K+', T('customers', 'müşteri')], ['4.9', T('rating', 'puan')], ['24/7', T('support', 'destek')]].map(([n, l]) => `<div><b style="display:block;font-size:28px;letter-spacing:-0.02em;color:#4f46e5;">${n}</b>${muted(l)}</div>`).join(''))),
  variant('feature-box', copy('Feature checklist box', 'Özellik listesi kutusu'), (T) => box('max-width:340px;padding:20px 22px;border-radius:18px;background:#f5f3ff;', `<b style="display:block;margin-bottom:10px;color:#4c1d95;">${T('Every plan includes', 'Her planda dahil')}</b>${[T('Custom domain', 'Özel alan adı'), T('SSL certificate', 'SSL sertifikası'), T('Daily backups', 'Günlük yedek'), T('Email support', 'E-posta desteği')].map((item) => `<div style="display:flex;gap:10px;margin-bottom:6px;font-size:15px;"><span aria-hidden="true" style="color:#7c3aed;font-weight:900;">✓</span>${item}</div>`).join('')}`)),
  variant('as-seen-in', copy('As seen in', 'Basında biz'), (T) => box('display:flex;flex-wrap:wrap;align-items:center;gap:22px;', `${muted(T('As seen in', 'Basında biz'), 'font-weight:700;letter-spacing:0.1em;text-transform:uppercase;font-size:12px;')}${[['The Weekly', 'font-family:Georgia,serif;font-weight:700;'], ['DESIGN DAILY', 'font-weight:900;letter-spacing:0.14em;font-size:13px;'], ['City Guide', 'font-style:italic;font-weight:800;']].map(([name, style]) => `<span style="color:#475569;font-size:17px;${style}">${name}</span>`).join('')}`)),
  variant('limited-offer', copy('Limited offer strip', 'Sınırlı teklif şeridi'), (T) => box('display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:12px;max-width:520px;padding:12px 16px;border-radius:14px;background:#0f172a;color:#ffffff;', `<span style="font-size:14.5px;"><b style="color:#facc15;">−30%</b> ${T('on all courses until Sunday', 'pazara kadar tüm kurslarda')}</span><a href="#" style="padding:8px 14px;border-radius:9px;background:#facc15;color:#0f172a;text-decoration:none;font-weight:800;font-size:14px;">${T('Claim offer', 'Fırsatı yakalayın')}</a>`)),
]

export const WIDGET_GROUPS = [
  { id: 'rating', name: copy('Ratings and reviews', 'Puanlar ve yorumlar'), widgets: RATING },
  { id: 'progress', name: copy('Progress', 'İlerleme'), widgets: PROGRESS },
  { id: 'time', name: copy('Time and dates', 'Zaman ve tarihler'), widgets: TIME },
  { id: 'social', name: copy('Social', 'Sosyal'), widgets: SOCIAL },
  { id: 'navigation', name: copy('Navigation aids', 'Gezinme yardımcıları'), widgets: NAVIGATION },
  { id: 'commerce', name: copy('Shop bits', 'Mağaza parçaları'), widgets: COMMERCE },
  { id: 'contact', name: copy('Contact bits', 'İletişim parçaları'), widgets: CONTACT },
  { id: 'media', name: copy('Media bits', 'Medya parçaları'), widgets: MEDIA },
  { id: 'feedback', name: copy('Feedback and states', 'Geri bildirim ve durumlar'), widgets: FEEDBACK },
  { id: 'data', name: copy('Data and code', 'Veri ve kod'), widgets: DATA },
  { id: 'forms', name: copy('Form bits', 'Form parçaları'), widgets: FORMS },
  { id: 'people', name: copy('People', 'Kişiler'), widgets: PEOPLE },
  { id: 'marketing', name: copy('Marketing bits', 'Pazarlama parçaları'), widgets: MARKETING },
]
