# Generated by Django 6.0.8 on 2026-09-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0022_verified_unique_custom_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='share_mode',
            field=models.CharField(choices=[('off', 'Not shared'), ('link', 'Anyone with the link'), ('people', 'Only invited people')], default='off', max_length=8),
        ),
    ]
