# Generated by Django 6.0.8 on 2026-09-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0023_new_sites_start_unshared'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_themes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
