// Rich library of ready-made HTML snippets for the HTML-upload editor's palette.
// Each entry is a self-contained, inline-styled element so it drops cleanly into
// any document (no external CSS needed) and previews live in the palette. Lots of
// variety per type — especially buttons — so the palette feels like a real
// component library, not one bland default.

import { SECTION_BLOCKS } from './sectionBlocks/index.js'

const B = (style, label = 'Button') =>
  `<a href="#" style="${style}">${label}</a>`

const BTN_BASE = 'display:inline-block;text-decoration:none;font-weight:600;cursor:pointer;text-align:center;font-family:inherit;'

const buttons = [
  ['solid', 'Solid', B(`${BTN_BASE}padding:12px 26px;background:#2563eb;color:#fff;border-radius:10px;`)],
  ['gradient', 'Gradient', B(`${BTN_BASE}padding:12px 26px;background:linear-gradient(90deg,#6366f1,#a855f7);color:#fff;border-radius:10px;`)],
  ['glow', 'Glow', B(`${BTN_BASE}padding:12px 26px;background:linear-gradient(90deg,#2563eb,#7c3aed);color:#fff;border-radius:10px;box-shadow:0 10px 30px rgba(37,99,235,0.45);`)],
  ['pill', 'Pill', B(`${BTN_BASE}padding:12px 30px;background:#111827;color:#fff;border-radius:999px;`)],
  ['outline', 'Outline', B(`${BTN_BASE}padding:11px 25px;background:transparent;color:#2563eb;border:2px solid #2563eb;border-radius:10px;`)],
  ['outline-pill', 'Outline pill', B(`${BTN_BASE}padding:11px 28px;background:transparent;color:#111827;border:1.5px solid #111827;border-radius:999px;`)],
  ['ghost', 'Ghost', B(`${BTN_BASE}padding:12px 24px;background:#eef2ff;color:#4338ca;border-radius:10px;`)],
  ['soft', 'Soft', B(`${BTN_BASE}padding:12px 24px;background:rgba(37,99,235,0.12);color:#2563eb;border-radius:12px;`)],
  ['dark', 'Dark', B(`${BTN_BASE}padding:12px 26px;background:#0f172a;color:#fff;border-radius:10px;`)],
  ['3d', '3D', B(`${BTN_BASE}padding:12px 26px;background:#f59e0b;color:#1f2937;border-radius:12px;box-shadow:0 5px 0 #b45309;`)],
  ['neon', 'Neon', B(`${BTN_BASE}padding:12px 26px;background:#0b0f19;color:#22d3ee;border:1px solid #22d3ee;border-radius:10px;box-shadow:0 0 16px rgba(34,211,238,0.55);`)],
  ['glass', 'Glass', B(`${BTN_BASE}padding:12px 26px;background:rgba(255,255,255,0.18);color:#fff;border:1px solid rgba(255,255,255,0.4);border-radius:12px;backdrop-filter:blur(8px);`)],
  ['shadow', 'Shadow', B(`${BTN_BASE}padding:12px 26px;background:#fff;color:#111827;border-radius:12px;box-shadow:0 12px 28px rgba(0,0,0,0.16);`)],
  ['gradient-border', 'Gradient edge', `<a href="#" style="${BTN_BASE}padding:2px;background:linear-gradient(90deg,#ec4899,#8b5cf6);border-radius:12px;"><span style="display:block;padding:10px 24px;background:#fff;color:#111827;border-radius:10px;">Button</span></a>`],
  ['arrow', 'With arrow', B(`${BTN_BASE}padding:12px 26px;background:#16a34a;color:#fff;border-radius:10px;`, 'Continue &nbsp;&rarr;')],
  ['block', 'Full width', B(`${BTN_BASE}display:block;padding:14px;background:#2563eb;color:#fff;border-radius:10px;`)],
  ['minimal', 'Minimal link', B(`${BTN_BASE}padding:6px 2px;background:transparent;color:#2563eb;border-bottom:2px solid #2563eb;border-radius:0;`, 'Read more')],
  ['danger', 'Danger', B(`${BTN_BASE}padding:12px 26px;background:#dc2626;color:#fff;border-radius:10px;`, 'Delete')],
  // Responsive by construction: max-width:100% so the button never overflows a
  // narrow embed box; groups use inline-flex + wrap; fill-mode scales the label.
  ['success', 'Success', B(`${BTN_BASE}padding:12px 26px;background:#16a34a;color:#fff;border-radius:10px;max-width:100%;`, 'Save')],
  ['warning', 'Warning', B(`${BTN_BASE}padding:12px 26px;background:#f59e0b;color:#1f2937;border-radius:10px;max-width:100%;`, 'Review')],
  ['icon-left', 'Icon left', B(`${BTN_BASE}display:inline-flex;align-items:center;gap:9px;padding:12px 24px;background:#2563eb;color:#fff;border-radius:10px;max-width:100%;`, '<span aria-hidden="true">&darr;</span> Download')],
  ['sunset', 'Sunset', B(`${BTN_BASE}padding:12px 28px;background:linear-gradient(90deg,#f97316,#ec4899);color:#fff;border-radius:12px;max-width:100%;`)],
  ['ocean', 'Ocean', B(`${BTN_BASE}padding:12px 28px;background:linear-gradient(90deg,#0ea5e9,#6366f1);color:#fff;border-radius:12px;max-width:100%;`)],
  ['soft-rose', 'Soft rose', B(`${BTN_BASE}padding:12px 24px;background:#ffe4e6;color:#be123c;border-radius:12px;max-width:100%;`)],
  ['soft-emerald', 'Soft emerald', B(`${BTN_BASE}padding:12px 24px;background:#d1fae5;color:#047857;border-radius:12px;max-width:100%;`)],
  ['elevated', 'Elevated', B(`${BTN_BASE}padding:13px 28px;background:#4f46e5;color:#fff;border-radius:12px;box-shadow:0 8px 20px rgba(79,70,229,0.4);max-width:100%;`)],
  ['mono-outline', 'Mono outline', B(`${BTN_BASE}padding:11px 26px;background:#fff;color:#0f172a;border:1.5px solid #e2e8f0;border-radius:10px;box-shadow:0 1px 2px rgba(0,0,0,0.05);max-width:100%;`)],
  ['pill-icon', 'Pill + icon', B(`${BTN_BASE}display:inline-flex;align-items:center;gap:9px;padding:11px 24px;background:#0f172a;color:#fff;border-radius:999px;max-width:100%;`, 'Get started <span aria-hidden="true">&rarr;</span>')],
  ['gradient-pill', 'Gradient pill', B(`${BTN_BASE}padding:12px 30px;background:linear-gradient(90deg,#8b5cf6,#ec4899);color:#fff;border-radius:999px;max-width:100%;`)],
  ['frost', 'Frost', B(`${BTN_BASE}padding:12px 26px;background:#f1f5f9;color:#334155;border:1px solid #e2e8f0;border-radius:10px;max-width:100%;`)],
  ['cta-large', 'Large CTA', B(`${BTN_BASE}padding:16px 34px;font-size:17px;background:#2563eb;color:#fff;border-radius:12px;max-width:100%;`, 'Start free trial')],
  ['play', 'Play', B(`${BTN_BASE}display:inline-flex;align-items:center;gap:10px;padding:12px 26px;background:#111827;color:#fff;border-radius:999px;max-width:100%;`, '<span aria-hidden="true">&#9654;</span> Watch demo')],
]

const navbars = [
  ['dark', 'Dark', `<nav style="display:flex;justify-content:space-between;align-items:center;padding:16px 30px;background:#0f172a;color:#fff;font-family:inherit;flex-wrap:wrap;gap:12px;"><span style="font-weight:800;font-size:19px;">Brand</span><div style="display:flex;gap:22px;font-size:15px;"><a href="#" style="color:#cbd5e1;text-decoration:none;">Home</a><a href="#" style="color:#cbd5e1;text-decoration:none;">About</a><a href="#" style="color:#cbd5e1;text-decoration:none;">Contact</a></div></nav>`],
  ['light', 'Light', `<nav style="display:flex;justify-content:space-between;align-items:center;padding:16px 30px;background:#fff;color:#111827;font-family:inherit;border-bottom:1px solid #e5e7eb;flex-wrap:wrap;gap:12px;"><span style="font-weight:800;font-size:19px;">Brand</span><div style="display:flex;gap:22px;font-size:15px;"><a href="#" style="color:#374151;text-decoration:none;">Home</a><a href="#" style="color:#374151;text-decoration:none;">About</a><a href="#" style="color:#374151;text-decoration:none;">Contact</a></div></nav>`],
  ['cta', 'With button', `<nav style="display:flex;justify-content:space-between;align-items:center;padding:14px 30px;background:#fff;color:#111827;font-family:inherit;box-shadow:0 1px 0 rgba(0,0,0,0.06);flex-wrap:wrap;gap:12px;"><span style="font-weight:800;font-size:19px;">Brand</span><div style="display:flex;gap:20px;align-items:center;font-size:15px;"><a href="#" style="color:#374151;text-decoration:none;">Features</a><a href="#" style="color:#374151;text-decoration:none;">Pricing</a><a href="#" style="padding:9px 18px;background:#2563eb;color:#fff;border-radius:8px;text-decoration:none;font-weight:600;">Sign up</a></div></nav>`],
  ['gradient', 'Gradient', `<nav style="display:flex;justify-content:space-between;align-items:center;padding:16px 30px;background:linear-gradient(90deg,#4f46e5,#9333ea);color:#fff;font-family:inherit;flex-wrap:wrap;gap:12px;"><span style="font-weight:800;font-size:19px;">Brand</span><div style="display:flex;gap:22px;font-size:15px;"><a href="#" style="color:rgba(255,255,255,0.9);text-decoration:none;">Home</a><a href="#" style="color:rgba(255,255,255,0.9);text-decoration:none;">Work</a><a href="#" style="color:rgba(255,255,255,0.9);text-decoration:none;">Contact</a></div></nav>`],
  ['centered', 'Centered', `<nav style="display:flex;flex-direction:column;align-items:center;gap:8px;padding:18px;background:#fff;color:#111827;font-family:inherit;border-bottom:1px solid #e5e7eb;"><span style="font-weight:800;font-size:20px;letter-spacing:1px;">BRAND</span><div style="display:flex;gap:26px;font-size:14px;"><a href="#" style="color:#374151;text-decoration:none;">Home</a><a href="#" style="color:#374151;text-decoration:none;">About</a><a href="#" style="color:#374151;text-decoration:none;">Blog</a><a href="#" style="color:#374151;text-decoration:none;">Contact</a></div></nav>`],
  ['vertical', 'Vertical sidebar', `<nav style="display:flex;flex-direction:column;gap:6px;width:220px;padding:22px 16px;background:#0f172a;color:#fff;font-family:inherit;min-height:320px;"><span style="font-weight:800;font-size:19px;padding:0 10px 14px;">Brand</span>${['Dashboard', 'Projects', 'Team', 'Settings'].map((l, i) => `<a href="#" style="padding:10px 12px;border-radius:8px;color:${i === 0 ? '#fff' : '#94a3b8'};background:${i === 0 ? 'rgba(255,255,255,0.1)' : 'transparent'};text-decoration:none;font-size:15px;">${l}</a>`).join('')}</nav>`],
  ['vertical-light', 'Vertical light', `<nav style="display:flex;flex-direction:column;gap:4px;width:220px;padding:22px 16px;background:#fff;color:#111827;font-family:inherit;border-right:1px solid #e5e7eb;min-height:320px;"><span style="font-weight:800;font-size:19px;padding:0 10px 14px;">Brand</span>${['Overview', 'Analytics', 'Customers', 'Billing'].map((l, i) => `<a href="#" style="padding:10px 12px;border-radius:8px;color:${i === 0 ? '#4f46e5' : '#374151'};background:${i === 0 ? '#eef2ff' : 'transparent'};text-decoration:none;font-size:15px;font-weight:${i === 0 ? 600 : 400};">${l}</a>`).join('')}</nav>`],
  ['sticky', 'Floating pill', `<nav style="display:flex;justify-content:space-between;align-items:center;padding:12px 24px;margin:14px;background:rgba(255,255,255,0.8);backdrop-filter:blur(10px);border:1px solid #e5e7eb;border-radius:999px;box-shadow:0 8px 24px rgba(0,0,0,0.08);color:#111827;font-family:inherit;flex-wrap:wrap;gap:12px;"><span style="font-weight:800;font-size:18px;">Brand</span><div style="display:flex;gap:8px;align-items:center;font-size:14px;"><a href="#" style="padding:7px 14px;border-radius:999px;color:#374151;text-decoration:none;">Home</a><a href="#" style="padding:7px 14px;border-radius:999px;color:#374151;text-decoration:none;">Work</a><a href="#" style="padding:7px 16px;border-radius:999px;background:#111827;color:#fff;text-decoration:none;font-weight:600;">Contact</a></div></nav>`],
  ['transparent', 'Transparent', `<nav style="display:flex;justify-content:space-between;align-items:center;padding:18px 30px;background:transparent;color:#0f172a;font-family:inherit;flex-wrap:wrap;gap:12px;"><span style="font-weight:800;font-size:19px;">Brand</span><div style="display:flex;gap:24px;font-size:15px;"><a href="#" style="color:#334155;text-decoration:none;">Home</a><a href="#" style="color:#334155;text-decoration:none;">Pricing</a><a href="#" style="color:#334155;text-decoration:none;">Blog</a></div></nav>`],
  ['search', 'With search', `<nav style="display:flex;justify-content:space-between;align-items:center;gap:16px;padding:14px 28px;background:#fff;color:#111827;font-family:inherit;border-bottom:1px solid #e5e7eb;flex-wrap:wrap;"><span style="font-weight:800;font-size:19px;">Brand</span><input placeholder="Search…" style="flex:1;min-width:140px;max-width:320px;padding:8px 14px;border:1px solid #e2e8f0;border-radius:999px;font-size:14px;" /><div style="display:flex;gap:18px;font-size:15px;"><a href="#" style="color:#374151;text-decoration:none;">Docs</a><a href="#" style="color:#374151;text-decoration:none;">Login</a></div></nav>`],
  ['tworow', 'Two row', `<nav style="font-family:inherit;border-bottom:1px solid #e5e7eb;background:#fff;color:#111827;"><div style="display:flex;justify-content:space-between;align-items:center;padding:12px 28px;"><span style="font-weight:800;font-size:20px;">Brand</span><div style="display:flex;gap:12px;font-size:13px;color:#64748b;"><a href="#" style="color:inherit;text-decoration:none;">Login</a><a href="#" style="color:inherit;text-decoration:none;">Sign up</a></div></div><div style="display:flex;gap:26px;padding:10px 28px;background:#f8fafc;font-size:14px;">${['Home', 'Products', 'Solutions', 'Pricing', 'About'].map((l) => `<a href="#" style="color:#374151;text-decoration:none;">${l}</a>`).join('')}</div></nav>`],
]

const cards = [
  ['elevated', 'Elevated', `<div style="padding:24px;border-radius:16px;background:#fff;box-shadow:0 12px 30px rgba(0,0,0,0.1);font-family:inherit;max-width:320px;"><h3 style="margin:0 0 8px;font-size:20px;">Card title</h3><p style="margin:0;color:#64748b;line-height:1.6;">A short supporting description for this card.</p></div>`],
  ['outline', 'Outline', `<div style="padding:24px;border-radius:14px;background:#fff;border:1px solid #e2e8f0;font-family:inherit;max-width:320px;"><h3 style="margin:0 0 8px;font-size:20px;">Card title</h3><p style="margin:0;color:#64748b;line-height:1.6;">A short supporting description for this card.</p></div>`],
  ['gradient', 'Gradient', `<div style="padding:26px;border-radius:16px;background:linear-gradient(135deg,#6366f1,#a855f7);color:#fff;font-family:inherit;max-width:320px;"><h3 style="margin:0 0 8px;font-size:20px;">Card title</h3><p style="margin:0;color:rgba(255,255,255,0.85);line-height:1.6;">A short supporting description for this card.</p></div>`],
  ['icon', 'Icon top', `<div style="padding:24px;border-radius:16px;background:#fff;box-shadow:0 8px 24px rgba(0,0,0,0.08);font-family:inherit;max-width:320px;"><div style="width:44px;height:44px;border-radius:12px;background:#eef2ff;color:#4f46e5;display:grid;place-items:center;font-size:22px;margin-bottom:14px;">★</div><h3 style="margin:0 0 6px;font-size:18px;">Feature</h3><p style="margin:0;color:#64748b;line-height:1.6;">Describe the feature in one line.</p></div>`],
  ['image', 'Image card', `<div style="border-radius:16px;overflow:hidden;background:#fff;box-shadow:0 10px 26px rgba(0,0,0,0.1);font-family:inherit;max-width:320px;"><img src="https://picsum.photos/seed/9/640/320" alt="" style="width:100%;height:150px;object-fit:cover;display:block;" /><div style="padding:18px 20px;"><h3 style="margin:0 0 6px;font-size:18px;">Article title</h3><p style="margin:0;color:#64748b;line-height:1.6;">A short teaser for the article.</p></div></div>`],
  ['profile', 'Profile', `<div style="padding:26px;border-radius:16px;background:#fff;box-shadow:0 8px 24px rgba(0,0,0,0.08);font-family:inherit;text-align:center;max-width:260px;"><div style="width:72px;height:72px;border-radius:999px;background:linear-gradient(135deg,#f472b6,#8b5cf6);margin:0 auto 14px;"></div><h3 style="margin:0 0 2px;font-size:18px;">Jane Doe</h3><p style="margin:0;color:#64748b;">Product Designer</p></div>`],
  ['horizontal', 'Horizontal', `<div style="display:flex;gap:16px;align-items:center;padding:16px;border-radius:14px;background:#fff;box-shadow:0 8px 24px rgba(0,0,0,0.08);font-family:inherit;max-width:420px;"><img src="https://picsum.photos/seed/11/200/200" alt="" style="width:84px;height:84px;border-radius:12px;object-fit:cover;flex-shrink:0;" /><div><h3 style="margin:0 0 4px;font-size:18px;">Card title</h3><p style="margin:0;color:#64748b;font-size:14px;line-height:1.5;">A compact horizontal card, great for lists.</p></div></div>`],
  ['stat', 'Stat', `<div style="padding:24px;border-radius:16px;background:#fff;box-shadow:0 8px 24px rgba(0,0,0,0.06);font-family:inherit;max-width:220px;"><div style="font-size:14px;color:#64748b;margin-bottom:6px;">Revenue</div><div style="font-size:34px;font-weight:800;color:#0f172a;">$48.2k</div><div style="font-size:13px;color:#16a34a;font-weight:600;margin-top:4px;">▲ 12% this month</div></div>`],
  ['pricing', 'Pricing', `<div style="padding:28px;border-radius:18px;background:#fff;border:2px solid #6366f1;box-shadow:0 16px 40px rgba(99,102,241,0.2);font-family:inherit;text-align:center;max-width:260px;"><div style="font-size:13px;font-weight:700;color:#6366f1;text-transform:uppercase;letter-spacing:1px;">Pro</div><div style="font-size:40px;font-weight:800;color:#0f172a;margin:6px 0 14px;">$12<span style="font-size:15px;color:#94a3b8;font-weight:500;">/mo</span></div><a href="#" style="display:block;padding:11px;border-radius:10px;background:linear-gradient(90deg,#6366f1,#a855f7);color:#fff;text-decoration:none;font-weight:600;">Choose</a></div>`],
  ['glass', 'Glass', `<div style="box-sizing:border-box;padding:24px;border-radius:16px;background:rgba(255,255,255,0.55);border:1px solid rgba(255,255,255,0.55);box-shadow:0 10px 28px rgba(15,23,42,0.1);backdrop-filter:blur(12px);font-family:inherit;max-width:320px;"><h3 style="margin:0 0 8px;font-size:20px;color:#0f172a;">Glassmorphism</h3><p style="margin:0;color:#475569;line-height:1.6;">A frosted-glass card that pops on a colorful background.</p></div>`],
  // Responsive cards: box-sizing + width:100% + max-width so they fill a small
  // box and cap on a large one; clamp() on the biggest type; inner rows wrap.
  ['bordered-top', 'Top accent', `<div style="box-sizing:border-box;width:100%;max-width:340px;padding:24px;border-radius:14px;background:#fff;border-top:4px solid #6366f1;box-shadow:0 8px 24px rgba(0,0,0,0.07);font-family:inherit;"><h3 style="margin:0 0 8px;font-size:clamp(18px,4vw,20px);color:#0f172a;">Card title</h3><p style="margin:0;color:#64748b;line-height:1.6;">A short supporting description for this card.</p></div>`],
  ['feature', 'Feature', `<div style="box-sizing:border-box;width:100%;max-width:340px;padding:26px;border-radius:16px;background:#fff;box-shadow:0 8px 24px rgba(0,0,0,0.07);font-family:inherit;"><div style="width:48px;height:48px;border-radius:14px;background:linear-gradient(135deg,#6366f1,#a855f7);display:grid;place-items:center;color:#fff;font-size:22px;margin-bottom:16px;">&#10022;</div><h3 style="margin:0 0 6px;font-size:19px;color:#0f172a;">Fast by default</h3><p style="margin:0;color:#64748b;line-height:1.6;">Explain the feature and its benefit in a sentence.</p></div>`],
  ['testimonial', 'Testimonial', `<div style="box-sizing:border-box;width:100%;max-width:400px;padding:26px;border-radius:16px;background:#fff;box-shadow:0 10px 26px rgba(0,0,0,0.08);font-family:inherit;"><p style="margin:0 0 16px;font-size:clamp(16px,4vw,18px);color:#1e293b;line-height:1.6;">"This completely changed how our team ships work."</p><div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap;"><div style="width:44px;height:44px;border-radius:999px;background:linear-gradient(135deg,#f472b6,#8b5cf6);flex-shrink:0;"></div><div><div style="font-weight:700;color:#0f172a;">Jordan Lee</div><div style="color:#64748b;font-size:14px;">Head of Design</div></div></div></div>`],
  ['notification', 'Notification', `<div style="box-sizing:border-box;width:100%;max-width:400px;display:flex;gap:14px;padding:16px;border-radius:14px;background:#fff;box-shadow:0 8px 24px rgba(0,0,0,0.08);font-family:inherit;"><div style="width:40px;height:40px;border-radius:12px;background:#eef2ff;color:#4f46e5;display:grid;place-items:center;font-size:20px;flex-shrink:0;">&#9873;</div><div style="min-width:0;"><div style="font-weight:700;color:#0f172a;">New message</div><p style="margin:2px 0 0;color:#64748b;font-size:14px;line-height:1.5;">You have a new update waiting in your inbox.</p></div></div>`],
  ['product', 'Product', `<div style="box-sizing:border-box;width:100%;max-width:300px;border-radius:16px;overflow:hidden;background:#fff;box-shadow:0 10px 26px rgba(0,0,0,0.1);font-family:inherit;"><img src="https://picsum.photos/seed/22/600/400" alt="" style="width:100%;height:180px;object-fit:cover;display:block;" /><div style="padding:18px 20px;"><div style="display:flex;justify-content:space-between;align-items:center;gap:8px;flex-wrap:wrap;"><h3 style="margin:0;font-size:18px;color:#0f172a;">Product name</h3><span style="font-weight:800;color:#16a34a;">$39</span></div><p style="margin:6px 0 14px;color:#64748b;font-size:14px;line-height:1.5;">Short product description here.</p><a href="#" style="display:block;text-align:center;padding:11px;border-radius:10px;background:#0f172a;color:#fff;text-decoration:none;font-weight:600;">Add to cart</a></div></div>`],
  ['team', 'Team member', `<div style="box-sizing:border-box;width:100%;max-width:260px;padding:24px;border-radius:16px;background:#fff;box-shadow:0 8px 24px rgba(0,0,0,0.07);font-family:inherit;text-align:center;"><img src="https://picsum.photos/seed/24/200/200" alt="" style="width:88px;height:88px;border-radius:999px;object-fit:cover;margin:0 auto 14px;display:block;" /><h3 style="margin:0 0 2px;font-size:18px;color:#0f172a;">Sam Rivera</h3><p style="margin:0 0 12px;color:#64748b;font-size:14px;">Engineer</p><div style="display:flex;justify-content:center;gap:14px;color:#94a3b8;font-size:14px;font-weight:700;"><a href="#" style="color:inherit;text-decoration:none;">in</a><a href="#" style="color:inherit;text-decoration:none;">X</a><a href="#" style="color:inherit;text-decoration:none;">gh</a></div></div>`],
  ['cta', 'CTA card', `<div style="box-sizing:border-box;width:100%;max-width:420px;padding:clamp(24px,5vw,34px);border-radius:18px;background:linear-gradient(135deg,#4f46e5,#7c3aed);color:#fff;font-family:inherit;text-align:center;"><h3 style="margin:0 0 8px;font-size:clamp(20px,5vw,24px);">Ready to start?</h3><p style="margin:0 0 18px;color:rgba(255,255,255,0.85);line-height:1.6;">Join thousands of makers building today.</p><a href="#" style="display:inline-block;padding:12px 28px;border-radius:10px;background:#fff;color:#4f46e5;text-decoration:none;font-weight:700;">Get started</a></div>`],
  ['minimal', 'Minimal', `<div style="box-sizing:border-box;width:100%;max-width:340px;padding:22px 4px;font-family:inherit;"><div style="font-size:13px;font-weight:700;color:#6366f1;letter-spacing:1px;text-transform:uppercase;margin-bottom:8px;">Step 01</div><h3 style="margin:0 0 6px;font-size:20px;color:#0f172a;">Plan the work</h3><p style="margin:0;color:#64748b;line-height:1.6;">A clean, borderless card that leans on type and space.</p></div>`],
  ['dark', 'Dark', `<div style="box-sizing:border-box;width:100%;max-width:340px;padding:26px;border-radius:16px;background:#0f172a;color:#fff;font-family:inherit;"><h3 style="margin:0 0 8px;font-size:20px;">Dark card</h3><p style="margin:0;color:#94a3b8;line-height:1.6;">Use a dark surface to make bright accents pop.</p></div>`],
  ['badge-top', 'With badge', `<div style="box-sizing:border-box;width:100%;max-width:340px;padding:24px;border-radius:16px;background:#fff;border:1px solid #e2e8f0;font-family:inherit;"><span style="display:inline-block;padding:4px 11px;border-radius:999px;background:#dcfce7;color:#15803d;font-size:12px;font-weight:700;margin-bottom:12px;">Popular</span><h3 style="margin:0 0 6px;font-size:19px;color:#0f172a;">Highlighted plan</h3><p style="margin:0;color:#64748b;line-height:1.6;">A card that leads with a status badge.</p></div>`],
]

const badges = [
  ['solid', 'Solid', `<span style="display:inline-block;padding:5px 12px;background:#2563eb;color:#fff;border-radius:999px;font-size:12px;font-weight:700;font-family:inherit;">New</span>`],
  ['soft', 'Soft', `<span style="display:inline-block;padding:5px 12px;background:#dbeafe;color:#1d4ed8;border-radius:999px;font-size:12px;font-weight:700;font-family:inherit;">Beta</span>`],
  ['outline', 'Outline', `<span style="display:inline-block;padding:4px 12px;background:transparent;color:#2563eb;border:1.5px solid #2563eb;border-radius:999px;font-size:12px;font-weight:700;font-family:inherit;">Pro</span>`],
  ['success', 'Success', `<span style="display:inline-block;padding:5px 12px;background:#dcfce7;color:#15803d;border-radius:999px;font-size:12px;font-weight:700;font-family:inherit;">Active</span>`],
  ['dot', 'With dot', `<span style="display:inline-flex;align-items:center;gap:6px;padding:5px 12px;background:#f1f5f9;color:#0f172a;border-radius:999px;font-size:12px;font-weight:600;font-family:inherit;"><span style="width:7px;height:7px;border-radius:999px;background:#22c55e;"></span>Online</span>`],
  ['gradient', 'Gradient', `<span style="display:inline-block;padding:5px 13px;background:linear-gradient(90deg,#f59e0b,#ef4444);color:#fff;border-radius:999px;font-size:12px;font-weight:700;font-family:inherit;">Hot</span>`],
  ['danger', 'Danger', `<span style="display:inline-block;padding:5px 12px;background:#fee2e2;color:#b91c1c;border-radius:999px;font-size:12px;font-weight:700;font-family:inherit;">Error</span>`],
  ['warning', 'Warning', `<span style="display:inline-block;padding:5px 12px;background:#fef3c7;color:#b45309;border-radius:999px;font-size:12px;font-weight:700;font-family:inherit;">Pending</span>`],
  ['info', 'Info', `<span style="display:inline-block;padding:5px 12px;background:#e0f2fe;color:#0369a1;border-radius:999px;font-size:12px;font-weight:700;font-family:inherit;">Info</span>`],
  ['neutral', 'Neutral', `<span style="display:inline-block;padding:5px 12px;background:#f1f5f9;color:#475569;border-radius:999px;font-size:12px;font-weight:700;font-family:inherit;">Draft</span>`],
  ['square', 'Square', `<span style="display:inline-block;padding:5px 10px;background:#2563eb;color:#fff;border-radius:6px;font-size:12px;font-weight:700;font-family:inherit;">v2.0</span>`],
  ['count', 'Count', `<span style="display:inline-flex;align-items:center;gap:7px;font-family:inherit;font-size:14px;font-weight:600;color:#0f172a;">Inbox<span style="display:inline-grid;place-items:center;min-width:20px;height:20px;padding:0 6px;border-radius:999px;background:#ef4444;color:#fff;font-size:11px;box-sizing:border-box;">9</span></span>`],
  ['icon', 'With icon', `<span style="display:inline-flex;align-items:center;gap:6px;padding:5px 12px;background:#eef2ff;color:#4338ca;border-radius:999px;font-size:12px;font-weight:700;font-family:inherit;"><span aria-hidden="true">&#9733;</span>Featured</span>`],
  ['dot-outline', 'Outline dot', `<span style="display:inline-flex;align-items:center;gap:7px;padding:5px 13px;background:#fff;color:#0f172a;border:1px solid #e2e8f0;border-radius:999px;font-size:12px;font-weight:600;font-family:inherit;"><span style="width:7px;height:7px;border-radius:999px;background:#f59e0b;"></span>Away</span>`],
  ['glow', 'Glow', `<span style="display:inline-block;padding:5px 13px;background:#2563eb;color:#fff;border-radius:999px;font-size:12px;font-weight:700;font-family:inherit;box-shadow:0 0 14px rgba(37,99,235,0.5);">Live</span>`],
  ['dark', 'Dark', `<span style="display:inline-block;padding:5px 12px;background:#0f172a;color:#e2e8f0;border-radius:999px;font-size:12px;font-weight:700;font-family:inherit;">Enterprise</span>`],
]

const headings = [
  ['display', 'Display', `<h1 style="margin:0;font-size:52px;font-weight:800;line-height:1.05;font-family:inherit;color:#0f172a;">A bold display heading</h1>`],
  ['gradient', 'Gradient text', `<h1 style="margin:0;font-size:52px;font-weight:800;line-height:1.05;font-family:inherit;background:linear-gradient(90deg,#6366f1,#ec4899);-webkit-background-clip:text;background-clip:text;color:transparent;">Gradient headline</h1>`],
  ['eyebrow', 'Eyebrow + title', `<div style="font-family:inherit;"><div style="color:#2563eb;font-weight:700;font-size:14px;letter-spacing:1.5px;text-transform:uppercase;margin-bottom:8px;">Introducing</div><h2 style="margin:0;font-size:38px;font-weight:700;color:#0f172a;">Something worth your attention</h2></div>`],
  ['centered', 'Centered', `<h2 style="margin:0;font-size:40px;font-weight:700;text-align:center;font-family:inherit;color:#0f172a;">Centered section heading</h2>`],
]

const texts = [
  ['body', 'Body', `<p style="margin:0;font-size:17px;line-height:1.7;color:#475569;font-family:inherit;">A clear paragraph of body text that explains your idea without getting in the way.</p>`],
  ['lead', 'Lead', `<p style="margin:0;font-size:21px;line-height:1.6;color:#334155;font-family:inherit;">A larger lead paragraph that introduces the section with a little more weight.</p>`],
  ['muted', 'Muted small', `<p style="margin:0;font-size:14px;line-height:1.6;color:#94a3b8;font-family:inherit;">Smaller muted text for captions, notes and fine print.</p>`],
]

const images = [
  ['rounded', 'Rounded', `<img src="https://picsum.photos/seed/3/800/450" alt="" style="max-width:100%;height:auto;border-radius:14px;display:block;" />`],
  ['shadow', 'Shadow', `<img src="https://picsum.photos/seed/4/800/450" alt="" style="max-width:100%;height:auto;border-radius:14px;box-shadow:0 20px 45px rgba(0,0,0,0.2);display:block;" />`],
  ['circle', 'Avatar', `<img src="https://picsum.photos/seed/5/240/240" alt="" style="width:120px;height:120px;border-radius:999px;object-fit:cover;display:block;" />`],
  ['square-pp', 'Square photo', `<img src="https://picsum.photos/seed/5/240/240" alt="" style="width:120px;height:120px;border-radius:16px;object-fit:cover;display:block;" />`],
  ['ring', 'Ring avatar', `<img src="https://picsum.photos/seed/7/240/240" alt="" style="width:120px;height:120px;border-radius:999px;object-fit:cover;display:block;border:3px solid #fff;box-shadow:0 0 0 3px #6366f1;" />`],
  ['framed', 'Framed', `<img src="https://picsum.photos/seed/6/800/450" alt="" style="max-width:100%;height:auto;border-radius:14px;border:6px solid #fff;box-shadow:0 8px 24px rgba(0,0,0,0.12);display:block;" />`],
]

const quotes = [
  ['accent', 'Accent bar', `<blockquote style="margin:0;padding:14px 24px;border-left:4px solid #2563eb;background:#f8fafc;font-style:italic;color:#1e293b;font-size:18px;font-family:inherit;">"A great quote that builds trust with your visitors."</blockquote>`],
  ['large', 'Large', `<blockquote style="margin:0;font-size:28px;font-weight:600;line-height:1.4;color:#0f172a;font-family:inherit;">"The simplest solution is usually the best one."</blockquote>`],
  ['card', 'Quote card', `<div style="padding:26px;border-radius:16px;background:#fff;box-shadow:0 10px 26px rgba(0,0,0,0.08);font-family:inherit;max-width:420px;"><p style="margin:0 0 14px;font-size:18px;font-style:italic;color:#1e293b;line-height:1.5;">"This made our whole workflow click into place."</p><div style="font-weight:700;color:#0f172a;">Alex Morgan</div><div style="color:#64748b;font-size:14px;">Founder, Studio</div></div>`],
]

const lists = [
  ['check', 'Checklist', `<ul style="margin:0;padding:0;list-style:none;font-family:inherit;font-size:16px;line-height:2;color:#1e293b;"><li style="display:flex;gap:10px;"><span style="color:#22c55e;font-weight:700;">✓</span>First benefit goes here</li><li style="display:flex;gap:10px;"><span style="color:#22c55e;font-weight:700;">✓</span>Second benefit goes here</li><li style="display:flex;gap:10px;"><span style="color:#22c55e;font-weight:700;">✓</span>Third benefit goes here</li></ul>`],
  ['bulleted', 'Bulleted', `<ul style="margin:0;padding-left:20px;font-family:inherit;font-size:16px;line-height:1.9;color:#1e293b;"><li>First item</li><li>Second item</li><li>Third item</li></ul>`],
  ['numbered', 'Numbered', `<ol style="margin:0;padding-left:22px;font-family:inherit;font-size:16px;line-height:1.9;color:#1e293b;"><li>Step one</li><li>Step two</li><li>Step three</li></ol>`],
]

const inputs = [
  ['default', 'Field', `<label style="display:block;font-size:14px;font-weight:600;color:#1e293b;font-family:inherit;">Email<input type="email" placeholder="you@example.com" style="display:block;width:100%;padding:11px 14px;border:1px solid #cbd5e1;border-radius:10px;font-size:15px;margin-top:6px;box-sizing:border-box;" /></label>`],
  ['pill', 'Pill search', `<input type="search" placeholder="Search…" style="width:100%;padding:12px 20px;border:1px solid #e2e8f0;border-radius:999px;font-size:15px;font-family:inherit;box-sizing:border-box;" />`],
  ['inline', 'Inline + button', `<div style="display:flex;gap:8px;font-family:inherit;max-width:420px;"><input type="email" placeholder="Your email" style="flex:1;padding:12px 16px;border:1px solid #cbd5e1;border-radius:10px;font-size:15px;box-sizing:border-box;" /><a href="#" style="padding:12px 22px;background:#2563eb;color:#fff;border-radius:10px;text-decoration:none;font-weight:600;white-space:nowrap;">Subscribe</a></div>`],
  // Responsive fields: every control is width:100% + box-sizing:border-box and
  // capped with max-width, so it fills a narrow box and never overflows.
  ['icon-left', 'Icon field', `<div style="display:flex;align-items:center;gap:10px;width:100%;max-width:420px;padding:11px 16px;border:1px solid #cbd5e1;border-radius:10px;background:#fff;font-family:inherit;box-sizing:border-box;"><span aria-hidden="true" style="color:#94a3b8;">&#9906;</span><input type="search" placeholder="Search anything…" style="flex:1;min-width:0;border:0;outline:0;font-size:15px;background:transparent;" /></div>`],
  ['labeled', 'Labeled', `<label style="display:block;font-family:inherit;width:100%;max-width:420px;"><span style="display:block;font-size:14px;font-weight:600;color:#1e293b;margin-bottom:6px;">Full name</span><input type="text" placeholder="Jane Doe" style="display:block;width:100%;padding:12px 14px;border:1px solid #cbd5e1;border-radius:10px;font-size:15px;box-sizing:border-box;" /></label>`],
  ['textarea', 'Text area', `<label style="display:block;font-family:inherit;width:100%;max-width:480px;"><span style="display:block;font-size:14px;font-weight:600;color:#1e293b;margin-bottom:6px;">Message</span><textarea rows="4" placeholder="Write your message…" style="display:block;width:100%;padding:12px 14px;border:1px solid #cbd5e1;border-radius:10px;font-size:15px;font-family:inherit;box-sizing:border-box;resize:vertical;"></textarea></label>`],
  ['hint', 'With hint', `<label style="display:block;font-family:inherit;width:100%;max-width:420px;"><span style="display:block;font-size:14px;font-weight:600;color:#1e293b;margin-bottom:6px;">Password</span><input type="password" placeholder="••••••••" style="display:block;width:100%;padding:12px 14px;border:1px solid #cbd5e1;border-radius:10px;font-size:15px;box-sizing:border-box;" /><span style="display:block;margin-top:6px;font-size:12px;color:#94a3b8;">Use at least 8 characters.</span></label>`],
  ['prefix', 'Prefix group', `<div style="display:flex;width:100%;max-width:420px;font-family:inherit;box-sizing:border-box;"><span style="display:grid;place-items:center;padding:0 14px;background:#f1f5f9;border:1px solid #cbd5e1;border-right:0;border-radius:10px 0 0 10px;color:#64748b;font-size:15px;">@</span><input type="text" placeholder="username" style="flex:1;min-width:0;padding:12px 14px;border:1px solid #cbd5e1;border-radius:0 10px 10px 0;font-size:15px;box-sizing:border-box;" /></div>`],
  ['error', 'Error state', `<label style="display:block;font-family:inherit;width:100%;max-width:420px;"><span style="display:block;font-size:14px;font-weight:600;color:#1e293b;margin-bottom:6px;">Email</span><input type="email" value="bad-email" style="display:block;width:100%;padding:12px 14px;border:1.5px solid #ef4444;border-radius:10px;font-size:15px;box-sizing:border-box;background:#fef2f2;" /><span style="display:block;margin-top:6px;font-size:12px;color:#dc2626;">Please enter a valid email.</span></label>`],
  ['success', 'Success state', `<label style="display:block;font-family:inherit;width:100%;max-width:420px;"><span style="display:block;font-size:14px;font-weight:600;color:#1e293b;margin-bottom:6px;">Username</span><input type="text" value="available_name" style="display:block;width:100%;padding:12px 14px;border:1.5px solid #22c55e;border-radius:10px;font-size:15px;box-sizing:border-box;background:#f0fdf4;" /><span style="display:block;margin-top:6px;font-size:12px;color:#16a34a;">Looks good!</span></label>`],
  ['large-pill', 'Large pill', `<input type="text" placeholder="Enter your email to get started" style="width:100%;max-width:480px;padding:16px 24px;border:1px solid #e2e8f0;border-radius:999px;font-size:16px;font-family:inherit;box-sizing:border-box;box-shadow:0 4px 14px rgba(0,0,0,0.05);" />`],
]

const linkbuttons = [
  ['arrow', 'Arrow link', `<a href="#" style="display:inline-flex;align-items:center;gap:8px;color:#2563eb;text-decoration:none;font-weight:700;font-family:inherit;">Read more <span aria-hidden="true">&rarr;</span></a>`],
  ['underline', 'Underline', `<a href="#" style="display:inline-block;color:#111827;text-decoration:none;border-bottom:2px solid #111827;font-weight:700;font-family:inherit;padding-bottom:3px;">View project</a>`],
  ['pill', 'Small pill', `<a href="#" style="display:inline-flex;align-items:center;gap:8px;padding:8px 14px;border-radius:999px;background:#f1f5f9;color:#0f172a;text-decoration:none;font-weight:700;font-family:inherit;">Open link <span aria-hidden="true">&rarr;</span></a>`],
]

const selects = [
  ['default', 'Default', `<label style="display:block;font-size:14px;font-weight:700;color:#1e293b;font-family:inherit;">Plan<select style="display:block;width:100%;margin-top:6px;padding:11px 14px;border:1px solid #cbd5e1;border-radius:10px;background:#fff;color:#0f172a;font-size:15px;font-family:inherit;box-sizing:border-box;"><option>Starter</option><option>Pro</option><option>Team</option></select></label>`],
  ['soft', 'Soft', `<select style="width:100%;padding:12px 16px;border:1px solid #dbeafe;border-radius:12px;background:#eff6ff;color:#1d4ed8;font-size:15px;font-weight:600;font-family:inherit;box-sizing:border-box;"><option>Choose a category</option><option>Design</option><option>Development</option><option>Marketing</option></select>`],
  ['inline', 'Inline filter', `<div style="display:flex;align-items:center;gap:10px;font-family:inherit;"><span style="font-size:14px;font-weight:700;color:#475569;">Filter</span><select style="padding:9px 36px 9px 12px;border:1px solid #e2e8f0;border-radius:999px;background:#fff;color:#0f172a;font-size:14px;"><option>Newest</option><option>Popular</option><option>Featured</option></select></div>`],
]

const alerts = [
  ['info', 'Info', `<div style="display:flex;gap:10px;align-items:flex-start;padding:14px 16px;border-radius:12px;background:#eff6ff;color:#1e40af;border:1px solid #bfdbfe;font-family:inherit;"><strong style="font-size:14px;">Info</strong><span style="font-size:14px;line-height:1.5;">This is an informational message for visitors.</span></div>`],
  ['success', 'Success', `<div style="display:flex;gap:10px;align-items:flex-start;padding:14px 16px;border-radius:12px;background:#ecfdf5;color:#047857;border:1px solid #a7f3d0;font-family:inherit;"><strong style="font-size:14px;">Success</strong><span style="font-size:14px;line-height:1.5;">Everything is ready to go.</span></div>`],
  ['warning', 'Warning', `<div style="display:flex;gap:10px;align-items:flex-start;padding:14px 16px;border-radius:12px;background:#fffbeb;color:#92400e;border:1px solid #fde68a;font-family:inherit;"><strong style="font-size:14px;">Note</strong><span style="font-size:14px;line-height:1.5;">Add a short warning or reminder here.</span></div>`],
  ['dark', 'Dark', `<div style="padding:15px 18px;border-radius:14px;background:#111827;color:#e5e7eb;font-family:inherit;box-shadow:0 12px 30px rgba(15,23,42,0.22);"><strong style="display:block;margin-bottom:3px;color:#fff;">Announcement</strong><span style="font-size:14px;line-height:1.5;color:#cbd5e1;">A compact message with stronger visual weight.</span></div>`],
]

const accordions = [
  ['clean', 'Clean FAQ', `<div style="font-family:inherit;max-width:680px;display:grid;gap:10px;"><details style="border:1px solid #e5e7eb;border-radius:12px;background:#fff;padding:14px 16px;"><summary style="cursor:pointer;font-weight:700;color:#0f172a;">What is included?</summary><p style="margin:10px 0 0;color:#64748b;line-height:1.6;">Everything you need to describe the offer clearly.</p></details><details style="border:1px solid #e5e7eb;border-radius:12px;background:#fff;padding:14px 16px;"><summary style="cursor:pointer;font-weight:700;color:#0f172a;">Can I customize it?</summary><p style="margin:10px 0 0;color:#64748b;line-height:1.6;">Yes, change the text, spacing, colors and layout.</p></details></div>`],
  ['boxed', 'Boxed FAQ', `<div style="font-family:inherit;max-width:680px;"><details open style="margin-bottom:10px;border:1px solid #e2e8f0;border-radius:12px;background:#fff;padding:16px 18px;"><summary style="cursor:pointer;font-weight:700;color:#0f172a;">First question</summary><p style="margin:10px 0 0;color:#64748b;line-height:1.6;">A short answer that expands inside the card.</p></details><details style="border:1px solid #e2e8f0;border-radius:12px;background:#fff;padding:16px 18px;"><summary style="cursor:pointer;font-weight:700;color:#0f172a;">Second question</summary><p style="margin:10px 0 0;color:#64748b;line-height:1.6;">Another answer goes here.</p></details></div>`],
  ['dark', 'Dark FAQ', `<div style="font-family:inherit;max-width:680px;background:#0f172a;padding:16px;border-radius:16px;display:grid;gap:10px;"><details open style="border:1px solid rgba(255,255,255,0.14);border-radius:12px;padding:14px 16px;color:#fff;"><summary style="cursor:pointer;font-weight:700;">Why choose this?</summary><p style="margin:10px 0 0;color:#cbd5e1;line-height:1.6;">Because the answer is direct, compact and easy to scan.</p></details><details style="border:1px solid rgba(255,255,255,0.14);border-radius:12px;padding:14px 16px;color:#fff;"><summary style="cursor:pointer;font-weight:700;">How does it work?</summary><p style="margin:10px 0 0;color:#cbd5e1;line-height:1.6;">Write a useful answer here.</p></details></div>`],
]

const tabs = [
  ['simple', 'Simple tabs', `<div data-builder-tabs="tabs-simple" style="font-family:inherit;border:1px solid #e2e8f0;border-radius:14px;overflow:hidden;background:#fff;--builder-tab-bg:transparent;--builder-tab-color:#64748b;--builder-tab-active-bg:#fff;--builder-tab-active-color:#2563eb;--builder-tab-active-border:#2563eb;--builder-tab-padding:13px 16px;"><div role="tablist" style="display:flex;gap:0;background:#f8fafc;border-bottom:1px solid #e2e8f0;margin:0;"><button type="button" role="tab" data-builder-tab="overview" aria-selected="true" style="flex:1;font-weight:700;">Overview</button><button type="button" role="tab" data-builder-tab="details" aria-selected="false" style="flex:1;font-weight:600;">Details</button><button type="button" role="tab" data-builder-tab="faq" aria-selected="false" style="flex:1;font-weight:600;">FAQ</button></div><div role="tabpanel" data-builder-panel="overview" style="padding:20px;color:#475569;line-height:1.6;">Overview content goes here. Edit labels and panels after placing.</div><div role="tabpanel" data-builder-panel="details" hidden style="padding:20px;color:#475569;line-height:1.6;">Details content goes here.</div><div role="tabpanel" data-builder-panel="faq" hidden style="padding:20px;color:#475569;line-height:1.6;">FAQ content goes here.</div></div>`],
  ['pills', 'Pill tabs', `<div data-builder-tabs="tabs-pills" style="font-family:inherit;--builder-tab-bg:transparent;--builder-tab-color:#64748b;--builder-tab-active-bg:#2563eb;--builder-tab-active-color:#fff;--builder-tab-padding:9px 16px;--builder-tab-radius:999px;"><div role="tablist" style="display:inline-flex;gap:6px;padding:5px;border-radius:999px;background:#f1f5f9;border:0;margin:0;"><button type="button" role="tab" data-builder-tab="work" aria-selected="true" style="font-weight:700;">Work</button><button type="button" role="tab" data-builder-tab="about" aria-selected="false" style="font-weight:700;">About</button><button type="button" role="tab" data-builder-tab="contact" aria-selected="false" style="font-weight:700;">Contact</button></div><div role="tabpanel" data-builder-panel="work" style="margin:16px 0 0;color:#475569;line-height:1.6;">Use pill tabs for compact content switching.</div><div role="tabpanel" data-builder-panel="about" hidden style="margin:16px 0 0;color:#475569;line-height:1.6;">Add a short about panel here.</div><div role="tabpanel" data-builder-panel="contact" hidden style="margin:16px 0 0;color:#475569;line-height:1.6;">Add contact details or a call to action here.</div></div>`],
]

const containers = [
  ['dashed', 'Drop zone', `<div style="box-sizing:border-box;min-height:100%;padding:24px;border:2px dashed #cbd5e1;border-radius:14px;background:#f8fafc;color:#64748b;font-family:inherit;text-align:center;">Drop content here</div>`],
  ['surface', 'Surface', `<div style="box-sizing:border-box;min-height:100%;padding:24px;border:1px solid #e2e8f0;border-radius:14px;background:#fff;box-shadow:0 8px 22px rgba(15,23,42,0.07);font-family:inherit;"><h3 style="margin:0 0 8px;color:#0f172a;">Surface container</h3><p style="margin:0;color:#64748b;line-height:1.6;">Use this as a styled wrapper for grouped content.</p></div>`],
  ['glass', 'Glass panel', `<div style="box-sizing:border-box;min-height:100%;padding:24px;border:1px solid rgba(255,255,255,0.5);border-radius:16px;background:rgba(255,255,255,0.45);backdrop-filter:blur(12px);box-shadow:0 10px 28px rgba(15,23,42,0.1);font-family:inherit;"><h3 style="margin:0 0 8px;color:#0f172a;">Glass panel</h3><p style="margin:0;color:#475569;line-height:1.6;">A translucent wrapper for visual sections.</p></div>`],
]

const icons = [
  ['circle', 'Circle', `<span style="display:inline-grid;place-items:center;width:100%;height:100%;border-radius:999px;background:#eef2ff;color:#4f46e5;font-size:clamp(18px,38vmin,120px);font-weight:800;font-family:system-ui;">*</span>`],
  ['square', 'Square', `<span style="display:inline-grid;place-items:center;width:100%;height:100%;border-radius:14px;background:#0f172a;color:#fff;font-size:clamp(18px,38vmin,120px);font-weight:800;font-family:system-ui;">+</span>`],
  ['outline', 'Outline', `<span style="display:inline-grid;place-items:center;width:100%;height:100%;border-radius:14px;border:2px solid #2563eb;color:#2563eb;font-size:clamp(18px,38vmin,120px);font-weight:800;font-family:system-ui;">i</span>`],
  ['gradient', 'Gradient', `<span style="display:inline-grid;place-items:center;width:100%;height:100%;border-radius:16px;background:linear-gradient(135deg,#6366f1,#ec4899);color:#fff;font-size:clamp(18px,38vmin,120px);font-weight:800;font-family:system-ui;box-shadow:0 12px 28px rgba(99,102,241,0.3);">+</span>`],
]

const htmlEmbeds = [
  ['blank', 'Blank custom', `<div style="display:grid;place-items:center;min-height:140px;border:1px dashed #cbd5e1;border-radius:14px;background:#f8fafc;color:#64748b;font-family:inherit;">Paste custom HTML here</div>`],
  ['css-card', 'CSS card', `<style>.custom-card{padding:26px;border-radius:18px;background:linear-gradient(135deg,#111827,#312e81);color:white;font-family:system-ui;box-shadow:0 18px 45px rgba(49,46,129,.35)}.custom-card p{color:#c7d2fe;line-height:1.6}</style><div class="custom-card"><h3 style="margin:0 0 8px;">Custom CSS block</h3><p style="margin:0;">Edit the markup and styles from the properties panel.</p></div>`],
]

const spacers = [
  ['sm', 'Small gap', `<div style="height:24px;"></div>`],
  ['md', 'Medium gap', `<div style="height:56px;"></div>`],
  ['lg', 'Large gap', `<div style="height:96px;"></div>`],
]

const sections = [
  ['soft', 'Soft band', `<section style="padding:60px 32px;background:#f8fafc;text-align:center;font-family:inherit;"><h2 style="margin:0 0 12px;font-size:34px;color:#0f172a;">Section title</h2><p style="margin:0 auto;max-width:560px;color:#64748b;font-size:18px;line-height:1.6;">A short paragraph that introduces what this section is about.</p></section>`],
  ['gradient', 'Gradient', `<section style="padding:72px 32px;background:linear-gradient(135deg,#4f46e5,#9333ea);color:#fff;text-align:center;font-family:inherit;"><h2 style="margin:0 0 12px;font-size:36px;">A standout section</h2><p style="margin:0 auto;max-width:560px;color:rgba(255,255,255,0.85);font-size:18px;line-height:1.6;">Use a gradient band to break up the page and draw the eye.</p></section>`],
  ['split', 'Split', `<section style="display:flex;flex-wrap:wrap;gap:32px;align-items:center;padding:56px 32px;max-width:1080px;margin:0 auto;font-family:inherit;"><div style="flex:1;min-width:260px;"><h2 style="margin:0 0 12px;font-size:32px;color:#0f172a;">Tell your story</h2><p style="margin:0;color:#64748b;font-size:17px;line-height:1.7;">Text on one side, an image on the other — a classic, flexible layout.</p></div><img src="https://picsum.photos/seed/8/520/340" alt="" style="flex:1;min-width:260px;border-radius:14px;max-width:100%;" /></section>`],
]

const dividers = [
  ['line', 'Line', `<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0;" />`],
  ['dashed', 'Dashed', `<hr style="border:none;border-top:1px dashed #cbd5e1;margin:32px 0;" />`],
  ['dot', 'Centered dot', `<div style="display:flex;align-items:center;gap:14px;margin:32px 0;color:#cbd5e1;"><span style="flex:1;height:1px;background:#e2e8f0;"></span><span style="font-size:18px;">•</span><span style="flex:1;height:1px;background:#e2e8f0;"></span></div>`],
]

// Canonical Bootstrap markup with small inline fallbacks. The class names remain
// useful when a project later loads Bootstrap, while the editor/export still
// looks correct without making Bootstrap a runtime dependency of the builder.
const bootstrapVariants = {
  navbar: ['bootstrap', 'Bootstrap Navbar', `<nav class="navbar navbar-expand-lg bg-body-tertiary" style="display:flex;align-items:center;padding:12px 20px;background:#f8f9fa;color:#212529;border-bottom:1px solid #dee2e6;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;"><div class="container-fluid" style="display:flex;width:100%;align-items:center;justify-content:space-between;gap:20px;"><a class="navbar-brand" href="#" style="color:#212529;font-size:20px;font-weight:600;text-decoration:none;">Navbar</a><div class="navbar-nav" style="display:flex;align-items:center;gap:18px;"><a class="nav-link active" aria-current="page" href="#" style="color:#212529;text-decoration:none;">Home</a><a class="nav-link" href="#features" style="color:#495057;text-decoration:none;">Features</a><a class="nav-link" href="#pricing" style="color:#495057;text-decoration:none;">Pricing</a></div></div></nav>`, { foundation: 'bootstrap', recommended: true }],
  heading: ['bootstrap', 'Bootstrap Heading', `<h1 class="display-4" style="margin:0;color:#212529;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;font-size:clamp(2.5rem,5vw,3.5rem);font-weight:300;line-height:1.2;">Bootstrap heading</h1>`, { foundation: 'bootstrap', recommended: true }],
  text: ['bootstrap', 'Bootstrap Lead Text', `<p class="lead" style="margin:0;color:#212529;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;font-size:1.25rem;font-weight:300;line-height:1.5;">This is a lead paragraph. It stands out from regular body text.</p>`, { foundation: 'bootstrap', recommended: true }],
  button: ['bootstrap', 'Bootstrap Button', `<button type="button" class="btn btn-primary" style="display:inline-block;padding:.5rem 1rem;border:1px solid #0d6efd;border-radius:.375rem;background:#0d6efd;color:#fff;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;font-size:1rem;font-weight:400;line-height:1.5;text-align:center;cursor:pointer;">Primary</button>`, { foundation: 'bootstrap', recommended: true }],
  linkbutton: ['bootstrap', 'Bootstrap Link Button', `<a href="#" class="btn btn-link" role="button" style="display:inline-block;padding:.5rem 1rem;border-radius:.375rem;color:#0d6efd;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;font-size:1rem;line-height:1.5;text-align:center;text-decoration:underline;">Link button</a>`, { foundation: 'bootstrap', recommended: true }],
  image: ['bootstrap', 'Bootstrap Image', `<img class="img-fluid rounded" src="https://picsum.photos/seed/bootstrap/800/450" alt="Responsive example" style="display:block;max-width:100%;height:auto;border-radius:.375rem;" />`, { foundation: 'bootstrap', recommended: true }],
  section: ['bootstrap', 'Bootstrap Section', `<section class="container py-5" style="box-sizing:border-box;width:100%;max-width:1140px;margin:0 auto;padding:3rem 1.5rem;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;"><h2 style="margin:0 0 .75rem;color:#212529;font-size:2rem;">Section title</h2><p style="margin:0;color:#6c757d;font-size:1rem;line-height:1.5;">A responsive Bootstrap-style content section.</p></section>`, { foundation: 'bootstrap', recommended: true }],
  card: ['bootstrap', 'Bootstrap Card', `<div class="card" style="max-width:320px;border:1px solid rgba(0,0,0,.175);border-radius:.375rem;background:#fff;color:#212529;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;overflow:hidden;"><img class="card-img-top" src="https://picsum.photos/seed/bootstrap-card/640/320" alt="" style="display:block;width:100%;height:150px;object-fit:cover;"><div class="card-body" style="padding:1rem;"><h5 class="card-title" style="margin:0 0 .5rem;font-size:1.25rem;">Card title</h5><p class="card-text" style="margin:0 0 1rem;line-height:1.5;">Supporting text for the Bootstrap card.</p><a href="#" class="btn btn-primary" style="display:inline-block;padding:.375rem .75rem;border-radius:.375rem;background:#0d6efd;color:#fff;text-decoration:none;">Go somewhere</a></div></div>`, { foundation: 'bootstrap', recommended: true }],
  list: ['bootstrap', 'Bootstrap List Group', `<div class="list-group" style="display:flex;max-width:420px;flex-direction:column;border-radius:.375rem;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;overflow:hidden;"><a href="#" class="list-group-item list-group-item-action active" aria-current="true" style="padding:.75rem 1rem;border:1px solid #0d6efd;background:#0d6efd;color:#fff;text-decoration:none;">Active item</a><a href="#" class="list-group-item list-group-item-action" style="padding:.75rem 1rem;border:1px solid rgba(0,0,0,.125);border-top:0;background:#fff;color:#212529;text-decoration:none;">Second item</a><a href="#" class="list-group-item list-group-item-action" style="padding:.75rem 1rem;border:1px solid rgba(0,0,0,.125);border-top:0;background:#fff;color:#212529;text-decoration:none;">Third item</a></div>`, { foundation: 'bootstrap', recommended: true }],
  quote: ['bootstrap', 'Bootstrap Blockquote', `<figure style="margin:0;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;"><blockquote class="blockquote" style="margin:0 0 1rem;color:#212529;font-size:1.25rem;"><p style="margin:0;">A well-known quote contained in a blockquote element.</p></blockquote><figcaption class="blockquote-footer" style="color:#6c757d;font-size:.875rem;">Someone famous in <cite title="Source Title">Source Title</cite></figcaption></figure>`, { foundation: 'bootstrap', recommended: true }],
  badge: ['bootstrap', 'Bootstrap Badge', `<span class="badge text-bg-primary" style="display:inline-block;padding:.35em .65em;border-radius:.375rem;background:#0d6efd;color:#fff;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;font-size:.75em;font-weight:700;line-height:1;">New</span>`, { foundation: 'bootstrap', recommended: true }],
  input: ['bootstrap', 'Bootstrap Form Control', `<div style="font-family:system-ui,-apple-system,'Segoe UI',sans-serif;"><label for="bootstrap-email" class="form-label" style="display:block;margin-bottom:.5rem;color:#212529;">Email address</label><input id="bootstrap-email" type="email" class="form-control" placeholder="name@example.com" style="display:block;box-sizing:border-box;width:100%;padding:.375rem .75rem;border:1px solid #ced4da;border-radius:.375rem;background:#fff;color:#212529;font-size:1rem;line-height:1.5;" /></div>`, { foundation: 'bootstrap', recommended: true }],
  select: ['bootstrap', 'Bootstrap Select', `<div style="font-family:system-ui,-apple-system,'Segoe UI',sans-serif;"><label for="bootstrap-select" class="form-label" style="display:block;margin-bottom:.5rem;color:#212529;">Choose an option</label><select id="bootstrap-select" class="form-select" style="display:block;box-sizing:border-box;width:100%;padding:.375rem 2.25rem .375rem .75rem;border:1px solid #ced4da;border-radius:.375rem;background:#fff;color:#212529;font-size:1rem;line-height:1.5;"><option selected>Open this menu</option><option>One</option><option>Two</option><option>Three</option></select></div>`, { foundation: 'bootstrap', recommended: true }],
  alert: ['bootstrap', 'Bootstrap Alert', `<div class="alert alert-primary" role="alert" style="padding:1rem;border:1px solid #b6d4fe;border-radius:.375rem;background:#cfe2ff;color:#084298;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;line-height:1.5;">A simple primary alert—check it out!</div>`, { foundation: 'bootstrap', recommended: true }],
  accordion: ['bootstrap', 'Bootstrap Accordion', `<div class="accordion" style="max-width:680px;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;"><details class="accordion-item" open style="border:1px solid rgba(0,0,0,.125);background:#fff;"><summary class="accordion-button" style="padding:1rem 1.25rem;color:#052c65;background:#cfe2ff;font-weight:500;cursor:pointer;">Accordion Item #1</summary><div class="accordion-body" style="padding:1rem 1.25rem;color:#212529;line-height:1.5;">This item uses Bootstrap's accordion structure and remains usable without extra JavaScript.</div></details><details class="accordion-item" style="border:1px solid rgba(0,0,0,.125);border-top:0;background:#fff;"><summary class="accordion-button collapsed" style="padding:1rem 1.25rem;color:#212529;font-weight:500;cursor:pointer;">Accordion Item #2</summary><div class="accordion-body" style="padding:1rem 1.25rem;color:#212529;line-height:1.5;">Add another answer here.</div></details></div>`, { foundation: 'bootstrap', recommended: true }],
  container: ['bootstrap', 'Bootstrap Container', `<div class="container" style="box-sizing:border-box;width:100%;max-width:1140px;min-height:140px;margin:0 auto;padding:1.5rem;border:1px solid #dee2e6;border-radius:.375rem;background:#fff;color:#212529;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;"><h3 style="margin:0 0 .5rem;">Responsive container</h3><p style="margin:0;color:#6c757d;line-height:1.5;">Place grouped content inside this Bootstrap container.</p></div>`, { foundation: 'bootstrap', recommended: true }],
  tabs: ['bootstrap', 'Bootstrap Tabs', `<div data-builder-tabs="tabs-bootstrap" style="font-family:system-ui,-apple-system,'Segoe UI',sans-serif;--builder-tab-bg:transparent;--builder-tab-color:#495057;--builder-tab-active-bg:#fff;--builder-tab-active-color:#495057;--builder-tab-active-border:#dee2e6;--builder-tab-padding:.5rem 1rem;--builder-tab-radius:.375rem .375rem 0 0;"><div class="nav nav-tabs" role="tablist" style="display:flex;gap:0;border-bottom:1px solid #dee2e6;"><button type="button" class="nav-link active" role="tab" data-builder-tab="home" aria-selected="true">Home</button><button type="button" class="nav-link" role="tab" data-builder-tab="profile" aria-selected="false">Profile</button><button type="button" class="nav-link" role="tab" data-builder-tab="contact" aria-selected="false">Contact</button></div><div class="tab-content" style="padding:1rem 0;"><div class="tab-pane active" role="tabpanel" data-builder-panel="home">Home tab content.</div><div class="tab-pane" role="tabpanel" data-builder-panel="profile" hidden>Profile tab content.</div><div class="tab-pane" role="tabpanel" data-builder-panel="contact" hidden>Contact tab content.</div></div></div>`, { foundation: 'bootstrap', recommended: true }],
  divider: ['bootstrap', 'Bootstrap Divider', `<hr class="border border-secondary border-1 opacity-25" style="margin:1rem 0;border:0;border-top:1px solid #6c757d;opacity:.25;" />`, { foundation: 'bootstrap', recommended: true }],
  spacer: ['bootstrap', 'Bootstrap Spacing', `<div class="py-4" aria-hidden="true" style="box-sizing:border-box;height:48px;"></div>`, { foundation: 'bootstrap', recommended: true }],
}

function toEntries(list) {
  return list.map(([id, label, html, metadata = {}]) => ({ id, label, html, ...metadata }))
}

function withBootstrap(type, list) {
  const recommended = bootstrapVariants[type]
  return toEntries(recommended ? [recommended, ...list] : list)
}

export const HTML_VARIANTS = {
  button: withBootstrap('button', buttons),
  linkbutton: withBootstrap('linkbutton', linkbuttons),
  navbar: withBootstrap('navbar', navbars),
  card: withBootstrap('card', cards),
  badge: withBootstrap('badge', badges),
  heading: withBootstrap('heading', headings),
  text: withBootstrap('text', texts),
  image: withBootstrap('image', images),
  quote: withBootstrap('quote', quotes),
  list: withBootstrap('list', lists),
  input: withBootstrap('input', inputs),
  select: withBootstrap('select', selects),
  alert: withBootstrap('alert', alerts),
  accordion: withBootstrap('accordion', accordions),
  tabs: withBootstrap('tabs', tabs),
  container: withBootstrap('container', containers),
  icon: toEntries(icons),
  html: toEntries(htmlEmbeds),
  spacer: withBootstrap('spacer', spacers),
  section: withBootstrap('section', sections),
  divider: withBootstrap('divider', dividers),
}

export function htmlVariantsFor(type) {
  return HTML_VARIANTS[type] || []
}

// ---- Ready-made section BLOCKS (HTML) ----------------------------------------

const hero = `<section style="padding:80px 32px;text-align:center;font-family:inherit;"><h1 style="margin:0 0 16px;font-size:54px;font-weight:800;line-height:1.05;color:#0f172a;">Welcome to my site</h1><p style="margin:0 auto 28px;max-width:600px;font-size:20px;color:#64748b;line-height:1.5;">A clear one-liner about what you do and why it matters to the people you want to reach.</p><div style="display:flex;gap:12px;justify-content:center;flex-wrap:wrap;"><a href="#" style="padding:13px 28px;background:linear-gradient(90deg,#6366f1,#a855f7);color:#fff;border-radius:10px;text-decoration:none;font-weight:600;">Get started</a><a href="#" style="padding:13px 28px;background:#eef2ff;color:#4338ca;border-radius:10px;text-decoration:none;font-weight:600;">Learn more</a></div></section>`

const features = `<section style="padding:64px 32px;max-width:1080px;margin:0 auto;font-family:inherit;"><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:28px;text-align:center;">${[['⚡', 'Fast', 'Built for speed so visitors never wait.'], ['🧩', 'Flexible', 'Mix blocks to build exactly what you need.'], ['🔒', 'Yours', 'Every color and word is under your control.']].map(([i, h, p]) => `<div><div style="width:52px;height:52px;border-radius:14px;background:#eef2ff;color:#4f46e5;display:grid;place-items:center;font-size:24px;margin:0 auto 14px;">${i}</div><h3 style="margin:0 0 6px;font-size:19px;color:#0f172a;">${h}</h3><p style="margin:0;color:#64748b;line-height:1.6;">${p}</p></div>`).join('')}</div></section>`

const pricing = `<section style="padding:64px 32px;max-width:1000px;margin:0 auto;font-family:inherit;"><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:22px;">${[['Starter', '$0', false], ['Pro', '$12/mo', true], ['Team', '$29/mo', false]].map(([n, pr, hot]) => `<div style="padding:28px;border-radius:16px;background:#fff;border:${hot ? '2px solid #6366f1' : '1px solid #e2e8f0'};box-shadow:${hot ? '0 16px 40px rgba(99,102,241,0.2)' : 'none'};text-align:center;"><h3 style="margin:0 0 4px;font-size:18px;color:#0f172a;">${n}</h3><div style="font-size:36px;font-weight:800;color:#0f172a;margin-bottom:14px;">${pr}</div><a href="#" style="display:block;padding:11px;border-radius:10px;text-decoration:none;font-weight:600;background:${hot ? 'linear-gradient(90deg,#6366f1,#a855f7)' : '#eef2ff'};color:${hot ? '#fff' : '#4338ca'};">Choose plan</a></div>`).join('')}</div></section>`

const cta = `<section style="padding:64px 32px;background:linear-gradient(135deg,#4f46e5,#9333ea);text-align:center;font-family:inherit;"><h2 style="margin:0 0 18px;font-size:34px;color:#fff;">Ready to get started?</h2><a href="#" style="padding:14px 30px;background:#fff;color:#4f46e5;border-radius:10px;text-decoration:none;font-weight:700;">Contact me</a></section>`

const stats = `<section style="padding:56px 32px;max-width:980px;margin:0 auto;font-family:inherit;"><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:20px;text-align:center;">${[['120+', 'Projects'], ['8 yrs', 'Experience'], ['99%', 'Happy clients'], ['24/7', 'Support']].map(([n, l]) => `<div><div style="font-size:40px;font-weight:800;color:#2563eb;">${n}</div><div style="color:#64748b;font-size:15px;">${l}</div></div>`).join('')}</div></section>`

const testimonial = `<section style="padding:64px 32px;text-align:center;font-family:inherit;max-width:760px;margin:0 auto;"><p style="margin:0 0 16px;font-size:24px;font-style:italic;color:#1e293b;line-height:1.5;">"Working with them was the best decision I made this year. Clear, fast and genuinely creative."</p><div style="font-weight:700;color:#0f172a;">Alex Morgan</div><div style="color:#64748b;">Founder, Studio</div></section>`

const footer = `<footer style="padding:40px 32px;background:#0f172a;color:#cbd5e1;font-family:inherit;"><div style="max-width:1000px;margin:0 auto;display:flex;flex-wrap:wrap;gap:20px;justify-content:space-between;align-items:center;"><span style="font-weight:800;color:#fff;font-size:18px;">Brand</span><div style="display:flex;gap:20px;font-size:14px;"><a href="#" style="color:#cbd5e1;text-decoration:none;">About</a><a href="#" style="color:#cbd5e1;text-decoration:none;">Work</a><a href="#" style="color:#cbd5e1;text-decoration:none;">Contact</a></div><span style="font-size:13px;color:#64748b;">© 2026 Brand</span></div></footer>`

const heroSplit = `<section style="display:flex;flex-wrap:wrap;align-items:center;gap:40px;padding:64px 32px;max-width:1080px;margin:0 auto;font-family:inherit;"><div style="flex:1;min-width:280px;"><h1 style="margin:0 0 16px;font-size:46px;font-weight:800;line-height:1.1;color:#0f172a;">Build it your way</h1><p style="margin:0 0 24px;font-size:19px;color:#64748b;line-height:1.6;">A split hero with the message on one side and a visual on the other.</p><a href="#" style="padding:13px 28px;background:#2563eb;color:#fff;border-radius:10px;text-decoration:none;font-weight:600;">Get started</a></div><img src="https://picsum.photos/seed/20/640/440" alt="" style="flex:1;min-width:280px;border-radius:18px;max-width:100%;box-shadow:0 20px 50px rgba(0,0,0,0.15);" /></section>`

const faq = `<section style="padding:64px 32px;max-width:760px;margin:0 auto;font-family:inherit;"><h2 style="margin:0 0 24px;font-size:32px;text-align:center;color:#0f172a;">Frequently asked questions</h2><div style="display:grid;gap:10px;">${[['Is there a free plan?', 'Yes — start for free and upgrade whenever you are ready.'], ['Can I cancel anytime?', 'Absolutely, no contracts and no hidden fees.'], ['Do you offer support?', 'Friendly humans are available whenever you get stuck.']].map(([q, a]) => `<details style="border:1px solid #e5e7eb;border-radius:12px;background:#fff;padding:14px 16px;"><summary style="cursor:pointer;font-weight:600;font-size:17px;color:#0f172a;">${q}</summary><p style="margin:10px 0 0;color:#64748b;line-height:1.6;">${a}</p></details>`).join('')}</div></section>`

const logos = `<section style="padding:48px 32px;text-align:center;font-family:inherit;"><p style="margin:0 0 22px;font-size:13px;letter-spacing:1.5px;text-transform:uppercase;color:#94a3b8;font-weight:600;">Trusted by teams at</p><div style="display:flex;flex-wrap:wrap;gap:40px;justify-content:center;align-items:center;opacity:0.6;font-weight:800;font-size:22px;color:#475569;">${['Acme', 'Globex', 'Umbra', 'Soylent', 'Initech'].map((n) => `<span>${n}</span>`).join('')}</div></section>`

const contact = `<section style="padding:64px 32px;max-width:560px;margin:0 auto;font-family:inherit;"><h2 style="margin:0 0 8px;font-size:32px;text-align:center;color:#0f172a;">Get in touch</h2><p style="margin:0 0 28px;text-align:center;color:#64748b;">We usually reply within a day.</p><div style="display:flex;flex-direction:column;gap:14px;"><input placeholder="Your name" style="padding:13px 16px;border:1px solid #cbd5e1;border-radius:10px;font-size:15px;font-family:inherit;" /><input placeholder="Email" style="padding:13px 16px;border:1px solid #cbd5e1;border-radius:10px;font-size:15px;font-family:inherit;" /><textarea placeholder="Message" rows="4" style="padding:13px 16px;border:1px solid #cbd5e1;border-radius:10px;font-size:15px;font-family:inherit;resize:vertical;"></textarea><a href="#" style="padding:14px;background:#2563eb;color:#fff;border-radius:10px;text-decoration:none;font-weight:600;text-align:center;">Send message</a></div></section>`

const about = `<section style="padding:72px 32px;max-width:1080px;margin:0 auto;font-family:inherit;"><div style="display:grid;grid-template-columns:minmax(260px,0.9fr) minmax(280px,1.1fr);gap:46px;align-items:center;"><div style="aspect-ratio:1/1;border-radius:24px;background:linear-gradient(135deg,#dbeafe,#818cf8);box-shadow:0 24px 60px rgba(79,70,229,0.18);"></div><div><p style="margin:0 0 10px;color:#2563eb;font-weight:800;letter-spacing:1.2px;text-transform:uppercase;font-size:13px;">About</p><h2 style="margin:0 0 14px;font-size:38px;color:#0f172a;line-height:1.1;">A short story with a clear point of view.</h2><p style="margin:0;color:#64748b;font-size:18px;line-height:1.7;">Use this section to explain who you are, what you make, and why visitors should trust you.</p></div></div></section>`

const services = `<section style="padding:72px 32px;background:#f8fafc;font-family:inherit;"><div style="max-width:1080px;margin:0 auto;"><p style="margin:0 0 10px;color:#2563eb;font-weight:800;letter-spacing:1.2px;text-transform:uppercase;font-size:13px;">Services</p><h2 style="margin:0 0 28px;font-size:38px;color:#0f172a;">What I can help with</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px;">${[['Strategy', 'Clarify goals and shape the right plan.'], ['Design', 'Turn the idea into a polished visual system.'], ['Build', 'Ship responsive pages that feel fast and clean.'], ['Improve', 'Iterate with real feedback and measurable outcomes.']].map(([h, p]) => `<div style="padding:22px;border-radius:16px;background:#fff;border:1px solid #e2e8f0;"><h3 style="margin:0 0 8px;color:#0f172a;font-size:18px;">${h}</h3><p style="margin:0;color:#64748b;line-height:1.6;">${p}</p></div>`).join('')}</div></div></section>`

const process = `<section style="padding:72px 32px;max-width:960px;margin:0 auto;font-family:inherit;"><p style="margin:0 0 10px;color:#2563eb;font-weight:800;letter-spacing:1.2px;text-transform:uppercase;font-size:13px;text-align:center;">Process</p><h2 style="margin:0 0 34px;font-size:38px;color:#0f172a;text-align:center;">From idea to launch</h2><div style="display:grid;gap:18px;">${[['01', 'Discover', 'Define audience, goals and content priorities.'], ['02', 'Design', 'Build the visual direction and responsive structure.'], ['03', 'Launch', 'Polish, publish and keep improving after release.']].map(([n, h, p]) => `<div style="display:grid;grid-template-columns:70px 1fr;gap:18px;align-items:start;padding:22px;border-radius:16px;border:1px solid #e2e8f0;background:#fff;"><div style="font-size:28px;font-weight:900;color:#2563eb;">${n}</div><div><h3 style="margin:0 0 6px;color:#0f172a;font-size:20px;">${h}</h3><p style="margin:0;color:#64748b;line-height:1.6;">${p}</p></div></div>`).join('')}</div></section>`

const team = `<section style="padding:72px 32px;background:#f8fafc;font-family:inherit;"><div style="max-width:1080px;margin:0 auto;text-align:center;"><p style="margin:0 0 10px;color:#2563eb;font-weight:800;letter-spacing:1.2px;text-transform:uppercase;font-size:13px;">Team</p><h2 style="margin:0 0 34px;font-size:38px;color:#0f172a;">People behind the work</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:20px;">${['Avery Stone', 'Mina Park', 'Leo Carter', 'Nora Wells'].map((n, i) => `<div style="padding:22px;border-radius:18px;background:#fff;border:1px solid #e2e8f0;"><div style="width:78px;height:78px;border-radius:999px;background:linear-gradient(${120 + i * 30}deg,#93c5fd,#c084fc);margin:0 auto 14px;"></div><h3 style="margin:0 0 4px;color:#0f172a;font-size:18px;">${n}</h3><p style="margin:0;color:#64748b;font-size:14px;">Creative partner</p></div>`).join('')}</div></div></section>`

const gallery = `<section style="padding:72px 32px;max-width:1120px;margin:0 auto;font-family:inherit;"><p style="margin:0 0 10px;color:#2563eb;font-weight:800;letter-spacing:1.2px;text-transform:uppercase;font-size:13px;">Gallery</p><h2 style="margin:0 0 28px;font-size:38px;color:#0f172a;">A visual sample wall</h2><div style="columns:3 230px;column-gap:18px;">${[1,2,3,4,5,6,7,8].map((n) => `<div style="break-inside:avoid;margin-bottom:18px;aspect-ratio:${n % 3 === 0 ? '4/5' : n % 2 === 0 ? '1/1' : '4/3'};border-radius:18px;background:linear-gradient(${90 + n * 28}deg,#dbeafe,#6366f1);"></div>`).join('')}</div></section>`

const portfolio = `<section style="padding:72px 32px;background:#f8fafc;font-family:inherit;"><div style="max-width:1120px;margin:0 auto;"><p style="margin:0 0 10px;color:#2563eb;font-weight:800;letter-spacing:1.2px;text-transform:uppercase;font-size:13px;">Work</p><h2 style="margin:0 0 28px;font-size:38px;color:#0f172a;">Selected projects</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:22px;">${['Brand refresh', 'Product launch', 'Editorial site', 'Design system'].map((h, i) => `<article style="overflow:hidden;border-radius:18px;background:#fff;border:1px solid #e2e8f0;box-shadow:0 12px 28px rgba(15,23,42,0.06);"><div style="aspect-ratio:16/10;background:linear-gradient(${120 + i * 35}deg,#bfdbfe,#7c3aed);"></div><div style="padding:20px;"><span style="font-size:12px;font-weight:800;color:#2563eb;text-transform:uppercase;letter-spacing:1px;">Case study</span><h3 style="margin:8px 0 6px;color:#0f172a;font-size:20px;">${h}</h3><p style="margin:0;color:#64748b;line-height:1.6;">A short result-focused description goes here.</p></div></article>`).join('')}</div></div></section>`

const newsletter = `<section style="padding:72px 32px;font-family:inherit;"><div style="max-width:760px;margin:0 auto;text-align:center;padding:42px 28px;border-radius:24px;background:#0f172a;color:#fff;"><p style="margin:0 0 10px;color:#93c5fd;font-weight:800;letter-spacing:1.2px;text-transform:uppercase;font-size:13px;">Newsletter</p><h2 style="margin:0 0 12px;font-size:36px;line-height:1.1;">Get the next update.</h2><p style="margin:0 auto 24px;max-width:520px;color:#cbd5e1;line-height:1.6;">A short promise about what subscribers will receive.</p><div style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap;"><input type="email" placeholder="Email address" style="min-width:240px;padding:13px 16px;border:1px solid rgba(255,255,255,0.18);border-radius:12px;background:rgba(255,255,255,0.08);color:#fff;font-size:15px;" /><a href="#" style="padding:13px 22px;border-radius:12px;background:#fff;color:#0f172a;text-decoration:none;font-weight:800;">Subscribe</a></div></div></section>`

const blogPosts = `<section style="padding:72px 32px;max-width:1080px;margin:0 auto;font-family:inherit;"><p style="margin:0 0 10px;color:#2563eb;font-weight:800;letter-spacing:1.2px;text-transform:uppercase;font-size:13px;">Articles</p><h2 style="margin:0 0 28px;font-size:38px;color:#0f172a;">Latest writing</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px;">${[['Design', 'Designing for clarity'], ['Build', 'Small systems that scale'], ['Notes', 'What changed this month']].map(([tag, h]) => `<article style="padding:24px;border-radius:18px;background:#fff;border:1px solid #e2e8f0;"><span style="display:inline-block;margin-bottom:14px;padding:4px 10px;border-radius:999px;background:#eef2ff;color:#4338ca;font-size:12px;font-weight:800;">${tag}</span><h3 style="margin:0 0 8px;color:#0f172a;font-size:21px;">${h}</h3><p style="margin:0;color:#64748b;line-height:1.6;">A concise excerpt that makes people want to read more.</p></article>`).join('')}</div></section>`

const video = `<section style="padding:72px 32px;background:#0f172a;color:#fff;font-family:inherit;"><div style="max-width:1000px;margin:0 auto;text-align:center;"><p style="margin:0 0 10px;color:#93c5fd;font-weight:800;letter-spacing:1.2px;text-transform:uppercase;font-size:13px;">Watch</p><h2 style="margin:0 0 24px;font-size:38px;">Show the product in motion</h2><div style="aspect-ratio:16/9;border-radius:22px;background:linear-gradient(135deg,#1e293b,#4338ca);display:grid;place-items:center;box-shadow:0 28px 70px rgba(0,0,0,0.35);"><span style="display:grid;place-items:center;width:74px;height:74px;border-radius:999px;background:#fff;color:#0f172a;font-size:22px;font-weight:900;">Play</span></div></div></section>`

// The original section blocks, filed into the section library's categories.
const CORE_BLOCKS = [
  { id: 'hero', category: 'hero', label: 'Hero', desc: 'Headline, subtitle & buttons', html: hero },
  { id: 'hero-split', category: 'hero', label: 'Split hero', desc: 'Text + image side by side', html: heroSplit },
  { id: 'about', category: 'about', label: 'About', desc: 'Story + visual block', html: about },
  { id: 'features', category: 'features', label: 'Features', desc: '3-column feature row', html: features },
  { id: 'services', category: 'services', label: 'Services', desc: '4 service cards', html: services },
  { id: 'process', category: 'process', label: 'Process', desc: 'Step-by-step timeline', html: process },
  { id: 'stats', category: 'stats', label: 'Stats', desc: 'Row of key numbers', html: stats },
  { id: 'pricing', category: 'pricing', label: 'Pricing', desc: '3 pricing cards', html: pricing },
  { id: 'portfolio', category: 'portfolio', label: 'Portfolio', desc: 'Project grid', html: portfolio },
  { id: 'gallery', category: 'portfolio', label: 'Gallery', desc: 'Masonry image wall', html: gallery },
  { id: 'team', category: 'team', label: 'Team', desc: 'People cards', html: team },
  { id: 'logos', category: 'logos', label: 'Logo cloud', desc: 'Trusted-by logos', html: logos },
  { id: 'testimonial', category: 'testimonials', label: 'Testimonial', desc: 'Quote + author', html: testimonial },
  { id: 'blog', category: 'blog', label: 'Blog posts', desc: 'Article cards', html: blogPosts },
  { id: 'faq', category: 'faq', label: 'FAQ', desc: 'Expandable questions', html: faq },
  { id: 'newsletter', category: 'newsletter', label: 'Newsletter', desc: 'Email signup', html: newsletter },
  { id: 'video', category: 'media', label: 'Video', desc: 'Media feature block', html: video },
  { id: 'contact', category: 'contact', label: 'Contact', desc: 'Contact form', html: contact },
  { id: 'cta', category: 'cta', label: 'Call to action', desc: 'Gradient banner', html: cta },
  { id: 'footer', category: 'footer', label: 'Footer', desc: 'Links + copyright', html: footer },
]

// Every ready-made section: the originals first, then the section library
// (sectionBlocks/), whose entries also carry a Turkish build (`htmlTr`) and
// their natural `size` on a 1000px canvas.
export const HTML_BLOCKS = [...CORE_BLOCKS, ...SECTION_BLOCKS]
