import { VERTICAL_TEMPLATE_TRANSLATIONS } from './templateCatalogData.js'

const TEMPLATE_TEXT_TR = {
  Home: 'Ana Sayfa',
  About: 'Hakkında',
  Elsewhere: 'Diğer bağlantılar',
  Work: 'Çalışmalar',
  Services: 'Hizmetler',
  Menu: 'Menü',
  Visit: 'Ziyaret',
  Product: 'Ürün',
  Features: 'Özellikler',
  Gallery: 'Galeri',
  Subscribe: 'Abone ol',
  Schedule: 'Program',
  RSVP: 'Katılım bildir',
  Shop: 'Mağaza',
  Experience: 'Deneyim',
  Skills: 'Beceriler',
  Pricing: 'Fiyatlandırma',
  Reviews: 'Yorumlar',
  Articles: 'Yazılar',
  Venue: 'Mekân',
  Booking: 'Rezervasyon',
  'Our story': 'Hikâyemiz',
  'Work with me': 'Birlikte çalışalım',
  'Get in touch': 'İletişime geçin',
  'Start free': 'Ücretsiz başla',
  Download: 'İndir',
  'Get a quote': 'Teklif alın',
  'Start a project': 'Projeyi başlat',
  'See results': 'Sonuçları görün',
  'What we do': 'Neler yapıyoruz',
  'Case studies': 'Vaka çalışmaları',
  'Recent results': 'Son sonuçlar',
  'Tell us about your project': 'Projenizi bize anlatın',
  'See the menu': 'Menüyü görün',
  'What we serve': 'Neler sunuyoruz',
  Breakfast: 'Kahvaltı',
  Lunch: 'Öğle yemeği',
  'Coffee & more': 'Kahve ve daha fazlası',
  'Hours & location': 'Saatler ve konum',
  'Open in Maps': 'Haritada aç',
  'Private events & catering': 'Özel etkinlikler ve catering',
  'Ask about dates': 'Tarihleri sorun',
  'Book a shoot': 'Çekim ayırtın',
  'View gallery': 'Galeriyi görün',
  'Check dates': 'Tarihleri kontrol edin',
  'Recent frames': 'Son kareler',
  'Check availability': 'Uygunluğu kontrol edin',
  'Notes from the workshop.': 'Atölyeden notlar.',
  Engineering: 'Mühendislik',
  Design: 'Tasarım',
  Writing: 'Yazı',
  'One essay a month': 'Ayda bir yazı',
  'Subscribe by email': 'E-posta ile abone olun',
  'See the schedule': 'Programı görün',
  'The day': 'Günün programı',
  'Guests arrive': 'Misafirlerin gelişi',
  Ceremony: 'Tören',
  Dinner: 'Akşam yemeği',
  Party: 'Kutlama',
  Where: 'Nerede',
  'The venue': 'Mekân',
  'Will you join us?': 'Bize katılacak mısınız?',
  'RSVP by email': 'E-posta ile katılım bildirin',
  'Shop now': 'Şimdi alışveriş yap',
  'Browse the shop': 'Mağazayı gezin',
  Bestsellers: 'Çok satanlar',
  'Why small batches': 'Neden küçük üretim?',
  'Questions about an order?': 'Sipariş hakkında sorunuz mu var?',
  'Built with care.': 'Özenle hazırlandı.',
  'All rights reserved.': 'Tüm hakları saklıdır.',
  Profile: 'Profil',
  Education: 'Eğitim',
  Contact: 'İletişim',
  Career: 'Kariyer',
  Toolkit: 'Araçlar',
  'Senior Product Designer': 'Kıdemli Ürün Tasarımcısı',
  'Product Designer': 'Ürün Tasarımcısı',
  'UI Designer': 'Arayüz Tasarımcısı',
  'B.A. Visual Design': 'Görsel Tasarım Lisansı',
  'Product strategy': 'Ürün stratejisi',
  'Design systems': 'Tasarım sistemleri',
  Prototyping: 'Prototipleme',
  'User research': 'Kullanıcı araştırması',
  'Open to new roles': 'Yeni fırsatlara açık',
  'Years of experience': 'Yıllık deneyim',
  'Projects shipped': 'Tamamlanan proje',
  'Teams supported': 'Desteklenen ekip',
  'Skills & education': 'Beceriler ve eğitim',
  'Email me': 'E-posta gönder',
  'Hire me': 'Birlikte çalışalım',
  "Let's work together": 'Birlikte çalışalım',
  'Product designer with 8+ years crafting clear, responsive interfaces. I care about systems, typography, and shipping work that lasts.': 'Net ve duyarlı arayüzler tasarlayan 8+ yıllık deneyime sahip ürün tasarımcısıyım. Sistemlere, tipografiye ve kalıcı işler üretmeye önem veriyorum.',
  'Led the redesign of the core product, improving activation by 28%. Built and maintained the design system used across 6 teams.': 'Ana ürünün yeniden tasarımını yöneterek aktivasyonu %28 artırdım. Altı ekipte kullanılan tasarım sistemini kurup geliştirdim.',
  'Owned end-to-end design for the mobile app from research to ship. Partnered closely with engineering on a fluid, responsive UI.': 'Mobil uygulamanın araştırmadan yayına kadar uçtan uca tasarımını üstlendim. Akıcı ve duyarlı bir arayüz için mühendislik ekibiyle yakın çalıştım.',
  'Designed marketing pages and interface components. Introduced a reusable layout grid that cut handoff time in half.': 'Pazarlama sayfaları ve arayüz bileşenleri tasarladım. Teslim süresini yarıya indiren yeniden kullanılabilir bir yerleşim sistemi geliştirdim.',
  'Graduated with honors; thesis on accessible interface patterns.': 'Erişilebilir arayüz kalıpları üzerine tezle onur derecesiyle mezun oldum.',
  'A track record of shipping design that moves real product metrics.': 'Gerçek ürün metriklerini iyileştiren tasarımlar üretme deneyimi.',
  'Also: conference speaker, design-systems meetup organizer.': 'Ayrıca konferans konuşmacısı ve tasarım sistemleri buluşması düzenleyicisi.',
  'Tell me about your team and what you are building — I usually reply within one business day.': 'Ekibinizi ve ne geliştirdiğinizi anlatın; genellikle bir iş günü içinde yanıt veririm.',
  'Product designer crafting clear, responsive interfaces.': 'Net ve duyarlı arayüzler tasarlayan ürün tasarımcısı.',
  Portfolio: 'Portfolyo',
  'Selected work': 'Seçili çalışmalar',
  'Designer & developer': 'Tasarımcı ve geliştirici',
  'Work that ships,': 'Yalnızca güzel değil,',
  'not just shines.': 'yayına hazır işler.',
  'Selected projects from eight years of building products, brands, and websites for teams that care about craft.': 'Ürüne önem veren ekipler için ürün, marka ve web sitesi geliştirdiğim sekiz yıldan seçili projeler.',
  'See the work': 'Çalışmaları gör',
  'Six projects that show range: product, web, mobile, and brand.': 'Ürün, web, mobil ve marka alanlarındaki çeşitliliği gösteren altı proje.',
  'Design with an engineering brain': 'Mühendislik bakışıyla tasarım',
  'I prototype in code, obsess over type and spacing, and measure outcomes after launch. Teams keep me around because handoff is painless and the details survive production.': 'Kodla prototip üretir, tipografi ve aralıklara özen gösterir, sonuçları yayından sonra ölçerim. Sorunsuz teslim ve üretimde korunan ayrıntılar için ekiplerle uzun süre çalışırım.',
  Projects: 'Projeler',
  Industries: 'Sektör',
  'Have a project in mind?': 'Aklınızda bir proje mi var?',
  'Tell me what you are building and where you are stuck — I reply within one business day.': 'Ne geliştirdiğinizi ve nerede zorlandığınızı anlatın; bir iş günü içinde yanıt veririm.',
  'Independent designer & developer. Available for select projects.': 'Bağımsız tasarımcı ve geliştirici. Seçili projeler için müsait.',
  'Designer making calm, usable software.': 'Sade ve kullanışlı yazılımlar tasarlayan bir tasarımcı.',
  'A plain page, on purpose. The work below speaks for itself.': 'Bilinçli olarak sade bir sayfa. Aşağıdaki çalışmalar kendini anlatıyor.',
  'Want the full case studies?': 'Tüm vaka çalışmalarını görmek ister misiniz?',
  Web: 'Web',
  Mobile: 'Mobil',
  Brand: 'Marka',
  Systems: 'Sistemler',
  FAQ: 'SSS',
  'Now in public beta': 'Şimdi herkese açık beta sürümünde',
  'Ship your product site': 'Ürün sitenizi',
  'in an afternoon.': 'bir öğleden sonra yayınlayın.',
  'See features': 'Özellikleri gör',
  'Teams on board': 'Kullanan ekip',
  Uptime: 'Çalışma süresi',
  'Average rating': 'Ortalama puan',
  'Everything you actually need': 'Gerçekten ihtiyacınız olan her şey',
  'No bloat. Three things, done extremely well.': 'Gereksiz kalabalık yok. Üç temel iş, son derece iyi yapılır.',
  'Fast by default': 'Varsayılan olarak hızlı',
  'Static pages served from the edge. 100/100 performance without tuning.': 'Uç sunuculardan sunulan statik sayfalar. Ayar gerektirmeden 100/100 performans.',
  'Secure forms': 'Güvenli formlar',
  'Spam-filtered submissions delivered to your inbox or webhook.': 'Spam filtresinden geçen gönderimler gelen kutunuza veya webhook adresinize iletilir.',
  'Private analytics': 'Gizlilik odaklı analizler',
  'Cookieless metrics your legal team will actually approve.': 'Hukuk ekibinizin onaylayacağı çerezsiz metrikler.',
  'Simple, honest pricing': 'Basit ve şeffaf fiyatlandırma',
  'Start free. Upgrade when you outgrow it.': 'Ücretsiz başlayın, ihtiyaçlarınız büyüdüğünde yükseltin.',
  Starter: 'Başlangıç',
  Pro: 'Profesyonel',
  Team: 'Ekip',
  'Most popular': 'En popüler',
  'Community support': 'Topluluk desteği',
  'Custom domain': 'Özel alan adı',
  'No badge': 'Rozet yok',
  'Priority support': 'Öncelikli destek',
  'Unlimited sites': 'Sınırsız site',
  'Roles & permissions': 'Roller ve izinler',
  'Audit log': 'Denetim günlüğü',
  'Questions, answered': 'Sorular ve yanıtları',
  'Can I use my own domain?': 'Kendi alan adımı kullanabilir miyim?',
  'Yes — Pro and Team plans connect any domain with automatic SSL.': 'Evet. Profesyonel ve Ekip planları otomatik SSL ile her alan adına bağlanabilir.',
  'Do you offer refunds?': 'Para iadesi sunuyor musunuz?',
  'Full refund within 30 days, no questions asked.': 'İlk 30 gün içinde koşulsuz tam iade sunuyoruz.',
  'Can I export my site?': 'Sitemi dışa aktarabilir miyim?',
  'Always. Your content is yours; export clean HTML at any time.': 'Her zaman. İçeriğiniz size aittir; istediğiniz zaman temiz HTML olarak dışa aktarabilirsiniz.',
  'Ready to ship?': 'Yayınlamaya hazır mısınız?',
  'Join 12,000 teams building faster sites with less hassle.': 'Daha hızlı ve kolay site geliştiren 12.000 ekibe katılın.',
  'Start free today': 'Bugün ücretsiz başlayın',
  'The fastest way from idea to a live product site.': 'Fikirden yayındaki ürün sitesine giden en hızlı yol.',
  'Get the app': 'Uygulamayı edin',
  'iOS & Android': 'iOS ve Android',
  'Your day,': 'Gününüz',
  'finally under control.': 'artık kontrol altında.',
  'Download free': 'Ücretsiz indir',
  'How it works': 'Nasıl çalışır?',
  'Built for focus': 'Odaklanmak için geliştirildi',
  'Smart planning': 'Akıllı planlama',
  'Drop tasks in; the schedule builds itself around your meetings.': 'Görevleri ekleyin; program toplantılarınıza göre kendini oluştursun.',
  'Focus mode': 'Odak modu',
  'One tap silences everything that is not the current task.': 'Tek dokunuş, mevcut görev dışındaki tüm dikkat dağıtıcıları susturur.',
  'Weekly review': 'Haftalık değerlendirme',
  'See where the hours actually went — and fix next week.': 'Saatlerin nereye gittiğini görün ve gelecek haftayı iyileştirin.',
  'Loved by busy people': 'Yoğun çalışanların favorisi',
  '“Deleted three other apps”': '“Diğer üç uygulamayı sildim”',
  '— Maya R., product manager. The planner I always wanted.': '— Maya R., ürün yöneticisi. Her zaman aradığım planlayıcı.',
  '“My evenings are back”': '“Akşamlarımı geri kazandım”',
  '— Jonas K., engineer. The focus mode alone is worth it.': '— Jonas K., mühendis. Yalnızca odak modu bile yeterli.',
  '“Simple, not simplistic”': '“Sade ama basit değil”',
  '— Aylin T., founder. Powerful without the clutter.': '— Aylin T., kurucu. Kalabalık olmadan güçlü.',
  'On the App Store and Google Play. Pro upgrade when you are ready.': 'App Store ve Google Play’de. Hazır olduğunuzda Profesyonel sürüme geçin.',
  'Download now': 'Şimdi indir',
  'The calm planner for busy weeks.': 'Yoğun haftalar için sakin bir planlayıcı.',
  'Design & engineering studio': 'Tasarım ve mühendislik stüdyosu',
  'Websites that earn': 'Değer üreten',
  'their keep.': 'web siteleri.',
  'We design, build, and maintain fast marketing sites for B2B teams — measured by pipeline, not pixels.': 'B2B ekipleri için hızlı pazarlama siteleri tasarlıyor, geliştiriyor ve sürdürüyoruz; başarıyı pikselle değil sonuçlarla ölçüyoruz.',
  'Sites launched': 'Yayınlanan site',
  'Avg. conversion lift': 'Ort. dönüşüm artışı',
  'Typical delivery': 'Tipik teslimat',
  'Three engagements, fixed scope, fixed price.': 'Üç hizmet modeli, net kapsam ve sabit fiyat.',
  'Site sprint': 'Site sprinti',
  'A full marketing site designed and live in 14 days.': 'Eksiksiz bir pazarlama sitesi 14 günde tasarlanır ve yayınlanır.',
  'Component libraries your team can actually maintain.': 'Ekibinizin gerçekten sürdürebileceği bileşen kütüphaneleri.',
  'Growth retainers': 'Büyüme desteği',
  'Continuous experiments: landing pages, A/B tests, SEO.': 'Sürekli deneyler: açılış sayfaları, A/B testleri ve SEO.',
  'Send a short brief — we respond with a plan and a fixed quote within 48 hours.': 'Kısa bir özet gönderin; 48 saat içinde plan ve sabit fiyat teklifiyle yanıtlayalım.',
  'A small studio with senior people only. No account managers.': 'Yalnızca deneyimli uzmanlardan oluşan küçük bir stüdyo. Aracı hesap yöneticisi yok.',
  'Find us': 'Bizi bulun',
  'Neighbourhood café · est. 2019': 'Mahalle kafesi · 2019’dan beri',
  'Good coffee.': 'İyi kahve.',
  'Honest food.': 'Dürüst yemek.',
  'Everything made in-house every morning: bread, cakes, and the best flat white on the street.': 'Ekmek, kek ve sokağın en iyi flat white’ı dahil her şey her sabah mutfağımızda hazırlanır.',
  'Seasonal, local, and changing often — this is today.': 'Mevsimlik, yerel ve sık değişen bugünkü menümüz.',
  'Sourdough & whipped butter': 'Ekşi mayalı ekmek ve çırpılmış tereyağı',
  'Shakshuka, herbs, warm bread': 'Şakşuka, otlar ve sıcak ekmek',
  'Granola, yogurt, berries': 'Granola, yoğurt ve orman meyveleri',
  'Roast cauliflower bowl': 'Fırın karnabahar kasesi',
  'Chicken schnitzel sandwich': 'Tavuk şinitzel sandviç',
  'Seasonal soup & bread': 'Mevsim çorbası ve ekmek',
  'Flat white': 'Flat white',
  'Filter — single origin': 'Filtre kahve — tek köken',
  'House lemonade': 'Ev yapımı limonata',
  'Mon–Fri': 'Pzt–Cum',
  'Sat–Sun': 'Cmt–Paz',
  'Kadıköy, Moda Cd. 42 — two minutes from the ferry.': 'Kadıköy, Moda Cd. 42 — vapura iki dakika.',
  'We host breakfasts, book clubs, and small launches up to 30 people.': '30 kişiye kadar kahvaltı, kitap kulübü ve küçük lansmanlara ev sahipliği yapıyoruz.',
  'Good coffee, honest food, friendly people.': 'İyi kahve, dürüst yemek ve güler yüzlü insanlar.',
  'Photographer · weddings & portraits': 'Fotoğrafçı · düğün ve portre',
  'Light, caught': 'Doğru anda',
  'at the right second.': 'yakalanan ışık.',
  'Editorial photography for people who hate posing. Natural, calm, and a little cinematic.': 'Poz vermeyi sevmeyenler için editoryal fotoğrafçılık. Doğal, sakin ve biraz sinematik.',
  'Hi, I am behind the camera': 'Merhaba, kameranın arkasındaki kişiyim',
  'Ten years, four hundred weddings, one rule: real moments beat staged ones. I shoot quietly, edit warmly, and deliver fast.': 'On yıl, dört yüz düğün ve tek kural: gerçek anlar kurgulanmış olanlardan değerlidir. Sessizce çeker, sıcak tonlarda düzenler ve hızlı teslim ederim.',
  '2026 dates are open': '2026 tarihleri açık',
  'Tell me about your day — date, place, and what matters most to you.': 'Gününüzü; tarihi, yeri ve sizin için en önemli ayrıntıları anlatın.',
  'Editorial photography, weddings & portraits.': 'Editoryal fotoğrafçılık, düğün ve portre.',
  'A blog about building software': 'Yazılım geliştirme üzerine bir blog',
  'Essays on product, design, and engineering — one a month, no filler.': 'Ürün, tasarım ve mühendislik üzerine ayda bir, dolgu içermeyen yazılar.',
  'The case for boring technology': 'Sıkıcı teknolojinin haklılığı',
  'Why our stack got simpler every year — and shipping got faster.': 'Teknoloji yığınımız neden her yıl sadeleşirken yayınlama hızımız arttı?',
  'Designing for the third read': 'Üçüncü okuma için tasarlamak',
  'Interfaces reveal themselves in layers. Plan all three.': 'Arayüzler katmanlar hâlinde kendini gösterir. Üçünü de planlayın.',
  'What I learned from 100 user calls': '100 kullanıcı görüşmesinden öğrendiklerim',
  'Patterns only show up after call forty. Keep going.': 'Kalıplar ancak kırkıncı görüşmeden sonra belirginleşir. Devam edin.',
  'Writing docs people actually read': 'İnsanların gerçekten okuduğu dokümanlar yazmak',
  'Structure beats prose. Examples beat structure.': 'Yapı anlatımdan, örnekler yapıdan güçlüdür.',
  'Jun 2026': 'Haz 2026',
  'May 2026': 'May 2026',
  'Apr 2026': 'Nis 2026',
  'Mar 2026': 'Mar 2026',
  'No spam, no growth hacks — just the writing. Unsubscribe anytime.': 'Spam ve büyüme hilesi yok; yalnızca yazılar. İstediğiniz zaman abonelikten çıkın.',
  'Essays on product, design, and engineering.': 'Ürün, tasarım ve mühendislik üzerine yazılar.',
  'Saturday · 12 September 2026 · Istanbul': 'Cumartesi · 12 Eylül 2026 · İstanbul',
  "We're getting": 'Evleniyoruz.',
  'married.': 'Hayatlarımızı birleştiriyoruz.',
  'And it would mean the world to celebrate with you. Here is everything you need for the day.': 'Bu günü sizinle kutlamak bizim için çok değerli. Günle ilgili ihtiyacınız olan her şey burada.',
  'RSVP now': 'Şimdi katılım bildir',
  'Welcome drinks on the terrace.': 'Terasta karşılama içecekleri.',
  'Short and sweet — bring sunglasses.': 'Kısa ve güzel; güneş gözlüğünüzü getirin.',
  'Long tables, family style, lots of toasts.': 'Uzun masalar, aile usulü servis ve bolca kutlama.',
  'First dance, then everyone dances. Until late.': 'İlk dansın ardından herkes gece geç saatlere kadar dans edecek.',
  'Esma Sultan Mansion, Ortaköy — on the water, under the bridge. Dress code: summer formal. Parking is limited; taxis are easy.': 'Esma Sultan Yalısı, Ortaköy — denizin kıyısında, köprünün altında. Kıyafet: yazlık resmî. Otopark sınırlı; taksi kullanımı kolay.',
  'Please reply by 1 August — and tell us about any dietary needs.': 'Lütfen 1 Ağustos’a kadar yanıt verin ve özel beslenme ihtiyaçlarınızı belirtin.',
  'With love — see you in September.': 'Sevgiyle — Eylül’de görüşmek üzere.',
  'Small-batch goods · free EU shipping over €60': 'Küçük üretim · €60 üzeri AB’ye ücretsiz kargo',
  'Made slowly.': 'Yavaş üretildi.',
  'Made to last.': 'Uzun ömürlü tasarlandı.',
  'Homeware from small European workshops — every piece traceable to the person who made it.': 'Küçük Avrupa atölyelerinden ev ürünleri; her parçanın üreticisi belli.',
  'Canvas tote — natural': 'Kanvas çanta — doğal',
  'Enamel mug — forest': 'Emaye kupa — orman',
  'Linen apron — rust': 'Keten önlük — pas rengi',
  'Beeswax candle set': 'Balmumu mum seti',
  'Ceramic pour-over': 'Seramik pour-over',
  'Wool throw — oat': 'Yün örtü — yulaf',
  'We visit every workshop, pay fairly, and stock little. When something sells out, it comes back when it is ready — not before.': 'Her atölyeyi ziyaret eder, adil ödeme yapar ve az stok tutarız. Tükenen ürün ancak yeniden hazır olduğunda geri gelir.',
  'We answer every email within a day — usually faster.': 'Her e-postayı bir gün içinde, çoğunlukla daha hızlı yanıtlarız.',
  'Small-batch homeware from European workshops.': 'Avrupa atölyelerinden küçük üretim ev ürünleri.',
  'Latest podcast episode': 'Son podcast bölümü',
  'Newsletter — one email a week': 'Bülten — haftada bir e-posta',
  'Tools I use daily': 'Her gün kullandığım araçlar',
  'Book a 15-min call': '15 dakikalık görüşme ayarla',
  'Maker, writer, and occasional podcaster. Everything I do, one tap away.': 'Üretici, yazar ve zaman zaman podcast yayıncısı. Yaptığım her şey tek dokunuş uzağınızda.',
  'Open menu': 'Menüyü aç',
  'Decorative visual': 'Dekoratif görsel',
  Photograph: 'Fotoğraf',
}

// Fitness & Wellness templates have deliberately bespoke editorial copy. Keep
// their Turkish output just as complete as their English counterpart instead
// of translating only the gallery card title.
Object.assign(TEMPLATE_TEXT_TR, {
  Programs: 'Programlar',
  Coaches: 'Koçlar',
  Join: 'Katıl',
  'Explore programs': 'Programları keşfet',
  Training: 'Antrenman',
  'People first': 'Önce insan',
  Practice: 'Pratik',
  Book: 'Rezervasyon yap',
  'See services': 'Hizmetleri gör',
  'This week': 'Bu hafta',
  'Our approach': 'Yaklaşımımız',
  'Ways to work together': 'Birlikte çalışma yolları',
  'Thoughtful care': 'Özenli destek',
  '60 min': '60 dk',
  '50 min': '50 dk',
  '45 min': '45 dk',
  Included: 'Dahil',

  'Strength · Conditioning · Community': 'Kuvvet · Kondisyon · Topluluk',
  'Train with': 'Planlı',
  'a plan.': 'antrenman yapın.',
  'Small-group strength coaching for people who want steady progress without gym-floor guesswork.': 'Spor salonunda ne yapacağını tahmin etmek istemeyen ve istikrarlı gelişim arayanlar için küçük grup kuvvet koçluğu.',
  'Start training': 'Antrenmana başla',
  coaches: 'koç',
  'weekly sessions': 'haftalık seans',
  'member rating': 'üye puanı',
  'Choose your starting line': 'Başlangıç noktanı seç',
  'A clear programme for the first week, the next milestone, and the long run.': 'İlk hafta, sonraki hedef ve uzun vadeli gelişim için net bir program.',
  Foundations: 'Temeller',
  'Learn the lifts, build confidence, and move well.': 'Temel hareketleri öğrenin, özgüven kazanın ve daha iyi hareket edin.',
  Build: 'Gelişim',
  'Structured strength blocks with progressive coaching.': 'Aşamalı koçlukla yapılandırılmış kuvvet blokları.',
  Performance: 'Performans',
  'Conditioning and power for your next personal best.': 'Bir sonraki kişisel rekorunuz için kondisyon ve güç.',
  'Coaching that meets you where you are': 'Olduğunuz yerden başlayan koçluk',
  'Every session has a plan, a coach who knows your name, and room to work at your own pace.': 'Her seansın bir planı, sizi tanıyan bir koçu ve kendi hızınızda çalışacak alanı vardır.',
  'First session': 'İlk seans',
  'Meet your coach, set a simple baseline, and leave with a plan for week one.': 'Koçunuzla tanışın, basit bir başlangıç seviyesi belirleyin ve ilk hafta planınızla ayrılın.',
  'Ready for a stronger routine?': 'Daha güçlü bir rutine hazır mısınız?',
  'Book a first session. No contract and no pressure to decide on the day.': 'İlk seansınızı ayırtın. Sözleşme yok, o gün karar verme baskısı yok.',
  'A strength club for consistent, supported progress.': 'İstikrarlı ve destekli gelişim için bir kuvvet kulübü.',
  'Strength training': 'Kuvvet antrenmanı',

  'A quiet hour for your whole week': 'Tüm haftanız için sakin bir saat',
  'Make space': 'Alan açın',
  'to breathe.': 've nefes alın.',
  'Slow, grounded yoga classes in a sunlit neighbourhood studio. Come exactly as you are.': 'Güneş alan bir mahalle stüdyosunda yavaş ve dengeli yoga dersleri. Olduğunuz gibi gelin.',
  'Book a class': 'Ders ayırt',
  'A rhythm for every week': 'Her hafta için bir ritim',
  'Choose a class that feels right today; all levels are welcome.': 'Bugün size iyi gelecek dersi seçin; her seviye davetlidir.',
  'Morning flow': 'Sabah akışı',
  'Wake up gently and move with your breath.': 'Nazikçe uyanın ve nefesinizle hareket edin.',
  'Slow vinyasa': 'Yavaş vinyasa',
  'An unhurried strength and mobility practice.': 'Acele etmeyen bir kuvvet ve hareketlilik pratiği.',
  'Reset class': 'Yenilenme dersi',
  'A generous weekend class for every level.': 'Her seviye için geniş ve rahat bir hafta sonu dersi.',
  'Less performance. More presence.': 'Daha az performans. Daha çok anda kalmak.',
  'We keep classes small, give clear options, and make room for quiet. Your practice can change from one week to the next.': 'Dersleri küçük tutar, net seçenekler sunar ve sakinliğe alan açarız. Pratiğiniz haftadan haftaya değişebilir.',
  'Small groups': 'Küçük gruplar',
  'Space to ask questions and make the practice yours.': 'Soru sormak ve pratiği kendinize göre uyarlamak için alan.',
  'Kind guidance': 'Nazik rehberlik',
  'Clear cues without pressure to get every shape right.': 'Her pozisyonu kusursuz yapma baskısı olmadan net yönlendirmeler.',
  'Your mat is waiting': 'Matınız sizi bekliyor',
  'Reserve a class or ask about a first-visit pass by email.': 'Bir ders ayırtın veya ilk ziyaret kartını e-postayla sorun.',
  'A neighbourhood yoga studio for slower, steadier days.': 'Daha yavaş ve dengeli günler için mahalle yoga stüdyosu.',
  'Yoga studio': 'Yoga stüdyosu',

  'Reformer · mat · private sessions': 'Reformer · mat · özel seanslar',
  'Precision that': 'İyi hissettiren',
  'feels good.': 'bir hassasiyet.',
  'A considered Pilates practice for strength, alignment, and more ease in everyday movement.': 'Kuvvet, hizalanma ve günlük harekette daha fazla rahatlık için düşünülmüş bir Pilates pratiği.',
  'Find a class': 'Bir ders bul',
  'Plan your practice': 'Pratiğini planla',
  'Choose reformer, mat, or a private session with a teacher who learns your body.': 'Vücudunuzu tanıyan bir eğitmenle reformer, mat veya özel seans seçin.',
  'Reformer foundations': 'Reformer temelleri',
  'A supportive introduction to equipment and form.': 'Ekipman ve form için destekleyici bir başlangıç.',
  'Mat strength': 'Mat kuvveti',
  'Deep core work with intelligent pacing.': 'Akıllı tempoyla derin merkez bölge çalışması.',
  'Private focus': 'Özel odak',
  'One-to-one attention for your specific goals.': 'Size özel hedefleriniz için bire bir ilgi.',
  'Built around how you move': 'Hareket biçiminiz etrafında kuruldu',
  'Good technique should feel clear, not intimidating. We use small, consistent cues to help you build strength you can trust.': 'İyi teknik göz korkutucu değil net hissettirmelidir. Güvenebileceğiniz kuvveti oluşturmanız için küçük ve tutarlı yönlendirmeler kullanırız.',
  'Thoughtful progressions': 'Düşünülmüş ilerlemeler',
  'A clear next step whether you are new or experienced.': 'Yeni ya da deneyimli olmanız fark etmeksizin net bir sonraki adım.',
  'Teacher attention': 'Eğitmen ilgisi',
  'Detailed, personal guidance in every class.': 'Her derste ayrıntılı ve kişisel rehberlik.',
  'Start with a first session': 'İlk seansla başlayın',
  'Tell us what you want from your practice and we will suggest the right class.': 'Pratiğinizden ne beklediğinizi söyleyin; size doğru dersi önerelim.',
  'Pilates for stronger, more confident everyday movement.': 'Daha güçlü ve güvenli günlük hareket için Pilates.',
  'Pilates studio': 'Pilates stüdyosu',

  'Personal training · online accountability': 'Kişisel antrenman · çevrim içi takip',
  'A plan built': 'Hayatınıza göre',
  'around your life.': 'oluşturulmuş bir plan.',
  'Coaching for busy people who want simple training, useful feedback, and results that last.': 'Basit antrenman, faydalı geri bildirim ve kalıcı sonuç isteyen yoğun insanlar için koçluk.',
  'Meet your coach': 'Koçunla tanış',
  coaching: 'koçluk',
  'first cycle': 'ilk döngü',
  'renewal rate': 'yenileme oranı',
  'No generic programmes': 'Genel geçer program yok',
  'Start with your schedule, your history, and one goal worth working toward.': 'Programınız, geçmişiniz ve uğruna çalışmaya değer tek bir hedefle başlayın.',
  'Start strong': 'Güçlü başla',
  'Build the habits and movement basics that make training stick.': 'Antrenmanı sürdürülebilir kılan alışkanlıkları ve hareket temellerini oluşturun.',
  'Build momentum': 'İvme kazan',
  'A progressive plan with weekly coaching feedback.': 'Haftalık koçluk geri bildirimiyle aşamalı bir plan.',
  'Stay ready': 'Hazır kal',
  'Flexible programming for travel, work, and real life.': 'Seyahat, iş ve gerçek hayat için esnek programlama.',
  'A coach in your corner': 'Yanınızda bir koç',
  'You get a clear training plan, honest feedback, and a practical way to stay consistent on busy weeks.': 'Net bir antrenman planı, dürüst geri bildirim ve yoğun haftalarda tutarlı kalmanın pratik yolunu elde edersiniz.',
  'Your first call': 'İlk görüşmeniz',
  'We talk through your routine, training history, and a goal you can measure.': 'Rutininizi, antrenman geçmişinizi ve ölçebileceğiniz bir hedefi konuşuruz.',
  'Make your next twelve weeks count': 'Önümüzdeki on iki haftayı değerlendirin',
  'Send a short note about where you are now and what you want to change.': 'Şu an nerede olduğunuzu ve neyi değiştirmek istediğinizi kısaca yazın.',
  'Personal training with a plan that fits real life.': 'Gerçek hayata uyan bir planla kişisel antrenman.',
  'Personal training': 'Kişisel antrenman',

  'City runs · trails · coffee after': 'Şehir koşuları · patikalar · sonrasında kahve',
  'Find your': 'Kendi',
  'running people.': 'koşu arkadaşlarını bul.',
  'A friendly run club for steady miles, new routes, and the kind of accountability that feels social.': 'Düzenli kilometreler, yeni rotalar ve sosyal hissettiren bir takip için samimi koşu kulübü.',
  'Join a run': 'Koşuya katıl',
  'weekly runs': 'haftalık koşu',
  'longest route': 'en uzun rota',
  'club members': 'kulüp üyesi',
  'A pace for every runner': 'Her koşucu için bir tempo',
  'Choose a group, meet at the start line, and let the route do the rest.': 'Bir grup seçin, başlangıçta buluşun ve gerisini rotaya bırakın.',
  'First 5K': 'İlk 5K',
  'A gentle group for building a running habit.': 'Koşu alışkanlığı oluşturmak için nazik bir grup.',
  'City miles': 'Şehir kilometreleri',
  'Midweek routes through the streets we love.': 'Sevdiğimiz sokaklardan geçen hafta içi rotaları.',
  'Trail days': 'Patika günleri',
  'Longer weekends outside the city and off the road.': 'Şehir dışında ve yollardan uzak daha uzun hafta sonları.',
  'The route is better together': 'Rota birlikte daha iyi',
  'Our run leaders set the pace, keep the group connected, and always make time for the coffee afterwards.': 'Koşu liderlerimiz tempoyu belirler, grubu bir arada tutar ve sonrasında kahve için her zaman zaman ayırır.',
  'New to the club?': 'Kulüpte yeni misiniz?',
  'Come to any first-5K or city-miles run. We will help you find your group.': 'İlk 5K veya şehir kilometreleri koşularından birine gelin. Grubunuzu bulmanıza yardım ederiz.',
  'See you at the start line': 'Başlangıç çizgisinde görüşürüz',
  'Join the next run and get the weekly route note in your inbox.': 'Bir sonraki koşuya katılın ve haftalık rota notunu gelen kutunuza alın.',
  'A run club for good miles and better company.': 'İyi kilometreler ve daha iyi dostluklar için bir koşu kulübü.',
  'Running club': 'Koşu kulübü',

  'Four days by the sea · limited to 16 guests': 'Deniz kenarında dört gün · 16 misafirle sınırlı',
  'Come back': 'Kendine',
  'to yourself.': 'dön.',
  'A long weekend of movement, good food, and unstructured time in a place made for exhaling.': 'Nefes vermek için tasarlanmış bir yerde hareket, iyi yemek ve plansız zamanla dolu uzun bir hafta sonu.',
  'Request a place': 'Yer talep et',
  'A gentle four-day rhythm': 'Nazik bir dört günlük ritim',
  'Everything is optional except arriving as you are.': 'Olduğunuz gibi gelmek dışında her şey isteğe bağlıdır.',
  'Arrive and settle': 'Gel ve yerleş',
  'Tea on the terrace, a soft evening practice.': 'Terasta çay, yumuşak bir akşam pratiği.',
  'Move and explore': 'Hareket et ve keşfet',
  'Morning movement, a long lunch, coastal walk.': 'Sabah hareketi, uzun öğle yemeği, sahil yürüyüşü.',
  'Rest and restore': 'Dinlen ve yenilen',
  'Breathwork, quiet hours, candlelit dinner.': 'Nefes çalışması, sakin saatler, mum ışığında akşam yemeği.',
  'More room in the day': 'Günde daha çok alan',
  'The retreat is deliberately spacious: enough structure to feel held, enough free time to notice what you need.': 'Kaçamak bilinçli olarak ferah tasarlandı: desteklenmek için yeterli yapı, ihtiyacınızı fark etmek için yeterli boş zaman.',
  'Slow mornings': 'Yavaş sabahlar',
  'No early alarms, only a nourishing start.': 'Erken alarm yok; yalnızca besleyici bir başlangıç.',
  'Small table': 'Küçük masa',
  'Shared meals with seasonal food and unhurried conversation.': 'Mevsimsel yemekler ve acele etmeyen sohbetlerle paylaşılan sofralar.',
  'Take your place at the table': 'Masadaki yerinizi alın',
  'Email us for dates, room options, and accessibility details.': 'Tarihler, oda seçenekleri ve erişilebilirlik ayrıntıları için e-posta gönderin.',
  'Small retreats for rest, movement, and renewed attention.': 'Dinlenme, hareket ve yenilenmiş dikkat için küçük kaçamaklar.',
  'Wellness retreat': 'İyi yaşam kaçamağı',

  'Evidence-led nutrition · everyday habits': 'Kanıta dayalı beslenme · günlük alışkanlıklar',
  'Food support': 'Beslenme desteği',
  'for real life.': 'gerçek hayat için.',
  'Simple, non-judgemental nutrition support that fits your culture, budget, schedule, and goals.': 'Kültürünüze, bütçenize, programınıza ve hedeflerinize uyan basit, yargısız beslenme desteği.',
  'Book a consultation': 'Danışma ayırt',
  'Choose the support you need': 'İhtiyacınız olan desteği seçin',
  'Start where you are and leave with actions that make sense next week.': 'Olduğunuz yerden başlayın ve gelecek hafta anlamlı olacak adımlarla ayrılın.',
  'Private consultation': 'Bireysel danışma',
  'A focused session around your habits, questions, and priorities.': 'Alışkanlıklarınıza, sorularınıza ve önceliklerinize odaklanan bir seans.',
  'Four-week reset': 'Dört haftalık yenilenme',
  'Structured support for building one sustainable routine at a time.': 'Her seferinde sürdürülebilir bir rutin oluşturmak için yapılandırılmış destek.',
  'Group workshop': 'Grup atölyesi',
  'Practical food education for teams, friends, and communities.': 'Ekipler, arkadaşlar ve topluluklar için pratik beslenme eğitimi.',
  'Useful information, not food rules': 'Yemek kuralları değil, faydalı bilgi',
  'We look at patterns before prescriptions. The goal is more confidence around food, not a perfect plan.': 'Reçetelerden önce örüntülere bakarız. Amaç kusursuz plan değil, yemek konusunda daha fazla özgüvendir.',
  'Tell us what a normal week looks like': 'Normal bir haftanızın nasıl göründüğünü anlatın',
  'Choose one or two changes worth testing': 'Denemeye değer bir veya iki değişiklik seçin',
  'Adjust with support as life happens': 'Hayat akarken destekle uyarlayın',
  'Start with one conversation': 'Tek bir görüşmeyle başlayın',
  'Share a little about what you need and we will suggest the best first session.': 'Neye ihtiyacınız olduğunu kısaca paylaşın; en iyi ilk seansı önerelim.',
  'Practical nutrition support for everyday life.': 'Günlük hayat için pratik beslenme desteği.',
  'Nutrition practice': 'Beslenme uzmanlığı',

  'Mindful movement · breath · rest': 'Bilinçli hareket · nefes · dinlenme',
  'A quieter way': 'Daha sakin bir yol',
  'to feel better.': 'ile daha iyi hissetmek.',
  'Small classes for slowing down, moving kindly, and making space for a steadier nervous system.': 'Yavaşlamak, nazikçe hareket etmek ve daha dengeli bir sinir sistemi için alan açmak üzere küçük dersler.',
  'Plan a visit': 'Bir ziyaret planla',
  'Choose your pace': 'Temponu seç',
  'Each class is designed to meet the energy you arrive with.': 'Her ders, geldiğinizde sahip olduğunuz enerjiye göre tasarlanır.',
  'Midday reset': 'Öğle yenilenmesi',
  'A short, grounding pause in the middle of the week.': 'Haftanın ortasında kısa ve dengeleyici bir mola.',
  'Move slowly': 'Yavaş hareket et',
  'Gentle mobility with more room to breathe.': 'Nefes için daha çok alan bırakan nazik hareketlilik.',
  'Rest practice': 'Dinlenme pratiği',
  'A soft end to the week with supported rest.': 'Destekli dinlenmeyle haftaya yumuşak bir kapanış.',
  'No need to push through': 'Kendini zorlamana gerek yok',
  'We offer options, permission to rest, and a practice that makes room for your actual day—not the ideal one.': 'Seçenekler, dinlenme izni ve ideal olana değil gerçek gününüze yer açan bir pratik sunuyoruz.',
  'Accessible entry': 'Erişilebilir başlangıç',
  'No experience, flexibility, or special equipment needed.': 'Deneyim, esneklik veya özel ekipman gerekmez.',
  'A softer room': 'Daha yumuşak bir alan',
  'Low light, simple language, and a pace that stays human.': 'Loş ışık, sade dil ve insani kalan bir tempo.',
  'Your first class can be simple': 'İlk dersiniz basit olabilir',
  'Tell us when you are free and we will help you choose a starting point.': 'Ne zaman müsait olduğunuzu söyleyin; başlangıç noktanızı seçmenize yardım edelim.',
  'Mindful movement for quieter, steadier days.': 'Daha sakin ve dengeli günler için bilinçli hareket.',
  'Mindful movement': 'Bilinçli hareket',

  'Technique · discipline · respect': 'Teknik · disiplin · saygı',
  'Practice with': 'Amaçla',
  'purpose.': 'pratik yapın.',
  'A welcoming martial arts school for focused training, patient coaching, and steady confidence.': 'Odaklı antrenman, sabırlı koçluk ve istikrarlı özgüven için sıcak karşılayan bir dövüş sanatları okulu.',
  'Try a class': 'Bir ders dene',
  'skill levels': 'beceri seviyesi',
  'weekly classes': 'haftalık ders',
  'teaching experience': 'yıllık eğitim deneyimi',
  'Start at your level': 'Seviyenden başla',
  'Clear fundamentals for new students and focused progression for returning practitioners.': 'Yeni öğrenciler için net temeller, geri dönenler için odaklı ilerleme.',
  'Fundamentals': 'Temeller',
  'Stance, movement, and the habits that make practice safe.': 'Duruş, hareket ve pratiği güvenli kılan alışkanlıklar.',
  Technique: 'Teknik',
  'Detailed drills and partner work at a thoughtful pace.': 'Düşünülmüş bir tempoda ayrıntılı çalışmalar ve eşli pratik.',
  'Advanced practice': 'İleri seviye pratik',
  'Longer rounds for experienced students seeking depth.': 'Derinlik arayan deneyimli öğrenciler için daha uzun raundlar.',
  'Discipline without intimidation': 'Göz korkutmayan disiplin',
  'Our instructors teach with clarity and care. You will know what to work on, why it matters, and how to progress.': 'Eğitmenlerimiz netlik ve özenle öğretir. Ne üzerinde çalışacağınızı, neden önemli olduğunu ve nasıl ilerleyeceğinizi bilirsiniz.',
  'First class': 'İlk ders',
  'Wear comfortable clothes, arrive ten minutes early, and we will take care of the rest.': 'Rahat kıyafetler giyin, on dakika erken gelin; gerisini biz hallederiz.',
  'Step onto the mat': 'Mata adım at',
  'Try one class and see whether this is the practice you have been looking for.': 'Bir ders deneyin ve aradığınız pratiğin bu olup olmadığını görün.',
  'A martial arts school for focused, respectful practice.': 'Odaklı ve saygılı pratik için dövüş sanatları okulu.',
  'Martial arts school': 'Dövüş sanatları okulu',

  'Recovery sessions · mobility · recharge': 'Toparlanma seansları · hareketlilik · yenilenme',
  'Recover with': 'Niyetle',
  'intention.': 'toparlan.',
  'A focused space for mobility, restorative movement, and the reset your training week needs.': 'Hareketlilik, yenileyici hareket ve antrenman haftanızın ihtiyaç duyduğu reset için odaklı bir alan.',
  'Reserve a session': 'Seans ayırt',
  'Recovery that fits your training': 'Antrenmanınıza uyan toparlanma',
  'Choose one focused session or build a regular recovery rhythm.': 'Tek bir odaklı seans seçin veya düzenli bir toparlanma ritmi oluşturun.',
  'Mobility session': 'Hareketlilik seansı',
  'Guided movement and practical tools for everyday range of motion.': 'Günlük hareket aralığı için rehberli hareket ve pratik araçlar.',
  'Deep reset': 'Derin yenilenme',
  'A longer restorative session for busy, demanding weeks.': 'Yoğun ve zorlayıcı haftalar için daha uzun yenileyici seans.',
  'Small group': 'Küçük grup',
  'Recovery sessions for teams, clubs, and training partners.': 'Ekipler, kulüpler ve antrenman arkadaşları için toparlanma seansları.',
  'Make recovery part of the plan': 'Toparlanmayı planın parçası yapın',
  'We keep it practical: pay attention, move with intention, and leave with something useful to repeat at home.': 'Pratik tutuyoruz: dikkat edin, niyetle hareket edin ve evde tekrarlayabileceğiniz faydalı bir şeyle ayrılın.',
  'Arrive with a quick check-in': 'Kısa bir kontrolle gelin',
  'Choose the right level of support': 'Doğru destek düzeyini seçin',
  'Leave with a simple next step': 'Basit bir sonraki adımla ayrılın',
  'Give your week a reset': 'Haftanıza bir reset verin',
  'Send us your preferred time and we will help you choose a session.': 'Tercih ettiğiniz zamanı gönderin; seans seçmenize yardım edelim.',
  'Restorative movement for sustainable training weeks.': 'Sürdürülebilir antrenman haftaları için yenileyici hareket.',
  'Recovery studio': 'Toparlanma stüdyosu',
})

// The vertical catalogue owns its bilingual copy next to the template data.
// Merge the generated English → Turkish map here so HTML previews and exports
// never fall back to English when another vertical is added.
Object.assign(TEMPLATE_TEXT_TR, VERTICAL_TEMPLATE_TRANSLATIONS)

const PHRASE_REPLACEMENTS_TR = [
  [' handles the boring parts — hosting, forms, analytics — so your team can focus on the product.', ' barındırma, formlar ve analiz gibi yorucu işleri üstlenir; ekibiniz ürüne odaklanır.'],
  [' turns scattered tasks into one calm timeline. Plan in seconds, focus for hours.', ' dağınık görevleri sakin bir zaman çizelgesinde toplar. Saniyeler içinde planlayın, saatlerce odaklanın.'],
  ['All rights reserved.', 'Tüm hakları saklıdır.'],
  ['Read more', 'Devamını oku'],
  ['Learn more', 'Daha fazla bilgi'],
  ['View project', 'Projeyi görüntüle'],
  ['View work', 'Çalışmaları görüntüle'],
  ['Send a message', 'Mesaj gönder'],
  ['Your email', 'E-posta adresiniz'],
  ['Email address', 'E-posta adresi'],
]

function translateText(value) {
  const raw = String(value || '')
  const leading = raw.match(/^\s*/)?.[0] || ''
  const trailing = raw.match(/\s*$/)?.[0] || ''
  const text = raw.trim()
  if (!text) return raw
  let translated = TEMPLATE_TEXT_TR[text] || text
  for (const [source, target] of PHRASE_REPLACEMENTS_TR) {
    translated = translated.replaceAll(source, target)
  }
  translated = translated
    .replace(/^Why (.+)$/u, 'Neden $1?')
    .replace(/^Get (.+) free$/u, '$1 uygulamasını ücretsiz edinin')
    .replace(/^Choose (.+)$/u, '$1 planını seç')
    .replace(/^Photograph (\d+)$/u, 'Fotoğraf $1')
    .replace(/^(.+) badge$/u, '$1 rozeti')
  return `${leading}${translated}${trailing}`
}

export function localizeTemplateHtml(html, language = 'en') {
  const source = String(html || '')
  if (!source) return source
  if (typeof DOMParser === 'undefined') {
    return source.replace(/<html([^>]*)>/i, `<html$1 lang="${language}">`)
  }
  const doc = new DOMParser().parseFromString(source, 'text/html')
  doc.documentElement.lang = language
  if (language === 'tr') {
    // Titles are built as "Site | Section" or "Site — Role": translate each
    // part, since the whole string is never a dictionary entry.
    if (doc.title) doc.title = doc.title.split(/(\s[|—·]\s)/).map(translateText).join('')
    const walker = doc.createTreeWalker(doc.body, NodeFilter.SHOW_TEXT)
    let node = walker.nextNode()
    while (node) {
      if (!node.parentElement?.closest('style,script,code,pre')) node.nodeValue = translateText(node.nodeValue)
      node = walker.nextNode()
    }
    doc.body.querySelectorAll('[aria-label], [title], [placeholder]').forEach((element) => {
      for (const attribute of ['aria-label', 'title', 'placeholder']) {
        if (element.hasAttribute(attribute)) {
          element.setAttribute(attribute, translateText(element.getAttribute(attribute)))
        }
      }
    })
  }
  return `<!doctype html>\n${doc.documentElement.outerHTML}`
}
