// The large vertical-template catalogue keeps English and Turkish copy next to
// one another. Template builders use `.en`; the localization layer consumes the
// generated map below, so adding another template never silently leaves its
// Turkish version behind.
//
// The first ten categories live here; the second wave lives in templateSeeds/,
// one file per theme, and is appended below.
import { collectTranslations, copy, item, profile, variant } from './templateCopy.js'
import { MORE_VERTICAL_SEEDS } from './templateSeeds/index.js'

export { templateText } from './templateCopy.js'

// How the gallery groups its categories. Every category (core or vertical)
// names one of these ids; the picker and the wizard list categories under them.
export const TEMPLATE_GROUPS = [
  { id: 'personal', name: copy('Personal & creators', 'Kişisel ve içerik üreticileri') },
  { id: 'creative', name: copy('Creative & media', 'Yaratıcı işler ve medya') },
  { id: 'tech', name: copy('Tech & startups', 'Teknoloji ve girişimler') },
  { id: 'business', name: copy('Business & services', 'İşletme ve hizmetler') },
  { id: 'industry', name: copy('Trades, industry & mobility', 'Zanaat, sanayi ve mobilite') },
  { id: 'food', name: copy('Food, travel & hospitality', 'Yeme-içme, seyahat ve konaklama') },
  { id: 'shops', name: copy('Shops, products & pets', 'Mağazalar, ürünler ve evcil hayvanlar') },
  { id: 'health', name: copy('Health, beauty & sport', 'Sağlık, güzellik ve spor') },
  { id: 'community', name: copy('Community, culture & learning', 'Topluluk, kültür ve eğitim') },
]

const FIRST_WAVE_SEEDS = [
  {
    id: 'property', siteCategory: 'business', icon: '🏠', group: 'business',
    name: copy('Real Estate & Property', 'Emlak ve Gayrimenkul'),
    desc: copy('Homes, rentals, developments, and property advisors.', 'Evler, kiralıklar, projeler ve gayrimenkul danışmanları.'),
    profile: profile({
      nav: [copy('Properties', 'Gayrimenkuller'), copy('Our approach', 'Yaklaşımımız'), copy('Book a viewing', 'Görüntüleme ayırt')],
      badge: copy('Independent property advisors', 'Bağımsız gayrimenkul danışmanları'),
      title: copy('Find a place that fits your next chapter.', 'Bir sonraki döneminize uyan yeri bulun.'),
      lead: copy('Considered homes, clear advice, and a calmer way to make a big decision.', 'Düşünülmüş evler, net tavsiye ve büyük bir karar vermenin daha sakin yolu.'),
      cta: copy('Browse homes', 'Evleri incele'),
      sectionTitle: copy('A better shortlist', 'Daha iyi bir kısa liste'),
      sectionLead: copy('Start with places that match how you actually want to live.', 'Gerçekte nasıl yaşamak istediğinize uyan yerlerden başlayın.'),
      items: [
        item('City homes', 'Şehir evleri', 'Light-filled apartments close to the life you already enjoy.', 'Sevdiğiniz yaşama yakın, ışık alan daireler.'),
        item('Quiet escapes', 'Sakin kaçışlar', 'Homes with room to slow down, host, and stay awhile.', 'Yavaşlamak, ağırlamak ve uzun kalmak için alanı olan evler.'),
        item('New chapters', 'Yeni başlangıçlar', 'Practical guidance for a first home, move, or investment.', 'İlk ev, taşınma veya yatırım için pratik rehberlik.'),
      ],
      storyTitle: copy('Advice before pressure', 'Baskıdan önce tavsiye'),
      story: copy('We listen first, explain the trade-offs plainly, and stay useful long after the viewing.', 'Önce dinler, artıları ve eksileri açıkça anlatır, görüntülemeden sonra da faydalı kalırız.'),
      steps: [copy('Tell us what matters most', 'Sizin için en önemli olanı anlatın'), copy('See a considered shortlist', 'Düşünülmüş kısa listeyi görün'), copy('Move forward with clarity', 'Netlikle ilerleyin')],
      ctaTitle: copy('Ready to look more closely?', 'Daha yakından bakmaya hazır mısınız?'),
      ctaCopy: copy('Share a few details and we will make a thoughtful first list.', 'Birkaç ayrıntıyı paylaşın, sizin için düşünülmüş ilk listeyi hazırlayalım.'),
      footer: copy('Property advice with fewer surprises and better questions.', 'Daha az sürpriz ve daha iyi sorularla gayrimenkul danışmanlığı.'),
      familyDescriptions: {
        catalog: copy('A clear property catalogue with a practical shortlist.', 'Pratik kısa listeye sahip net bir gayrimenkul kataloğu.'),
        editorial: copy('Editorial property storytelling for distinctive spaces.', 'Özgün mekânlar için editoryal gayrimenkul hikâyesi.'),
        service: copy('A trusted advisory landing page for property decisions.', 'Gayrimenkul kararları için güven veren danışmanlık sayfası.'),
      },
    }),
    variants: [
      variant('urban-lofts', 'indigo', 'directory', 'Urban Lofts'),
      variant('coastal-villas', 'ivory', 'catalog', 'Coastal Villas'),
      variant('family-homes', 'forest', 'editorial', 'Family Homes'),
      variant('city-rentals', 'sky', 'showcase', 'City Rentals'),
      variant('architecture-studio', 'mono', 'onepage', 'Architecture Studio'),
      variant('commercial-spaces', 'slate', 'sidebar', 'Commercial Spaces'),
      variant('new-development', 'midnight', 'directory', 'New Development'),
      variant('boutique-estates', 'plum', 'catalog', 'Boutique Estates'),
      variant('student-living', 'coral', 'editorial', 'Student Living'),
      variant('management', 'ocean', 'showcase', 'Property Management'),
    ],
  },
  {
    id: 'clinic', siteCategory: 'business', icon: '🩺', group: 'health',
    name: copy('Healthcare & Clinic', 'Sağlık ve Klinik'),
    desc: copy('Care practices, clinics, and appointment-led services.', 'Bakım pratikleri, klinikler ve randevu odaklı hizmetler.'),
    profile: profile({
      nav: [copy('Care', 'Bakım'), copy('Approach', 'Yaklaşım'), copy('Plan a visit', 'Ziyaret planla')],
      badge: copy('Clear information · thoughtful care', 'Net bilgi · özenli bakım'),
      title: copy('Care that starts with a good conversation.', 'İyi bir konuşmayla başlayan bakım.'),
      lead: copy('A calm, accessible starting point for questions, appointments, and next steps.', 'Sorular, randevular ve sonraki adımlar için sakin ve erişilebilir bir başlangıç noktası.'),
      cta: copy('Plan a visit', 'Ziyaret planla'),
      sectionTitle: copy('How we can help', 'Nasıl yardımcı olabiliriz'),
      sectionLead: copy('Simple routes to the support, information, or appointment you need.', 'İhtiyacınız olan destek, bilgi veya randevuya giden basit yollar.'),
      items: [
        item('First visit', 'İlk ziyaret', 'Bring your questions; we will make room to understand them.', 'Sorularınızı getirin; anlamak için alan açarız.'),
        item('Ongoing support', 'Sürekli destek', 'A clear rhythm for follow-ups and practical next steps.', 'Takipler ve pratik sonraki adımlar için net bir ritim.'),
        item('Helpful resources', 'Yararlı kaynaklar', 'Plain-language information to help you feel prepared.', 'Hazırlıklı hissetmenize yardımcı olan sade dilli bilgiler.'),
      ],
      storyTitle: copy('A more human visit', 'Daha insani bir ziyaret'),
      story: copy('We make the process easier to understand, leave time for questions, and help you know what happens next.', 'Süreci anlamayı kolaylaştırır, sorular için zaman bırakır ve sırada ne olduğunu bilmenize yardımcı oluruz.'),
      steps: [copy('Choose the right visit', 'Doğru ziyareti seçin'), copy('Share what you need', 'İhtiyacınızı paylaşın'), copy('Leave with a clear next step', 'Net bir sonraki adımla ayrılın')],
      ctaTitle: copy('Start with the right information', 'Doğru bilgiyle başlayın'),
      ctaCopy: copy('Email us before booking if you are unsure which visit is right for you.', 'Size hangi ziyaretin uygun olduğundan emin değilseniz rezervasyondan önce e-posta gönderin.'),
      footer: copy('Clear care information for calmer next steps.', 'Daha sakin sonraki adımlar için net bakım bilgisi.'),
      familyDescriptions: {
        catalog: copy('An easy-to-scan practice and services catalogue.', 'Kolayca taranabilen pratik ve hizmet kataloğu.'),
        service: copy('A welcoming practice page with clear care routes.', 'Net bakım yolları olan sıcak karşılayan pratik sayfası.'),
        editorial: copy('A calmer story-led page for a specialist practice.', 'Uzman bir pratik için daha sakin, hikâye odaklı sayfa.'),
        booking: copy('Appointment-first care with practical visit details.', 'Pratik ziyaret ayrıntılarıyla randevu öncelikli bakım.'),
      },
    }),
    variants: [
      variant('family-care', 'ocean', 'service', 'Family Care'),
      variant('dental-studio', 'ivory', 'booking', 'Dental Studio'),
      variant('physio-motion', 'forest', 'onepage', 'Physio Motion'),
      variant('skin-clinic', 'plum', 'sidebar', 'Skin Clinic'),
      variant('therapy-room', 'coral', 'editorial', 'Therapy Room'),
      variant('veterinary-care', 'sky', 'magazine', 'Veterinary Care'),
      variant('optic-house', 'mono', 'service', 'Optic House'),
      variant('womens-health', 'midnight', 'booking', "Women's Health", 'Kadın Sağlığı'),
      variant('sleep-clinic', 'slate', 'onepage', 'Sleep Clinic'),
      variant('medical-practice', 'indigo', 'sidebar', 'Medical Practice'),
    ],
  },
  {
    id: 'education', siteCategory: 'business', icon: '🎓', group: 'community',
    name: copy('Education & Courses', 'Eğitim ve Kurslar'),
    desc: copy('Academies, workshops, lessons, and cohort-based learning.', 'Akademiler, atölyeler, dersler ve kohort tabanlı öğrenme.'),
    profile: profile({
      nav: [copy('Learn', 'Öğren'), copy('Method', 'Yöntem'), copy('Join a class', 'Derse katıl')],
      badge: copy('Practical learning for curious people', 'Meraklı insanlar için pratik öğrenme'),
      title: copy('Learn the thing you came here to learn.', 'Öğrenmek için geldiğiniz şeyi gerçekten öğrenin.'),
      lead: copy('Clear lessons, generous feedback, and a community that keeps you moving.', 'Net dersler, cömert geri bildirim ve sizi hareket halinde tutan bir topluluk.'),
      cta: copy('Explore classes', 'Dersleri keşfet'),
      sectionTitle: copy('Choose your next skill', 'Bir sonraki becerinizi seçin'),
      sectionLead: copy('Small, focused learning paths that lead somewhere useful.', 'Faydalı bir yere götüren küçük ve odaklı öğrenme yolları.'),
      items: [
        item('Live learning', 'Canlı öğrenme', 'Work through ideas with an instructor and a small group.', 'Bir eğitmen ve küçük grupla fikirleri birlikte çalışın.'),
        item('Guided practice', 'Rehberli pratik', 'Useful exercises that turn a lesson into a real skill.', 'Dersi gerçek beceriye dönüştüren faydalı alıştırmalar.'),
        item('A useful finish', 'Faydalı bir sonuç', 'Leave with something made, understood, or ready to use.', 'Üretilmiş, anlaşılmış veya kullanıma hazır bir şeyle ayrılın.'),
      ],
      storyTitle: copy('Learning with momentum', 'İvmeyle öğrenmek'),
      story: copy('Our programmes are structured enough to guide you and open enough for your own questions and pace.', 'Programlarımız size rehberlik edecek kadar yapılandırılmış, kendi sorularınıza ve temponuza alan açacak kadar açıktır.'),
      steps: [copy('Pick a path', 'Bir yol seçin'), copy('Make time to practise', 'Pratik için zaman ayırın'), copy('Keep building with feedback', 'Geri bildirimle gelişmeye devam edin')],
      ctaTitle: copy('Your next class is a good place to start', 'Bir sonraki dersiniz başlamak için iyi bir yer'),
      ctaCopy: copy('Tell us what you want to learn and we will point you to the right format.', 'Ne öğrenmek istediğinizi söyleyin; sizi doğru formata yönlendirelim.'),
      footer: copy('Thoughtful learning for skills that travel with you.', 'Sizinle birlikte ilerleyen beceriler için düşünülmüş öğrenme.'),
      familyDescriptions: {
        catalog: copy('A clear course catalogue with practical learning paths.', 'Pratik öğrenme yolları olan net kurs kataloğu.'),
        service: copy('A conversion-focused page for tutoring and coaching.', 'Özel ders ve koçluk için dönüşüm odaklı sayfa.'),
        editorial: copy('A story-led workshop or programme page.', 'Hikâye odaklı atölye veya program sayfası.'),
        booking: copy('A schedule-first school and class booking page.', 'Takvim öncelikli okul ve ders rezervasyon sayfası.'),
      },
    }),
    variants: [
      variant('course-academy', 'indigo', 'magazine', 'Course Academy'),
      variant('language-lab', 'coral', 'service', 'Language Lab'),
      variant('coding-school', 'slate', 'onepage', 'Coding School'),
      variant('music-school', 'plum', 'directory', 'Music School'),
      variant('tutoring-studio', 'sky', 'editorial', 'Tutoring Studio'),
      variant('design-workshop', 'ivory', 'sidebar', 'Design Workshop'),
      variant('kids-academy', 'forest', 'magazine', 'Kids Academy'),
      variant('online-cohort', 'midnight', 'service', 'Online Cohort'),
      variant('university-program', 'press', 'onepage', 'University Program'),
      variant('driving-school', 'ocean', 'directory', 'Driving School'),
    ],
  },
  {
    id: 'travel', siteCategory: 'business', icon: '✈️', group: 'food',
    name: copy('Travel & Hospitality', 'Seyahat ve Konaklama'),
    desc: copy('Stays, guides, tours, and hospitality brands.', 'Konaklamalar, rehberler, turlar ve misafirperverlik markaları.'),
    profile: profile({
      nav: [copy('Stay', 'Konakla'), copy('Story', 'Hikâye'), copy('Plan a trip', 'Gezi planla')],
      badge: copy('Stay longer · notice more', 'Daha uzun kalın · daha fazlasını fark edin'),
      title: copy('A better way to arrive somewhere new.', 'Yeni bir yere varmanın daha iyi yolu.'),
      lead: copy('Thoughtful places, local notes, and room in the day for a little surprise.', 'Düşünülmüş yerler, yerel notlar ve gün içinde küçük sürprizlere alan.'),
      cta: copy('Plan your stay', 'Konaklamanı planla'),
      sectionTitle: copy('Make the place part of the trip', 'Mekânı gezinin parçası yapın'),
      sectionLead: copy('Every stay, route, or table is chosen for the story around it.', 'Her konaklama, rota veya masa çevresindeki hikâye için seçilir.'),
      items: [
        item('Stay well', 'İyi konaklayın', 'Rooms and spaces made for a slower, more generous visit.', 'Daha yavaş ve cömert bir ziyaret için tasarlanmış odalar ve alanlar.'),
        item('Follow a local thread', 'Yerel bir izi takip edin', 'Small recommendations that lead beyond the obvious.', 'Aşikar olanın ötesine götüren küçük öneriler.'),
        item('Leave with a memory', 'Bir anıyla ayrılın', 'Experiences with enough texture to stay with you.', 'Sizinle kalacak kadar dokusu olan deneyimler.'),
      ],
      storyTitle: copy('Hospitality, not a checklist', 'Kontrol listesi değil, misafirperverlik'),
      story: copy('We make the practical parts simple so you can spend more time noticing the place you came to see.', 'Pratik kısımları basitleştiririz; böylece görmek için geldiğiniz yeri fark etmeye daha çok zamanınız kalır.'),
      steps: [copy('Choose your rhythm', 'Kendi ritminizi seçin'), copy('Save a few local notes', 'Birkaç yerel not kaydedin'), copy('Arrive with room to wander', 'Gezmek için alan bırakarak varın')],
      ctaTitle: copy('Let us help with the first plan', 'İlk plana yardımcı olmamıza izin verin'),
      ctaCopy: copy('Tell us when you are coming and what kind of trip you need.', 'Ne zaman geleceğinizi ve nasıl bir gezi istediğinizi söyleyin.'),
      footer: copy('Thoughtful stays and local experiences, well connected.', 'İyi bağlantılı düşünülmüş konaklamalar ve yerel deneyimler.'),
      familyDescriptions: {
        catalog: copy('A trip and experience catalogue made for browsing.', 'Gezinmek için tasarlanmış gezi ve deneyim kataloğu.'),
        service: copy('A confident landing page for a travel operator.', 'Seyahat işletmesi için güven veren açılış sayfası.'),
        editorial: copy('Editorial storytelling for a memorable destination.', 'Unutulmaz bir destinasyon için editoryal hikâye anlatımı.'),
        booking: copy('A stay-first page with booking and arrival details.', 'Rezervasyon ve varış ayrıntılarıyla konaklama öncelikli sayfa.'),
      },
    }),
    variants: [
      variant('boutique-hotel', 'ivory', 'showcase', 'Boutique Hotel'),
      variant('city-hostel', 'coral', 'editorial', 'City Hostel'),
      variant('coastal-stay', 'ocean', 'directory', 'Coastal Stay'),
      variant('mountain-lodge', 'forest', 'magazine', 'Mountain Lodge'),
      variant('food-tour', 'press', 'catalog', 'Food Tour'),
      variant('villa-rental', 'plum', 'booking', 'Villa Rental'),
      variant('campground', 'noir', 'showcase', 'Campground'),
      variant('local-guide', 'sky', 'editorial', 'Local Guide'),
      variant('adventure-trips', 'midnight', 'directory', 'Adventure Trips'),
      variant('tour-operator', 'indigo', 'magazine', 'Tour Operator'),
    ],
  },
  {
    id: 'beauty', siteCategory: 'business', icon: '✨', group: 'health',
    name: copy('Beauty & Salon', 'Güzellik ve Salon'),
    desc: copy('Studios, rituals, artists, and appointment-led beauty brands.', 'Stüdyolar, ritüeller, sanatçılar ve randevu odaklı güzellik markaları.'),
    profile: profile({
      nav: [copy('Services', 'Hizmetler'), copy('Studio', 'Stüdyo'), copy('Book now', 'Şimdi ayırt')],
      badge: copy('Good work · good conversation', 'İyi iş · iyi sohbet'),
      title: copy('A little time set aside for you.', 'Sizin için ayrılmış biraz zaman.'),
      lead: copy('A considered studio experience with clear pricing, calm hands, and room to feel like yourself.', 'Net fiyatlar, sakin eller ve kendiniz gibi hissetmeniz için alanla düşünülmüş stüdyo deneyimi.'),
      cta: copy('Book an appointment', 'Randevu ayırt'),
      sectionTitle: copy('Choose your ritual', 'Ritüelinizi seçin'),
      sectionLead: copy('Simple services, thoughtful details, and no pressure to overdo it.', 'Basit hizmetler, düşünülmüş ayrıntılar ve abartmanız için hiçbir baskı yok.'),
      items: [
        item('Signature service', 'İmza hizmet', 'Our most-requested appointment, designed around your day.', 'Gününüz etrafında tasarlanan, en çok istenen randevumuz.'),
        item('A quiet reset', 'Sakin yenilenme', 'Time, care, and a slower pace when you need it.', 'İhtiyacınız olduğunda zaman, özen ve daha yavaş tempo.'),
        item('Event ready', 'Etkinliğe hazır', 'A little extra planning for the days you want to remember.', 'Hatırlamak istediğiniz günler için biraz daha planlama.'),
      ],
      storyTitle: copy('Details make the feeling', 'Ayrıntılar hissi oluşturur'),
      story: copy('We work carefully, explain what we are doing, and make the whole visit feel easier than your week.', 'Dikkatle çalışır, ne yaptığımızı açıklarız ve tüm ziyareti haftanızdan daha kolay hissettiririz.'),
      steps: [copy('Choose a service', 'Bir hizmet seçin'), copy('Find a time that works', 'Uyan bir zaman bulun'), copy('Arrive and exhale', 'Gelin ve nefes verin')],
      ctaTitle: copy('Find your next appointment', 'Bir sonraki randevunuzu bulun'),
      ctaCopy: copy('Send us a note if you would like help choosing the right service.', 'Doğru hizmeti seçmek için yardım isterseniz bize not gönderin.'),
      footer: copy('Thoughtful beauty services, made personal.', 'Kişisel hale getirilmiş düşünülmüş güzellik hizmetleri.'),
      familyDescriptions: {
        catalog: copy('A polished service catalogue for beauty studios.', 'Güzellik stüdyoları için özenli hizmet kataloğu.'),
        service: copy('A direct service and consultation landing page.', 'Doğrudan hizmet ve danışma açılış sayfası.'),
        editorial: copy('A brand-led editorial page for artists and ateliers.', 'Sanatçılar ve atölyeler için marka odaklı editoryal sayfa.'),
        booking: copy('An appointment-first salon experience.', 'Randevu öncelikli salon deneyimi.'),
      },
    }),
    variants: [
      variant('hair-atelier', 'ivory', 'booking', 'Hair Atelier'),
      variant('nail-studio', 'coral', 'showcase', 'Nail Studio'),
      variant('skin-ritual', 'plum', 'service', 'Skin Ritual'),
      variant('barbershop', 'noir', 'onepage', 'Barbershop'),
      variant('bridal-beauty', 'press', 'editorial', 'Bridal Beauty'),
      variant('lash-studio', 'midnight', 'sidebar', 'Lash Studio'),
      variant('spa-house', 'forest', 'booking', 'Spa House'),
      variant('tattoo-studio', 'mono', 'showcase', 'Tattoo Studio'),
      variant('makeup-artist', 'sky', 'service', 'Makeup Artist'),
      variant('fragrance-studio', 'ocean', 'onepage', 'Fragrance Studio'),
    ],
  },
  {
    id: 'legal-finance', siteCategory: 'business', icon: '⚖️', group: 'business',
    name: copy('Legal & Finance', 'Hukuk ve Finans'),
    desc: copy('Advisors, firms, planning practices, and trusted specialists.', 'Danışmanlar, firmalar, planlama pratikleri ve güvenilen uzmanlar.'),
    profile: profile({
      nav: [copy('Expertise', 'Uzmanlık'), copy('Perspective', 'Bakış açısı'), copy('Talk to us', 'Bizimle konuşun')],
      badge: copy('Clear advice for consequential decisions', 'Önemli kararlar için net tavsiye'),
      title: copy('Good decisions need a clearer view.', 'İyi kararlar daha net bir bakış gerektirir.'),
      lead: copy('Practical expertise, plain language, and a partnership built for the long term.', 'Pratik uzmanlık, sade dil ve uzun vadeye uygun ortaklık.'),
      cta: copy('Start a conversation', 'Bir görüşme başlat'),
      sectionTitle: copy('Where we add clarity', 'Nerede netlik katıyoruz'),
      sectionLead: copy('Focused support for decisions that deserve more than a quick answer.', 'Hızlı yanıttan fazlasını hak eden kararlar için odaklı destek.'),
      items: [
        item('A clear first view', 'Net ilk bakış', 'Understand the options, the risks, and the useful next question.', 'Seçenekleri, riskleri ve faydalı sonraki soruyu anlayın.'),
        item('Practical planning', 'Pratik planlama', 'Turn a complicated situation into a sequence you can act on.', 'Karmaşık bir durumu uygulayabileceğiniz bir sıraya dönüştürün.'),
        item('A steady partner', 'İstikrarlı ortak', 'Advice that stays useful as the situation changes.', 'Durum değiştikçe de faydalı kalan tavsiye.'),
      ],
      storyTitle: copy('Serious work, plainly explained', 'Ciddi iş, açıkça anlatılır'),
      story: copy('We take the detail seriously and make sure you can see the decision in front of you.', 'Ayrıntıyı ciddiye alır ve önünüzdeki kararı görebilmenizi sağlarız.'),
      steps: [copy('Share the situation', 'Durumu paylaşın'), copy('See the practical options', 'Pratik seçenekleri görün'), copy('Move with confidence', 'Güvenle ilerleyin')],
      ctaTitle: copy('Start with a useful first conversation', 'Faydalı bir ilk görüşmeyle başlayın'),
      ctaCopy: copy('Send a short outline and we will suggest the right next step.', 'Kısa bir özet gönderin; doğru sonraki adımı önerelim.'),
      footer: copy('Clear advice for decisions that matter.', 'Önemli kararlar için net tavsiye.'),
      familyDescriptions: {
        catalog: copy('A focused expertise catalogue for trusted advisors.', 'Güvenilen danışmanlar için odaklı uzmanlık kataloğu.'),
        service: copy('A credible firm site built around clear next steps.', 'Net sonraki adımlar etrafında kurulu güvenilir firma sitesi.'),
        editorial: copy('An editorial perspective page for specialist thinking.', 'Uzman bakış açısı için editoryal perspektif sayfası.'),
        booking: copy('A consultation-first route for important decisions.', 'Önemli kararlar için danışma öncelikli yol.'),
      },
    }),
    variants: [
      variant('law-firm', 'press', 'sidebar', 'Law Firm'),
      variant('family-law', 'ivory', 'service', 'Family Law'),
      variant('tax-advisory', 'indigo', 'onepage', 'Tax Advisory'),
      variant('wealth-planning', 'forest', 'editorial', 'Wealth Planning'),
      variant('accounting-studio', 'sky', 'magazine', 'Accounting Studio'),
      variant('insurance-advisor', 'ocean', 'catalog', 'Insurance Advisor'),
      variant('startup-legal', 'slate', 'sidebar', 'Startup Legal'),
      variant('mortgage-advisor', 'plum', 'service', 'Mortgage Advisor'),
      variant('compliance-counsel', 'mono', 'onepage', 'Compliance Counsel'),
      variant('investment-research', 'midnight', 'editorial', 'Investment Research'),
    ],
  },
  {
    id: 'home-services', siteCategory: 'business', icon: '🛠️', group: 'industry',
    name: copy('Home Services', 'Ev Hizmetleri'),
    desc: copy('Trusted teams for homes, repairs, upgrades, and everyday care.', 'Evler, onarımlar, iyileştirmeler ve günlük bakım için güvenilen ekipler.'),
    profile: profile({
      nav: [copy('Services', 'Hizmetler'), copy('How it works', 'Nasıl çalışır'), copy('Get a quote', 'Teklif al')],
      badge: copy('Practical work, properly finished', 'Pratik işler, gerektiği gibi tamamlanır'),
      title: copy('The kind of help you are glad to have saved.', 'Kaydettiğinize memnun olacağınız türden yardım.'),
      lead: copy('Clear quotes, reliable visits, and work that looks after the details.', 'Net teklifler, güvenilir ziyaretler ve ayrıntıları gözeten işler.'),
      cta: copy('Request a quote', 'Teklif iste'),
      sectionTitle: copy('A capable team for the job', 'İş için yetkin bir ekip'),
      sectionLead: copy('From a small repair to a longer project, start with a clear conversation.', 'Küçük onarımdan uzun projeye kadar net bir konuşmayla başlayın.'),
      items: [
        item('Fix and maintain', 'Onar ve koru', 'Reliable help for the things that need attention now.', 'Şimdi ilgi gerektiren şeyler için güvenilir yardım.'),
        item('Improve the everyday', 'Günlüğü iyileştir', 'Thoughtful upgrades that make the home work better.', 'Evin daha iyi çalışmasını sağlayan düşünülmüş iyileştirmeler.'),
        item('Plan a bigger change', 'Büyük değişimi planla', 'A practical route from first idea to finished work.', 'İlk fikirden tamamlanmış işe pratik bir yol.'),
      ],
      storyTitle: copy('Clear from the first visit', 'İlk ziyaretten itibaren net'),
      story: copy('We explain the work, the timing, and the options so there are fewer surprises later.', 'İşi, zamanı ve seçenekleri açıklarız; böylece sonrasında daha az sürpriz olur.'),
      steps: [copy('Tell us what needs doing', 'Yapılması gerekeni anlatın'), copy('Get a clear plan and quote', 'Net plan ve teklif alın'), copy('Choose a time that works', 'Uyan bir zaman seçin')],
      ctaTitle: copy('Make the first fix the easy part', 'İlk onarımı kolay kısım yapın'),
      ctaCopy: copy('Send a short note and a photo if helpful; we will guide the next step.', 'Kısa not ve faydalıysa fotoğraf gönderin; sonraki adımda size rehberlik edelim.'),
      footer: copy('Reliable home services for work done well.', 'İyi yapılmış işler için güvenilir ev hizmetleri.'),
      familyDescriptions: {
        catalog: copy('A practical catalogue for home and property services.', 'Ev ve gayrimenkul hizmetleri için pratik katalog.'),
        service: copy('A direct service site built for quote requests.', 'Teklif istekleri için kurulu doğrudan hizmet sitesi.'),
        editorial: copy('A story-led studio page for crafted home work.', 'Özenli ev işleri için hikâye odaklı stüdyo sayfası.'),
        booking: copy('A booking route for visits, cleaning, and maintenance.', 'Ziyaret, temizlik ve bakım için rezervasyon yolu.'),
      },
    }),
    variants: [
      variant('interior-studio', 'ivory', 'service', 'Interior Studio'),
      variant('renovation-co', 'coral', 'booking', 'Renovation Co.'),
      variant('plumbing-pro', 'sky', 'onepage', 'Plumbing Pro'),
      variant('electric-works', 'indigo', 'directory', 'Electric Works'),
      variant('landscaping', 'forest', 'catalog', 'Landscaping'),
      variant('cleaning-service', 'ocean', 'showcase', 'Cleaning Service'),
      variant('solar-installers', 'noir', 'service', 'Solar Installers'),
      variant('hvac-care', 'slate', 'booking', 'HVAC Care'),
      variant('pool-garden', 'plum', 'onepage', 'Pool & Garden'),
      variant('smart-home', 'mono', 'directory', 'Smart Home'),
    ],
  },
  {
    id: 'community', siteCategory: 'other', icon: '🤝', group: 'community',
    name: copy('Nonprofit & Community', 'Topluluk ve STK'),
    desc: copy('Clubs, causes, local groups, and community initiatives.', 'Kulüpler, amaçlar, yerel gruplar ve topluluk girişimleri.'),
    profile: profile({
      nav: [copy('Get involved', 'Katıl'), copy('Our work', 'Çalışmalarımız'), copy('Join us', 'Bize katıl')],
      badge: copy('Small actions add up', 'Küçük eylemler birikir'),
      title: copy('A place for people who want to help.', 'Yardım etmek isteyen insanlar için bir yer.'),
      lead: copy('Bring your time, ideas, skills, or simply your attention to something worth doing together.', 'Zamanınızı, fikirlerinizi, becerilerinizi veya yalnızca dikkatinizi birlikte yapmaya değer bir şeye getirin.'),
      cta: copy('Get involved', 'Katıl'),
      sectionTitle: copy('There is a way in', 'İçeri girmenin bir yolu var'),
      sectionLead: copy('Choose the kind of contribution that fits where you are right now.', 'Şu an bulunduğunuz yere uyan katkı biçimini seçin.'),
      items: [
        item('Give time', 'Zaman ayır', 'Join a practical project, event, or regular shift.', 'Pratik projeye, etkinliğe veya düzenli göreve katılın.'),
        item('Share a skill', 'Becerini paylaş', 'Bring what you know to a group that can use it.', 'Bildiklerinizi bunları kullanabilecek bir gruba getirin.'),
        item('Spread the word', 'Haberi yay', 'Help more people find the work and the community.', 'Daha çok insanın işi ve topluluğu bulmasına yardım edin.'),
      ],
      storyTitle: copy('Built with the people in the room', 'Odada bulunan insanlarla kuruldu'),
      story: copy('We make room for practical help, long conversations, and the local knowledge that makes change last.', 'Pratik yardım, uzun sohbetler ve değişimi kalıcı kılan yerel bilgi için alan açarız.'),
      steps: [copy('Find a small way in', 'Küçük bir giriş yolu bulun'), copy('Meet the people doing the work', 'İşi yapan insanlarla tanışın'), copy('Keep showing up', 'Gelmeye devam edin')],
      ctaTitle: copy('There is room for you here', 'Burada sizin için de yer var'),
      ctaCopy: copy('Send a note about what brings you here and we will share a good next step.', 'Sizi buraya getiren şeyi anlatan bir not gönderin; iyi bir sonraki adımı paylaşalım.'),
      footer: copy('Practical community work, made together.', 'Birlikte yapılan pratik topluluk çalışması.'),
      familyDescriptions: {
        catalog: copy('A clear way to browse community programmes and support.', 'Topluluk programlarını ve desteği incelemenin net yolu.'),
        editorial: copy('A story-led page for a cause and its people.', 'Bir amaç ve insanları için hikâye odaklı sayfa.'),
        booking: copy('An event and membership page for local participation.', 'Yerel katılım için etkinlik ve üyelik sayfası.'),
      },
    }),
    variants: [
      variant('hub', 'indigo', 'magazine', 'Community Hub'),
      variant('animal-rescue', 'forest', 'editorial', 'Animal Rescue'),
      variant('climate-action', 'ocean', 'directory', 'Climate Action'),
      variant('food-bank', 'coral', 'service', 'Food Bank'),
      variant('youth-club', 'sky', 'onepage', 'Youth Club'),
      variant('arts-foundation', 'plum', 'showcase', 'Arts Foundation'),
      variant('mutual-aid', 'noir', 'magazine', 'Mutual Aid'),
      variant('local-library', 'ivory', 'editorial', 'Local Library'),
      variant('sports-club', 'slate', 'directory', 'Sports Club'),
      variant('civic-campaign', 'press', 'service', 'Civic Campaign'),
    ],
  },
  {
    id: 'entertainment', siteCategory: 'other', icon: '🎵', group: 'creative',
    name: copy('Music & Entertainment', 'Müzik ve Eğlence'),
    desc: copy('Artists, venues, events, labels, and culture-led projects.', 'Sanatçılar, mekânlar, etkinlikler, plak şirketleri ve kültür odaklı projeler.'),
    profile: profile({
      nav: [copy('Listen', 'Dinle'), copy('Story', 'Hikâye'), copy('Tickets', 'Biletler')],
      badge: copy('Made for the people who show up', 'Gelen insanlar için üretildi'),
      title: copy('Make a night, a record, or a room feel memorable.', 'Bir geceyi, kaydı veya odayı unutulmaz hissettirin.'),
      lead: copy('A home for releases, shows, scenes, and the community around the sound.', 'Yayınlar, gösteriler, sahneler ve sesin etrafındaki topluluk için bir ev.'),
      cta: copy('See what is on', 'Programı gör'),
      sectionTitle: copy('Something worth showing up for', 'Gelmek için değer bir şey'),
      sectionLead: copy('New work, good rooms, and a little more reason to stay out late.', 'Yeni işler, iyi mekânlar ve geç saate kadar dışarıda kalmak için biraz daha neden.'),
      items: [
        item('New release', 'Yeni yayın', 'A first listen, a closer look, and the story behind it.', 'İlk dinleme, daha yakından bakış ve arkasındaki hikâye.'),
        item('Live night', 'Canlı gece', 'A room with the right sound, light, and people in it.', 'Doğru sesin, ışığın ve insanların olduğu bir oda.'),
        item('Keep in touch', 'Bağlantıda kal', 'Notes and announcements for the next thing worth seeing.', 'Görmeye değer sonraki şey için notlar ve duyurular.'),
      ],
      storyTitle: copy('Culture happens in the details', 'Kültür ayrıntılarda olur'),
      story: copy('We care about the programme, the poster, the door, and the feeling people take home afterwards.', 'Programa, postere, kapıya ve insanların sonrasında eve götürdüğü hisse önem veririz.'),
      steps: [copy('Find the next show', 'Sonraki gösteriyi bulun'), copy('Bring someone along', 'Yanınıza birini alın'), copy('Stay for the last song', 'Son şarkıya kadar kalın')],
      ctaTitle: copy('Keep the next date open', 'Bir sonraki tarih için yer açın'),
      ctaCopy: copy('Join the list for new releases, early tickets, and good local news.', 'Yeni yayınlar, erken biletler ve iyi yerel haberler için listeye katılın.'),
      footer: copy('Culture, sound, and good reasons to gather.', 'Kültür, ses ve bir araya gelmek için iyi nedenler.'),
      familyDescriptions: {
        catalog: copy('A catalogue for releases, programmes, and culture projects.', 'Yayınlar, programlar ve kültür projeleri için katalog.'),
        editorial: copy('A visual story page for artists and creative work.', 'Sanatçılar ve yaratıcı işler için görsel hikâye sayfası.'),
        booking: copy('A programme and ticket page for live events.', 'Canlı etkinlikler için program ve bilet sayfası.'),
      },
    }),
    variants: [
      variant('artist-release', 'midnight', 'showcase', 'Artist Release'),
      variant('dj-night', 'noir', 'magazine', 'DJ Night'),
      variant('indie-label', 'plum', 'directory', 'Indie Label'),
      variant('festival', 'coral', 'booking', 'Festival'),
      variant('podcast-network', 'ocean', 'editorial', 'Podcast Network'),
      variant('live-venue', 'slate', 'onepage', 'Live Venue'),
      variant('comedy-night', 'sky', 'showcase', 'Comedy Night'),
      variant('film-club', 'press', 'magazine', 'Film Club'),
      variant('theatre-company', 'ivory', 'directory', 'Theatre Company'),
      variant('dance-studio', 'forest', 'booking', 'Dance Studio'),
    ],
  },
  {
    id: 'mobility', siteCategory: 'business', icon: '🚗', group: 'industry',
    name: copy('Automotive & Mobility', 'Otomotiv ve Mobilite'),
    desc: copy('Vehicles, garages, rental fleets, and movement-led brands.', 'Araçlar, garajlar, kiralık filolar ve hareket odaklı markalar.'),
    profile: profile({
      nav: [copy('Explore', 'Keşfet'), copy('Why us', 'Neden biz'), copy('Book a visit', 'Ziyaret ayırt')],
      badge: copy('Move with more confidence', 'Daha çok güvenle hareket edin'),
      title: copy('A smarter route from here to there.', 'Buradan oraya daha akıllı bir rota.'),
      lead: copy('Practical choices, well-kept machines, and service that respects your time.', 'Pratik seçenekler, iyi bakılmış makineler ve zamanınıza saygı duyan hizmet.'),
      cta: copy('Explore options', 'Seçenekleri keşfet'),
      sectionTitle: copy('Choose the way you move', 'Hareket biçiminizi seçin'),
      sectionLead: copy('Find the vehicle, service, or route that makes the everyday easier.', 'Günlük hayatı kolaylaştıran araç, hizmet veya rotayı bulun.'),
      items: [
        item('Ready to go', 'Yola hazır', 'Well-presented options with the details already clear.', 'Ayrıntıları şimdiden net olan, iyi sunulmuş seçenekler.'),
        item('Kept in shape', 'Formda tutulur', 'Care, repair, and maintenance that stays practical.', 'Pratik kalan bakım, onarım ve koruma.'),
        item('Made for the journey', 'Yolculuk için yapıldı', 'Useful support before the keys, the route, or the booking.', 'Anahtardan, rotadan veya rezervasyondan önce faydalı destek.'),
      ],
      storyTitle: copy('Good service keeps things moving', 'İyi hizmet işleri hareket halinde tutar'),
      story: copy('We keep the information honest, the process simple, and the next decision easy to make.', 'Bilgiyi dürüst, süreci basit, sonraki kararı da kolay tutarız.'),
      steps: [copy('See the right options', 'Doğru seçenekleri görün'), copy('Ask the useful questions', 'Faydalı soruları sorun'), copy('Get moving with confidence', 'Güvenle yola çıkın')],
      ctaTitle: copy('Let us help with the next move', 'Sonraki hareketinizde yardımcı olalım'),
      ctaCopy: copy('Tell us what you need and we will point you to the right route.', 'Neye ihtiyacınız olduğunu söyleyin; sizi doğru rotaya yönlendirelim.'),
      footer: copy('Practical mobility for the way life moves.', 'Hayatın hareket biçimi için pratik mobilite.'),
      familyDescriptions: {
        catalog: copy('A clean catalogue for vehicles, parts, and mobility options.', 'Araçlar, parçalar ve mobilite seçenekleri için temiz katalog.'),
        service: copy('A direct service site for garages and specialists.', 'Garajlar ve uzmanlar için doğrudan hizmet sitesi.'),
        editorial: copy('A story-led page for movement and machine culture.', 'Hareket ve makine kültürü için hikâye odaklı sayfa.'),
        booking: copy('A booking-first page for rentals, visits, and services.', 'Kiralama, ziyaret ve hizmetler için rezervasyon öncelikli sayfa.'),
      },
    }),
    variants: [
      variant('car-dealer', 'indigo', 'directory', 'Car Dealer'),
      variant('ev-garage', 'forest', 'catalog', 'EV Garage'),
      variant('motorcycle-club', 'noir', 'service', 'Motorcycle Club'),
      variant('auto-detailer', 'slate', 'booking', 'Auto Detailer'),
      variant('bike-shop', 'ocean', 'showcase', 'Bike Shop'),
      variant('rental-fleet', 'sky', 'onepage', 'Rental Fleet'),
      variant('repair-garage', 'coral', 'directory', 'Repair Garage'),
      variant('car-wash', 'plum', 'catalog', 'Car Wash'),
      variant('parts-catalog', 'mono', 'service', 'Parts Catalog'),
      variant('driving-school', 'ivory', 'booking', 'Driving School'),
    ],
  },
]

export const VERTICAL_CATEGORY_SEEDS = [...FIRST_WAVE_SEEDS, ...MORE_VERTICAL_SEEDS]

// One description per structural family, used when a category does not phrase
// it in its own words. These describe the LAYOUT rather than the trade, because
// the layout is what the reader is actually choosing between once palette and
// copy are separate axes.
export const FAMILY_DESCRIPTIONS = {
  catalog: copy(
    'A practical catalogue: split hero, stat row, then a grid of three.',
    'Pratik katalog: bölünmüş hero, istatistik satırı ve üçlü ızgara.',
  ),
  service: copy(
    'Centred hero, services grid, then a story beside a numbered process.',
    'Ortalanmış hero, hizmet ızgarası ve numaralı süreçle yan yana hikâye.',
  ),
  editorial: copy(
    'Story first: a tall opening, a picture-led narrative, then the work.',
    'Önce hikâye: uzun bir açılış, görsel odaklı anlatı, sonra işler.',
  ),
  booking: copy(
    'Appointment-first, with the steps of a visit laid out as cards.',
    'Randevu öncelikli; ziyaretin adımları kart olarak sıralanır.',
  ),
  sidebar: copy(
    'Navigation lives in a full-height side rail, content beside it.',
    'Gezinme tam boy yan rayda yaşar, içerik onun yanında.',
  ),
  magazine: copy(
    'A masthead and a column river — a publication, not a landing page.',
    'Manşet ve sütun akışı — açılış sayfası değil, bir yayın.',
  ),
  showcase: copy(
    'Full-width alternating bands where the visuals carry the page.',
    'Sayfayı görsellerin taşıdığı, tam genişlikte alternatif bantlar.',
  ),
  directory: copy(
    'A searchable index of rows instead of a grid of cards.',
    'Kart ızgarası yerine aranabilir satır dizini.',
  ),
  onepage: copy(
    'One long scroll: numbered sections, pricing tiers and an FAQ.',
    'Tek uzun kaydırma: numaralı bölümler, fiyat paketleri ve SSS.',
  ),
  bento: copy(
    'A bento grid: hero, figures and highlights share one tiled canvas.',
    'Bento ızgarası: hero, rakamlar ve öne çıkanlar tek bir karo düzeninde.',
  ),
  split: copy(
    'Split screen: a fixed visual half beside a scrolling column of content.',
    'Bölünmüş ekran: sabit görsel yarım ve yanında kayan içerik sütunu.',
  ),
  chronicle: copy(
    'A centred timeline that tells the offer as a sequence of moments.',
    'Teklifi anlar dizisi olarak anlatan ortalanmış zaman çizelgesi.',
  ),
  poster: copy(
    'Poster type: an oversized headline, a moving ticker and big numbers.',
    'Afiş tipografisi: dev başlık, kayan şerit ve büyük numaralar.',
  ),
  stack: copy(
    'Stacked cards that pile up as you scroll, one idea per card.',
    'Kaydırdıkça üst üste binen kartlar; her kartta bir fikir.',
  ),
  letter: copy(
    'A personal letter: one narrow column of well-set type, no decoration.',
    'Kişisel bir mektup: tek dar sütunda özenli tipografi, süs yok.',
  ),
  compare: copy(
    'A comparison table that lays three options side by side.',
    'Üç seçeneği yan yana koyan karşılaştırma tablosu.',
  ),
  lookbook: copy(
    'A lookbook: large captioned visuals in an editorial grid.',
    'Lookbook: editoryal ızgarada büyük, açıklamalı görseller.',
  ),
  solo: copy(
    'One focused card on a quiet background: the sign-up is the page.',
    'Sakin bir arka plan üzerinde tek odaklı kart: kayıt formu sayfanın kendisi.',
  ),
  appshell: copy(
    'An app-style dashboard with a side menu, key figures and panels.',
    'Yan menü, temel rakamlar ve panellerle uygulama tarzı pano.',
  ),
}

// The short name the gallery shows for each layout. "classic" covers the
// hand-written core pages (CV, portfolio, landing, …).
export const FAMILY_NAMES = {
  classic: copy('Classic', 'Klasik'),
  catalog: copy('Catalogue', 'Katalog'),
  service: copy('Service', 'Hizmet'),
  editorial: copy('Editorial', 'Editoryal'),
  booking: copy('Booking', 'Rezervasyon'),
  sidebar: copy('Side rail', 'Yan menü'),
  magazine: copy('Magazine', 'Dergi'),
  showcase: copy('Showcase', 'Vitrin'),
  directory: copy('Directory', 'Dizin'),
  onepage: copy('One page', 'Tek sayfa'),
  bento: copy('Bento grid', 'Bento ızgara'),
  split: copy('Split screen', 'Bölünmüş ekran'),
  chronicle: copy('Timeline', 'Zaman çizelgesi'),
  poster: copy('Poster', 'Afiş'),
  stack: copy('Card stack', 'Kart yığını'),
  letter: copy('Letter', 'Mektup'),
  compare: copy('Comparison', 'Karşılaştırma'),
  lookbook: copy('Lookbook', 'Lookbook'),
  solo: copy('Single card', 'Tek kart'),
  appshell: copy('App dashboard', 'Uygulama paneli'),
}

// Interface words a family prints on its own, outside the category copy.
export const FAMILY_LABELS = {
  recommended: copy('Recommended', 'Önerilen'),
  whatYouGet: copy('What you get', 'Neler dahil'),
  investment: copy('Price level', 'Fiyat seviyesi'),
  emailPlaceholder: copy('Your email address', 'E-posta adresiniz'),
  search: copy('Search…', 'Ara…'),
  overview: copy('Overview', 'Genel bakış'),
  statusReady: copy('Ready', 'Hazır'),
  statusPopular: copy('Popular', 'Popüler'),
  statusNew: copy('New', 'Yeni'),
}

export const VERTICAL_TEMPLATE_TRANSLATIONS = collectTranslations([
  VERTICAL_CATEGORY_SEEDS,
  FAMILY_DESCRIPTIONS,
  FAMILY_LABELS,
  FAMILY_NAMES,
  TEMPLATE_GROUPS,
])
